### ISSUE TITLE
Access message variable from class EchoBot??? 

### ISSUE THREAD

**Issue by milo123milo** [carpedm20/fbchat#105]
Is possible to access `message` varialbe from `on_message` and put it outside `class`?
 
> import fbchat
> #subclass fbchat.Client and override required methods
> class EchoBot(fbchat.Client):
> 
>     
> 
>     def __init__(self,email, password, debug=True, user_agent=None):
>         fbchat.Client.__init__(self,email, password, debug, user_agent)
> 
>     def on_message(self, mid, author_id, author_name, message, metadata):
>         self.markAsDelivered(author_id, mid) #mark delivered
>         self.markAsRead(author_id) #mark read
>         
> 
>         print("%s said: %s"%(author_id, message))
> 
>         
> 
>         if str(author_id) != str(self.uid):
>             self.send(author_id,message)
> 
> 
> 
> bot = EchoBot
> bot.listen()

**Comment by Bankde** [comment]
This is not really related to fbchat issue haha

Try "global" variable, should work. However, using global variables is usually a bad practice.

**Comment by milo123milo** [comment]
i never heard for global variable haha can you maybe imoprt it wthit the upper code?
