### ISSUE TITLE
global name 'data' is not defined

### ISSUE THREAD

**Issue by akshay10503878** [carpedm20/fbchat#11]
Every time i am trying to login ,this error occurs.
client = fbchat.Client("User****Name", "password")
  File "~/VirtualEnvironments/PythonApi/lib/python2.7/site-packages/fbchat/client.py", line 68, in __init__
    self.data = data
NameError: global name 'data' is not defined

**Comment by PidgeyL** [comment]
I am getting the same error, both in python2.7 and 3.4

**Comment by Schmavery** [comment]
Hey guys, looks like you might be using a version of this API that is out of date.
https://github.com/carpedm20/fbchat/blob/master/fbchat/client.py#L68

This issue seems to be fixed by PR #7.  (No guarantees on the rest of the API).

**Comment by PidgeyL** [comment]
Indeed, this solved the problem.
I installed fbchat using the pip (and pip3) commands, which caused this issue. Could you update the version in pip as well please?

**Comment by Schmavery** [comment]
@carpedm20

**Comment by carpedm20** [comment]
Thanks! I'll fix this error tonight.
