### ISSUE TITLE
Support for login approvals

### ISSUE THREAD

**Issue by joenash** [carpedm20/fbchat#110]
Hey folks!

Does fbchat currently support login approvals? I had a quick flick through the docs and source, and couldn't see it. For reference, this is how facebook-chat-api supports it: https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#login

**Comment by Schmavery** [comment]
To be fair, I'm pretty sure the support in facebook-chat-api has been broken for a really long time (https://github.com/Schmavery/facebook-chat-api/issues/139).  I have many emoji hearts to give as a reward to whoever fixes it 😄

**Comment by joenash** [comment]
@Schmavery haha thanks for the quick response! I'll have a poke...is there the start of an implementation anywhere for fbchat?

**Comment by Schmavery** [comment]
Not that I know of.  There's issue #6 that also complains about the lack of support.  I've been doing my best to keep an eye out so that I could steal the implementation.

**Comment by joenash** [comment]
@Schmavery I love this mutual thievery between parallel fb-messenger chat apis

**Comment by kyjak** [comment]
So is there a solution to login either 2way auth or app pwd?

**Comment by TimLChan** [comment]
I'm halfway through a super hacky way of doing it (involves going through every single prompt every time). Will update as I go

**Comment by TimLChan** [comment]
@joenash Wondering if my PR fixed it for you?

**Comment by madsmtm** [comment]
I'm assuming it's fixed, after @TimLChan's great work!
