### ISSUE TITLE
Messaging suddenly stopped working

### ISSUE THREAD

**Issue by 1Zeus1** [carpedm20/fbchat#111]
Im working on a simple chat client so I dont always need to have my facebook open, I got this working and was messaging my friend on it while testing it.
It was all working, i closed the script then ran it again and now it gives me this error

AttributeError: 'Message' object has no attribute 'body'

This is my code 
```python
import fbchat

def login():
    email = "something"
    password = "somethingelse"
    global client
    client = fbchat.Client(email, password)
    mainloop()
def mainloop():

    global client
    name = input("Who would you like to message? (Type their full name): ")
    friends = client.getUsers(name)  # return a list of names
    friend = friends[0]
    last_messages = client.getThreadInfo(friend.uid, 0)
    last_messages.reverse()  # messages come in reversed order

    for message in last_messages:
        print(message.body)
    message = input("Type your message here: ")
    sent = client.send(friend.uid,message)
    if sent:
        print("Message sent successfully!")
        mainloop()
    else:
        print("Message not sent!")
        mainloop()
login()```

**Comment by 1Zeus1** [comment]
I cant get the code in the code tags sorry

**Comment by 1Zeus1** [comment]
So the problem was because my friend had sent me a picture which makes sense now, is there anyway around that?

**Comment by Dainius14** [comment]
Check if `message.body` is not `None` before printing
Body is basically the message itself. If only the picture was uploaded - body will be nulll.
