### ISSUE TITLE
Pip install fbchat fails

### ISSUE THREAD

**Issue by Mishqutin** [carpedm20/fbchat#113]
Command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Use
rs\\Mareczek\\AppData\\Local\\Temp\\pip_build_Mareczek\\lxml\\setup.py';exec(com
pile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __f
ile__, 'exec'))" install --record C:\Users\Mareczek\AppData\Local\Temp\pip-gzpna
hqi-record\install-record.txt --single-version-externally-managed --compile fail
ed with error code 1 in C:\Users\Mareczek\AppData\Local\Temp\pip_build_Mareczek\
lxml
Storing debug log for failure in C:\Users\Mareczek\pip\pip.log

**Comment by madsmtm** [comment]
This is a `lxml` installation error, please go to them with this problem

**Comment by QuentinCG** [comment]
I got the same issue.

You need to install some packages before lxml can compile.
Check how I did it:
https://github.com/QuentinCG/jarvis-fb-messenger/blob/master/install.sh
