### ISSUE TITLE
client.getUserInfo requires int parameter

### ISSUE THREAD

**Issue by botcs** [carpedm20/fbchat#114]
In this example code, I have to strip and recast the author_id because `fbid:` is automatically appended by the wrapper functions. 
```
    thread_list = client.getThreadList(0)
    last_thread = thread_list[0]
    messages = client.getThreadInfo(
        last_thread.thread_fbid, 0, thread_type=last_thread.thread_type)
    message = messages[0]
    name = client.getUserInfo(int(message.author[5:]))['name']
    print(name, '~', message.body)
```

However I think it would be not just convenient, but logical to make the `getter` functions accept each others' return values.

**Comment by madsmtm** [comment]
Fixed in v. `1.0.x`
