### ISSUE TITLE
Send stickers

### ISSUE THREAD

**Issue by DeadBlast** [carpedm20/fbchat#118]
How can i send multiple stickers? o.o/

**Comment by JohnathonNow** [comment]
What exactly do you mean by multiple? Do you mean send the stickers this project doesn't currently make easy to send, or do you mean multiple stickers in one message?

**Comment by SCWhite** [comment]
I think he is trying to ask "Are we able to send stickers? "
I got the same question.  
there is a "stickers.py"
but I'm not sure how it works

**Comment by JohnathonNow** [comment]
You can use
`client.send(CHAT_ID, MESSAGE, like=LIKE)`
where LIKE is 'L', 'M', or 'S', for the large thumbs up, medium thumbs up, and small thumbs up stickers, respectively. Right now there isn't an easy way to send the other stickers, however.

**Comment by SCWhite** [comment]
HI @JohnathonNow 
thank you for replying 
but I still don't understand why it's not easy to send other sticker ? 
can't we just change the sticker ID ?

in the current version, we can just send LIKES in 3 size
and I'm not sure why in "client.py" it change every unknown value to "L"
if user doesn't enter 'l' or 'm' or 's' , then use the large one

why can't we just change the sticker id?

**Comment by madsmtm** [comment]
Working on a PR, but basically, you have to send a message with an emoji, and add some extra data. Should be fairly straightforward

**Comment by JohnathonNow** [comment]
@SCWhite I just meant the library doesn't break that out for you. The library just expects a few known stickers - the varying sizes of the thumbs up sticker. If you know the other IDs then it isn't hard to add the feature.

**Comment by madsmtm** [comment]
Facebook has changed a lot of things, and `fbchat` has been updated, so I'm assuming this is outdated ;)
