### ISSUE TITLE
calling https://www.facebook.com/ajax/mercury/thread_sync.php gives 404, maybe URL needs to be updated?

### ISSUE THREAD

**Issue by stablum** [carpedm20/fbchat#124]
Hi,

the url `https://www.facebook.com/ajax/mercury/thread_sync.php` which is used by `Client.getUnread()` seems to respond always with 404. Can you please confirm this? Is the URL maybe outdated?

**Comment by ahmedelmahy** [comment]
Any suggested solution ?

**Comment by madsmtm** [comment]
Looking over it, this seems to be fixed in #269
