### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by jussumgai** [carpedm20/fbchat#127]
Attempt to login fails every time, the email and password fields supplied are correct (thrice verified).
Could it be a Python 3.6 issue?

import fbchat
client = fbchat.Client("EMAIL", "PASSWORD")

Traceback (most recent call last):
  File "C:\WERK\sendFb.py", line 3, in <module>
    client = fbchat.Client("EMAIL", "PASSWORD")
  File "C:\Python\lib\site-packages\fbchat\client.py", line 124, in __init__
    self.login(email, password, max_retries)
  File "C:\Python\lib\site-packages\fbchat\client.py", line 344, in login
    raise Exception("login failed. Check id/password")
Exception: login failed. Check id/password

**Comment by OdysLam** [comment]
I think it's an issue with the python version you are using. I run a facebook bot with this library and python2.7 smoothly

**Comment by jussumgai** [comment]
The problem was that I hadn't used the account on mobile and after login I received a popup telling me I have free access from my ISP. The current behavior of failing after 5 tries with the wrong error message (wrong password despite login success) should have an exception where the url response is displayed.

**Comment by SCWhite** [comment]
I got the same problem today
using  python 2.7 
the same code works a week ago

**Comment by madsmtm** [comment]
Try logging in on `https://m.facebook.com/login.php`, and then please post *every* url that you go through to get to the home page (Usually there's a "save device url", but there might be something more)

**Comment by SCWhite** [comment]
hey, I want to apologies for false reply
I check my code today, and realize that I type the wrong password
it run smoothly under python 2.7
and thanks @madsmtm  your advice really help

**Comment by S3jp4kCZE** [comment]
2.x works

**Comment by HizonPastorpili** [comment]
Having the same error, I can assure that my credentials are correct because after running the code Facebook runs a security check on my account question is how can I get in without this security check?
working on python 2.7
