### ISSUE TITLE
Passwords containing punctuation '#' cause login errors

### ISSUE THREAD

**Issue by amplogik** [carpedm20/fbchat#128]
If the fbpass contains '#', the fbchat.Client(fbid, fbpass) will fail.

Have verified this on a number of accounts.   Passwords containing other punctuation may also be effected.    The Client constructor needs to escape special chars properly.

**Comment by Bankde** [comment]
Strange, it works fine on my side and I don't think '#' is special char that causes problem.
Im using python2.7
However, my fbchat is still 0.6.0 which is very old already

Can anyone else verify this ?

**Comment by amplogik** [comment]
It's very strange.  Have confirmed from multiple machines.   For reasons that I cannot explain, any password containing '#' fails to log in.   Now this may be masking something else, such as password length issues which I hadn't considered, but it seems odd.    If I update the fb account password and remove '#', everything works great.   Add it back to the fb account password, and update the login info on fbchat, and I can't login again.

Tested with 3 diff fb accounts

Testing the nodejs facebook-chat-api in npm,  it seems to also have the same problem.   

This suggests to me that this issue is in  oauth tho, not fbchat.

Thought I should update you.    This may be an issue with the transport layer at facebook and not related to  the fbchat code.

**Comment by Schmavery** [comment]
@amplogik interesting.  I assume passwords containing "#" work when logging into the browser?  Would it be possible for you to inspect your network traffic when doing so and see if the "#" in the password is escaped in any way when when it is passed to facebook?

@Bankde your password contains "#" and you have no problems? hmm

**Comment by Bankde** [comment]
@Schmavery Yes, I had changed my password to contained "#" in the middle just to test this issue and it works fine. Since OP stated that he tested several times, I believe him though.

Is your password happened to start with or end with "#" ?
What version of python are you using ?
fbchat version ?
Very interesting it's now affecting nodejs too haha.
What operating system are you using ?

**Comment by madsmtm** [comment]
Can't confirm, using Ubuntu 16.04, `requests` v2.13, `fbchat` v. 0.8.2, tested on both Python 2.7 and Python 3.5, with password `#aaaa#aaaa#`

**Comment by Schmavery** [comment]
@amplogik how are you storing/retrieving your passwords?  Is this failing with passwords just hardcoded as strings in your code or is there something more complex happening on your end?

**Comment by nguyenvulong** [comment]
confirmed with password contains "@", in Windows

**Comment by madsmtm** [comment]
How did you confirm this @nguyenvulong? Can you give an example of a password that didn't work?

**Comment by nguyenvulong** [comment]
Yesterday I tried this password Xx123456@yy
After removing the "@yy" part, it's able to login successfully
Before that, it failed (I gave it 2 more times to retry)

**Comment by madsmtm** [comment]
Can't confirm, using Windows 10, `fbchat` v. 1.0.19, tested on Python 3.6, with password `Xx123456@yy`
As said above, are you sure the `@` is actually being stored correctly?
Which URL does it fail on? (Let it fail until it stops by itself, and show us the stack trace)
Maybe you could show us the code you're using?
Perhaps you could enable debugging information:
```
import logging
Client('<email>', '<password>', logging_level=logging.DEBUG)
```

**Comment by madsmtm** [comment]
I'll close this, after no response from the people able to reproduce the issue. Please reopen this if needed.
