### ISSUE TITLE
getThreadList seems not to actively check latest posts

### ISSUE THREAD

**Issue by PidgeyL** [carpedm20/fbchat#13]
From some tests I ran, it seems like `getThreadList` does not update when new messages are sent. I had to log in again to get the last messages.
Is it just me, or is this in fact the case?

**Comment by MikeCroall** [comment]
I am finding the same as you.

**Comment by madsmtm** [comment]
Facebook has changed a lot of things, and `fbchat` has been updated, so I'm assuming this is outdated ;)
