### ISSUE TITLE
AttributeError: 'module' object has no attribute 'signature'

### ISSUE THREAD

**Issue by amplogik** [carpedm20/fbchat#139]
version 0.10.0

example my_test.py:

import fbchat
client = fbchat.Client("example@example.com", "MyPassword")

When I run
python ./my_test.py

I get 
Traceback (most recent call last):
  File "./my_test.py", line 3, in <module>
    client = fbchat.Client("--[REDACTED]--", "--[REDACTED]--")
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 113, in __init__
    self.onLoggingIn += lambda email: log.info("Logging in %s..." % email)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/event_hook.py", line 26, in __iadd__
    params = inspect.signature(handler).parameters
AttributeError: 'module' object has no attribute 'signature'

Fresh install of python 2.7 on brand new machine
AttributeError: 'module' object has no attribute 'signature' would indicate a circular reference, but this is about as simple as it gets, and as you can see there is no issue with the import colliding with the name of the python script.

Works fine on old machine.   Have gone so far as to completely reinstall python.   Problem persists.

Any idea what is going on?

**Comment by amplogik** [comment]
Have discovered source of issue.   pip is installing in usr/local/lib/python2.7/dist-packages/fbchat/ , but on ubuntu it should be in /usr/lib/python2.7/dist-packages/fbchat/

If I manually move it to the right location it works.

**Comment by Dainius14** [comment]
Quick note: you left your login details :)

**Comment by Dainius14** [comment]
Second note: update fbchat. This version shouldn't have been published. It's still not tested with Python 2
