### ISSUE TITLE
0.10 not working

### ISSUE THREAD

**Issue by Fasic** [carpedm20/fbchat#143]
ValueError: This EventHook must be called with these keyword arguments: (email=str), but was called with: ({'email': <class 'str'>})

**Comment by Dainius14** [comment]
Update to 10.1

**Comment by yoshi2095** [comment]
@Dainius14 I am getting the exact same error. could you please explain how do I check the current version of fbchat, and how to update it to 10.1?

**Comment by Fasic** [comment]
I did it, go dl it from git as zip, un zip and copy all files in site-packege folder of lib. 

Now i have problem that python 3.6.1 crash on auto replay bot - -

**Comment by Dainius14** [comment]
I've just downloaded the latest release from PyPi and there's not such thing as an EventHook there yet. Are you sure you're using the latest release from Pypi? Try deleting and redownloading. If there's still a problem try an older version https://github.com/carpedm20/fbchat/archive/b804dc3f9439c08452ff8a5a8a62f7a8f2c01eb6.zip

**Comment by madsmtm** [comment]
Actually, you should make sure you're using the 0.9 version. Try `pip list`, and if you can't downgrade, uninstall `fbchat` and reinstall it.

**Comment by madsmtm** [comment]
I discovered that the issue was in PyPI, you should be able to update to the correct version now, and if not, try reinstalling it
