### ISSUE TITLE
Tests are run when they should be instantiated

### ISSUE THREAD

**Issue by Dainius14** [carpedm20/fbchat#144]
When PyCharm is saying that it is instantiating tests, they are actually being run. This leads to thing that methods can't be tested separately. Not sure where's the problem tho.

**Comment by madsmtm** [comment]
I might have figured the issue out, we were creating custom code for starting the tests, the proper way to do it is to use `python -m unittest -q tests`

**Comment by madsmtm** [comment]
We now use `pytest`, so this is no longer relevant
