### ISSUE TITLE
Handling of Approve/Refuse connection

### ISSUE THREAD

**Issue by SakiiR** [carpedm20/fbchat#147]
Hello,

I am trying to use your module to do a weechat plugin for facebook messenger.

When I did my tests, i didn't see any handling of the mobile notification Approve/Refuse Connection.

Do you know what I meant ? Thanks you, just to tell you, maybe i'll fork :)
PS: Only thing I see when i am connection is "Retrying, Retrying" and I saw your 2FA Handlers but I can't tell if it is an Handler of what I want to ?

Cya!

**Comment by madsmtm** [comment]
After returning to this, I'm sorry, but I must say, I didn't understand what you meant by "Approve/Refuse Connection". I don't use Facebook on my phone nor do I use 2FA, but maybe you can elaborate on what you mean?
If you're having trouble logging in, maybe you can give us a stack trace?

**Comment by madsmtm** [comment]
Closing, after no response from submitter

**Comment by SakiiR** [comment]
did not see the original response, sorry.

It is 3 years ago, I don't remember well :')

I think it was about handling the 2FA, that's all

**Comment by madsmtm** [comment]
Yeah, the 2FA handling is still, after those three years, pretty bad... 😁

**Comment by SakiiR** [comment]
haha ! good luck ;)
