### ISSUE TITLE
Client.on_message, None author_name

### ISSUE THREAD

**Issue by vlegoff** [carpedm20/fbchat#150]
I assume this doesn't happen with every Facebook account, for it would create some problems.  However, each time I try to display author_name, in the Client.on_message method, I get `None`.  I have the ID, so I could ask for the author in the list of users, but that would add a query.  Is it something that Facebook doesn't support anymore?

Thank you for your work,

**Comment by madsmtm** [comment]
That's exactly the reason, Facebook doesn't provide this information anymore when you receive a message. Perhaps try calling `getUserInfo` with the author_id, look at the raw data from that function, and grab the username from there (I'd recommend that you implement some sort of caching, too)
