### ISSUE TITLE
Client.listen, a forever blocking method

### ISSUE THREAD

**Issue by vlegoff** [carpedm20/fbchat#151]
I may be wrong, for the code seems to contradict it, but it seems Client.listen is a blocking method that one cannot interupt by, for instance, pressing CTRL + C.  While in a GUI application, it would be useful to have the client running in a separate thread, but being able to terminate it at any time.  Is it something possible?

**Comment by madsmtm** [comment]
I'm pretty sure the listen method supports `CTRL + C`, though haven't tested it on a windows. Anyways, you can set the variable `Client.listening` to `False` when you want the listen function to terminate
