### ISSUE TITLE
getUserInfo giving AttributeError

### ISSUE THREAD

**Issue by AbhayKD** [carpedm20/fbchat#152]
i'm trying to run the example given in the docs of user info. But it is giving me an error 
File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 907, in getUserInfo
    full_data= [details for profile,details in info['payload']['profiles'].items()]
AttributeError: 'list' object has no attribute 'items'
I've correctly passed the user id.

**Comment by madsmtm** [comment]
This function required that the passed user id is an integer. Should be fixed in `0.9.2`. I've updated PyPI
