### ISSUE TITLE
Invalid Index client bug

### ISSUE THREAD

**Issue by OdysLam** [carpedm20/fbchat#154]
Hey,

Client.py won't be able to log in because line 170 `self.payloadDefault['__rev'] = int(r.text.split('"revision":',1)[1].split(",",1)[0])` throws an error.

If you comment it out, client works as usual.

Cheers

**Comment by madsmtm** [comment]
Yes, this got fixed in v. 9.0.2 ;)
The issue was that Facebook changed their code
