### ISSUE TITLE
max_retries not logic

### ISSUE THREAD

**Issue by DennyWeinberg** [carpedm20/fbchat#156]
Passing max_retries 0 does not even tries to connect but says directly login failed.
But there should always be at least one tried.
You should adapt the error message or try always at least one times.
The name il max_retries and NOT max_tries...

**Comment by madsmtm** [comment]
That's a good suggestion! I'll look into adding it to the `development` branch

**Comment by madsmtm** [comment]
Fixed in v. `1.0.0` ;)
