### ISSUE TITLE
18-06-2017 : Facing suddenly indexerror: list index out of range even after upgrading to fbchat 0.9.3 

### ISSUE THREAD

**Issue by gerstaro** [carpedm20/fbchat#159]
Hi I m facing this issue even after upgrading to 0.9.3 

I m providing ph no in place of  FRIEND'S NAME in client.getUsers("FRIEND'S NAME") . It was working fine even yesterday. From today morning showing this problem
https://www.facebook.com/?seq=0&__req=3
Login of s********r@mail.ru successful.
Traceback (most recent call last):
  File "facechat.py", line 62, in <module>
    friend = friends[0]
IndexError: list index out of range

What is the issue ? Can yu please help? Thanks

**Comment by madsmtm** [comment]
Duplicate ;)
