### ISSUE TITLE
19-06-2017 : Facing suddenly indexerror: list index out of range even after upgrading to fbchat 0.9.3

### ISSUE THREAD

**Issue by gerstaro** [carpedm20/fbchat#161]
Hi I m facing this issue even after upgrading to 0.9.3

I m providing ph no in place of FRIEND'S NAME in client.getUsers("FRIEND'S NAME") . It was working fine till day before yesterday. From yesterday morning, was showing this problem
https://www.facebook.com/?seq=0&__req=3
Login of s********r@mail.ru successful.
Traceback (most recent call last):
File "facechat.py", line 62, in 
friend = friends[0]
IndexError: list index out of range

What is the issue ? Did facebook change anything again? Thanks

**Comment by madsmtm** [comment]
I'm guessing Facebook changed something, can you try it on v. `1.0.1`?

**Comment by madsmtm** [comment]
Closing, after no response from @gerstaro
