### ISSUE TITLE
Logins broken again as of 6/23/2017

### ISSUE THREAD

**Issue by amplogik** [carpedm20/fbchat#162]
Similar to a problem from last month,  suddenly fb logins do not work anymore.

Have tried with a number of accounts, and all result in output like the following example (user and pass masked)

It seems something has changed again.

Using latest fbchat-1.0.1

Example:
user@wwwserver# ./echobot.py
Logging in <masked email>...
Traceback (most recent call last):
  File "./echobot.py", line 21, in <module>
    bot = EchoBot("<masked email>", "<masked pass>")
  File "./echobot.py", line 8, in __init__
    fbchat.Client.__init__(self,email, password, debug, user_agent)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 73, in __init__
    self.login(email, password, max_tries)
  File "/usr/local/lib/python2.7/dist-packages/fbchat/client.py", line 318, in login
    raise Exception('Cannot login: max_tries should be at least one')
Exception: Cannot login: max_tries should be at least one

**Comment by madsmtm** [comment]
A lot of `fbchat`'s code has been updated in the new version, you're probably passing 0 to the parameter `max_tries` somewhere. Check out the [documentation](https://fbchat.readthedocs.io)

Also, next time, remember to include some of your code ;)
