### ISSUE TITLE
after facebook message it occurs an error

### ISSUE THREAD

**Issue by tonystark96** [carpedm20/fbchat#164]
i am using fbchat on django project, after it sends facebook message, there is an error like that:
![neolduu](https://user-images.githubusercontent.com/20117349/27512028-9e52d31c-593c-11e7-955e-a6921abfaf13.png)

what is wrong with this? probably there is an error with HTTPConnectionPool(host='asdadsasdasdas.com', port=80)

**Comment by madsmtm** [comment]
Perhaps you could show us some code, and steps to reproduce? ;)

**Comment by Bankde** [comment]
What is asdadsasdasdas.com ? Your error looks like it cannot resolve IP from that domain name.
