### ISSUE TITLE
AttributeError when accessing enum 'name' in Python 2.7

### ISSUE THREAD

**Issue by liamkirsh** [carpedm20/fbchat#179]
Version: Python 2.7.9, fbchat 1.0.13

When using the default Client class, the onMessage, onMessageSeen, and onMessageDelivered classes raise exceptions like the following:

`Traceback (most recent call last):
  File "/home/liam/.virtualenvs/fbchat/local/lib/python2.7/site-packages/fbchat/client.py", line 1360, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)
  File "leona.py", line 28, in onMessage
    log.info("Message from {} in {} ({}): {}".format(author_id, thread_id, thread_type.name, message))
AttributeError: 'int' object has no attribute 'name'`

This is because the Enum module treats enums as ints and doesn't support the 'name' property. Possible fixes are to use a get_thread_type function that converts an int to the enum name, or include enum34 as a dependency in requirements.txt.

**Comment by madsmtm** [comment]
I'll add `enum34` to the requirements, thanks ;)
