### ISSUE TITLE
Error #1357007 A security check is needed

### ISSUE THREAD

**Issue by chemhong** [carpedm20/fbchat#180]
Error #1357007  A security check is needed
how can i get ride of it?
thanks

**Comment by madsmtm** [comment]
Perhaps you could provide some steps to reproduce? Maybe there's something special about your account? What did you do to get this error?

**Comment by bschollnick** [comment]
Do you have 2 factor authentication turned on?

**Comment by madsmtm** [comment]
Closing, after no response from @chemhong
