### ISSUE TITLE
sendLocalImage doesn't work with Windows paths

### ISSUE THREAD

**Issue by ekauzlar** [carpedm20/fbchat#183]
The local image path provided to sendLocalImage needs to be a "/" path, windows local "\\" paths fail to upload properly.

**Comment by madsmtm** [comment]
We're using [open](https://docs.python.org/library/functions.html#open), so this is something more python related. See [this](https://mail.python.org/pipermail/tutor/2008-August/063922.html) for more help (In short, python uses `/` in windows paths)
