### ISSUE TITLE
Login successfull but library can't see it

### ISSUE THREAD

**Issue by DennyWeinberg** [carpedm20/fbchat#184]
Content of response:
`b'<?xml version="1.0" encoding="utf-8"?>\n<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Add Mobile Number</title><meta name="referrer" content="default" id="meta_referrer" /><style type="text/css">/*<![CDATA[*/.h{background-color:#3b5998;color:#fff;}.h .t{font-size:small;font-weight:normal;}.x{display:block;font-size:small;padding:5px;}.o{display:block;padding:5px;}.i .s{table-layout:fixed;width:100%;}.w{background:#6d84b4;display:inline-block;font-size:14px;font-weight:normal;margin:4px 0;padding:2px 8px;}.c .j{border:0;border-collapse:collapse;margin:0;padding:0;width:100%;}.c .j tbody{vertical-align:top;}.c .k>tr>td,.c .k>tbody>tr>td,.c .j td.k{vertical-align:middle;}.c .j td{padding:0;}.c .r{width:100%;}.p,.p.q{display:block;}.m{display:block;}.n{height:14px;width:14px;}.c a,.c a:visited{color:#3b5998;text-decoration:none;}.c .bf,.c .bf:visited{color:#6d84b4;}.c .v,.c .v:visited{color:#fff;}.c a:focus,.c a:hover,.c .bf:focus,.c .bf:hover{background-color:#3b5998;color:#fff;}.c .v:focus,.c .v:hover{background-color:#fff;color:#3b5998;}.q{border:0;display:inline-block;vertical-align:top;}i.q u{position:absolute;width:0;height:0;overflow:hidden;}.u{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}.bs{margin-top:8px;}.bc{margin-top:12px;}.bd{margin-bottom:4px;}.bi{margin-bottom:16px;}.y .bv{margin-right:4px;margin-top:-2px;vertical-align:middle;}.z{padding:16px;}.be{color:gray;}.bu{font-size:small;}body,tr,input,textarea,.g{font-size:medium;}.bb{font-size:large;}form{margin:0;border:0;}.bh{border-color:#ccced3 #c4c6ca #b4b6ba;border-style:solid;border-width:1px;}.bg{background:#fff;}.bj .bk{color:#1d2129;font-size:small;}.bk{display:block;}.bo{-webkit-appearance:none;background:none;display:inline-block;font-size:12px;height:28px;line-height:28px;margin:0;overflow:visible;padding:0 9px;text-align:center;vertical-align:top;white-space:nowrap;}.c .bo{border-radius:2px;}.br,a.br,html .c a.br{color:#fff;}.c .br{background-color:#4267b2;border:1px solid #365899;}.c a.br:hover,.c .br:hover{background-color:#465e91;}.br[disabled]{color:#899bc1;}.c .br[disabled]:hover{background-color:#4267b2;}.bq{font-size:14px;height:44px;line-height:44px;padding:0 20px;}.c a.bo::after{content:"";display:inline-block;height:100%;vertical-align:middle;}.bo.bp{display:block;width:100%;}a.bo.bp,.c label.bo.bp{display:block;width:auto;}.c .bo{padding:0 8px;}.c a.bo{height:26px;line-height:26px;}.c .bq{padding:0 19px;}.c a.bq{font-size:14px;height:42px;line-height:42px;}.bn{font-weight:normal;}body{text-align:left;direction:ltr;}body,tr,input,textarea,button{font-family:sans-serif;}body,p,figure,h1,h2,h3,h4,h5,h6,ul,ol,li,dl,dd,dt{margin:0;padding:0;}h1,h2,h3,h4,h5,h6{font-size:1em;font-weight:bold;}ul,ol{list-style:none;}article,aside,figcaption,figure,footer,header,nav,section{display:block;}.e #viewport{margin:0 auto;max-width:600px;}.f{background-color:#fff;}#page{position:relative;}/*]]>*/</style></head><body tabindex="0" class="b c d e f"><div class="g"><div id="viewport"><div id="objects_container"><div class="f" id="root" role="main"><div class="h i"><table class="j k" role="presentation"><tbody><tr><td class="l"><a class="m n o" href="/home.php?ref_component=mbasic_home_logo&amp;ref_page=MNuxWizardController"><img src="https://static.xx.fbcdn.net/rsrc.php/v3/yR/r/aOwaKgucSnh.png" width="14" height="14" class="p q" alt="Facebook logo" /></a></td><td class="r"><table class="j k s" role="presentation"><tbody><tr><td class="r"><h3 class="t u"><a class="v w" href="/a/nux/wizard/nav.php?step=phone&amp;skip">Add Mobile Number</a></h3></td></tr></tbody></table></td><td class="l"><a class="v x" href="/a/nux/wizard/nav.php?step=phone&amp;skip">Next</a></td></tr></tbody></table></div><div class="y z"><h3 class="ba"><span class="bb">Help Secure Your Account</span></h3>Add your mobile number to get updates, help with resetting your password and more. Only you will see the number on your profile.<form method="post" action="/phoneacqwrite/"><input type="hidden" name="fb_dtsg" value="AQHBZ3cJweEH:AQHDt92eY7KO" autocomplete="off" /><input type="hidden" name="source" value="m_nux_wizard" /><input type="hidden" name="country" value="BE" /><div class="bc bd"><span class="g be">Belgium (+32)<span role="separator" aria-hidden="true"> \xe2\x80\xa2 </span><a class="bf" href="/phoneacquire/changecountry/?source=m_nux_wizard">Change</a></span></div><div class="bg bh bi"><div class="bj"><label for="u_0_0" class="bk">Type your phone number</label><input autocorrect="off" autocapitalize="off" autocomplete="off" class="bl" name="contact_point" id="u_0_0" style="-wap-input-format: &#039;*N&#039;" type="text" /></div></div><input value="Continue" type="submit" class="bm bn bo bp bq br" /><div class="bs"><span class="bt bu be"><img src="https://static.xx.fbcdn.net/rsrc.php/v3/yA/r/DxvWP_BRGU_.png" width="8" height="11" class="bv q" />Only you will see your number</span></div></form></div><div></div></div></div></div></div></body></html>'`

**Comment by TimLChan** [comment]
The HTML suggests that a mobile number should be added into the account, but I haven't been able to trigger the message myself.

Seems like there is a `nav.php?step=phone&skip` on the page, maybe that will let you skip adding in a mobile number?

**Comment by madsmtm** [comment]
Could you please provide the stack trace, especially including the line saying `Login failed. Check email/password. (Failed on url: URL)`

We need the url it fails on, to be able to make a fix.

**Comment by madsmtm** [comment]
Closing, after (sadly) no response from @DennyWeinberg
