### ISSUE TITLE
Custom colors

### ISSUE THREAD

**Issue by tlaskyd** [carpedm20/fbchat#185]
Hello.
In my messenger I have my own custom colors (such as # 000000), so there is a problem with enumeration. It would be great to make a better way to represent colors than Enum.

**Comment by madsmtm** [comment]
This seems illogical, since Facebook either throws an error, or just ignores the request, if the color was invalid. If you absolutely want to do this, you can overwrite the `ThreadColor` enum like this:
```
import fbchat

class Color(object):
    def __init__(self, color=''):
        self.value = color

fbchat.models.ThreadColor = Color
```
And then you can use it like this:
```
client.changeThreadColor(fbchat.models.ThreadColor('#000000'), '1398901136836712')
```
