### ISSUE TITLE
GraphQL 

### ISSUE THREAD

**Issue by ritu99** [carpedm20/fbchat#186]
Currently getting 500 response on every graphql request.

"Exception: Error when sending request: Got 500 response"

**Comment by madsmtm** [comment]
Hmm, I cannot reproduce this, maybe you could give us some more detailed information

**Comment by ritu99** [comment]
Here's the exact error message:
`Traceback (most recent call last):
  File "onlineanalyzer.py", line 26, in <module>
    print(client.fetchThreadMessages(userchats[0], 20, 1502228399))
  File "/home/ritvik/miniconda3/lib/python3.5/site-packages/fbchat/client.py", line 696, in fetchThreadMessages
    'before': before
  File "/home/ritvik/miniconda3/lib/python3.5/site-packages/fbchat/client.py", line 138, in graphql_request
    return self.graphql_requests(query)[0]
  File "/home/ritvik/miniconda3/lib/python3.5/site-packages/fbchat/client.py", line 128, in graphql_requests
    j = graphql_response_to_json(checkRequest(self._post(ReqUrl.GRAPHQL, payload), do_json_check=False))
  File "/home/ritvik/miniconda3/lib/python3.5/site-packages/fbchat/utils.py", line 157, in checkRequest
    raise Exception('Error when sending request: Got {} response'.format(r.status_code))
Exception: Error when sending request: Got 500 response`

Is there anything else I could provide to help?

**Comment by madsmtm** [comment]
Maybe you could provide the exact code you're using?

**Comment by ritu99** [comment]
`from fbchat import Client
from fbchat.models import *
import logging
import getpass

username = input("Username?")
password = getpass.getpass("Password?")

client = Client(username, password, logging_level=logging.DEBUG)

# print(client.fetchThreadList(offset=0, limit=20))

threads = [];
try:
    index = 0;
    while True:
        threads.extend(client.fetchThreadList(offset=index, limit=20))
        index += 20
except Exception as e:
    print()

groupchats = [i for i in threads if i.type == ThreadType.GROUP]
userchats = [i for i in threads if i.type == ThreadType.USER ]


print(client.fetchThreadMessages(userchats[0], 20, 1502228399))`

**Comment by ritu99** [comment]
I just reinstalled the library and it fixed the issue - not sure of the cause.

**Comment by madsmtm** [comment]
Well, it could be a pip issue, but it could also very well be Facebook, that's causing trouble. Also, the timestamp you're providing to `fetchThreadMessages` is a "Special Timestamp", meaning that it counts in milliseconds, not seconds. So the line should read:
```
print(client.fetchThreadMessages(userchats[0].uid, 20, 1502228399000))
```
... I think...
