### ISSUE TITLE
[Question] Is onChatTimestamp working?

### ISSUE THREAD

**Issue by PythonNut** [carpedm20/fbchat#192]
I've been running fbchat for about a day now, but I haven't seen a single call to `onChatTimestamp`. I this to be expected?

**Comment by madsmtm** [comment]
Related to #49. The implementor of this was @JarbasAI, so perhaps he can give you some help?

**Comment by JarbasAI** [comment]
i've not used this in a while, i will enable them on my setup and let you know, it was working at the time of the PR but facebook may have changed something

**Comment by JarbasAI** [comment]
i forgot to get back to you, i am still receiving those (and often!)

**Comment by PythonNut** [comment]
@JarbasAI I'm not seeing them for some reason, although I have not changed `onChatTimestamp`'s implementation. Do you have any idea why this might be?

**Comment by PythonNut** [comment]
Thanks, I got it working!

(As it turns out, I *did* need to override the implementation in my inheriting class.)
