### ISSUE TITLE
[Feature] Send attachments

### ISSUE THREAD

**Issue by PythonNut** [carpedm20/fbchat#194]
In the messenger webapp, you can send attachments by dragging them into the messenger window, which is super handy as a fast, throwaway file sharing system (w/ zero privacy :P).

It would be really cool if this could be automated in `fbchat`.

**Comment by vn-ki** [comment]
Is this enhancement implemented? I can see code related to implementing this in v1.1.1. Please correct me if I'm wrong.

**Comment by vn-ki** [comment]
@madsmtm

**Comment by madsmtm** [comment]
Not yet, I was working on it. You can receive (most) attachments in `onMessage`, but it's still not possible to send files & such.

**Comment by kapi2289** [comment]
Added in #318!

**Comment by madsmtm** [comment]
Added in release `v1.4.0`. The relevant method is called `sendLocalFiles`
