### ISSUE TITLE
API Documentation Error

### ISSUE THREAD

**Issue by theunicorncow** [carpedm20/fbchat#196]
The call api.getThreadList(start, end, type, callback) claims to return an array with objects which contain field 'name,' which should be: "Name of the thread. Usually the name of the user. In group chats, this will be empty if the name of the group chat is unset." However, unless the thread is a group chat with a user set name, the field 'name' is an empty string, even if the thread is with a single individual.

**Comment by madsmtm** [comment]
I think you're confusing this with [facebook-chat-api's getThreadList](https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getThreadList). `fbchat` doesn't have anything called `getThreadList`, and it definitely doesn't have `callback`s

**Comment by madsmtm** [comment]
Also, see [facebook-chat-api#476](https://github.com/Schmavery/facebook-chat-api/pull/476)
