### ISSUE TITLE
Install Error, no has  "bs4".

### ISSUE THREAD

**Issue by wannaphongcom** [carpedm20/fbchat#2]
I using Python 3.4.3 64 bit for windows 8. I using
pip install fbchat
but install error.
  No distributions at all found for bs4 (from fbchat)

from setup.py in fbchat.
```python
    install_requires=[
        'requests',
        'bs4'
    ],
```

'bs4' to 'beautifulsoup4'
Thank you.

**Comment by bsansouci** [comment]
I second that ;)

**Comment by wannaphongcom** [comment]
Thank you for fbchat. :D
