### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by carpedm20** [carpedm20/fbchat#20]
need documentation

**Comment by danetrain** [comment]
Please? I would love even some preliminary examples.

**Comment by PidgeyL** [comment]
@danetrain Most documentation is in the code itself. Please also have a look there.
A short overview of basic functions would be:

    import fbchat # (obviously, as you need to import the package)
    email=""
    password=""
    browser="" # This is optional
    client = fbchat.Client(email, password, browser)
    users = client.getUsers("with this name")
    user_id_of_partner = users[0].uid
    client.send(user_id_of_partner, "Hi")
    client.listen() # Starts a listener (keep in mind, it's blocking/single threaded)

**Comment by danetrain** [comment]
I've looked over the code. Am I correct in the conclusion that this doesn't yet have the capability to interact with the settings of a chat thread? i.e. boot someone or add someone?

**Comment by PidgeyL** [comment]
not yet, no. We (or at least I) currently focus more on the person-to-person chat, and get all the functionalities for that first

**Comment by massey101** [comment]
If we want to help out with the documentation what is the preferred method for questions? Emai to carpedm20@gmail.com? Thanks.

**Comment by ArsalanBashir** [comment]
@massey101 I guess a pull request would be ideal.

**Comment by carpedm20** [comment]
@massey101 yes, feel free to give a pull request to this repo :+1:

**Comment by OndrejVomacka** [comment]
Please, give me a simple example of a echo bot for educational purposes. I fight with client.listen(). Thx.

**Comment by thekindlyone** [comment]
@OndrejVomacka see my PR, added some documentation.

**Comment by madsmtm** [comment]
I've added `fbchat` to [ReadTheDocs](http://fbchat.readthedocs.io), and included examples and documentation there ;)
