### ISSUE TITLE
2FA broken because of case issues

### ISSUE THREAD

**Issue by ekohilas** [carpedm20/fbchat#205]
[This line](https://github.com/ekohilas/fbchat/blob/master/fbchat/client.py#L253)
Fails on the checkpoint because the facebook has it as "Enter login code to continue" which isn't identical.
Having it as 
```
 ('enter security code to continue' in r.text.lower() or 'enter login code to continue' in r.text.lower())):
```
works however wouldn't it be more efficient to check the page's title instead?
```
('enter security code to continue' in r.title.lower() or 'enter login code to continue' in r.title.lower())):
```

**Comment by ekohilas** [comment]
There also seems to be general issues in 2FA logins, even with this fixed.

**Comment by madsmtm** [comment]
Thank you for pointing this out. As you can probably tell, the 2FA implementation is very hacky, but I don't see another way to do it. Drop us a PR, you'll get credit, and if you have any more suggestions please include them too ;)

**Comment by madsmtm** [comment]
But in reality, it's probably a localization-thing, so maybe there's a better way of determining this?
