### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by sdnian** [carpedm20/fbchat#209]
Something I got an JSONDecodeError message.. It seems that the body contains some special characters will be the case. For example:

Exception in parsing of {'ofd_ts': 1506942246450, 'queue': 100007086494268, 'delta': {'attachments': [], 'irisSeqId': '66093', 'messageMetadata': {'offlineThreadingId': '6320573888207506336', 'actorFbId': '100018997750378', 'messageId': 'mid.$cAAAAA8oJeFZlDgcmF1e3MHanN8ug', 'tags': ['source:chat:orca'], 'timestamp': '1506942246423', 'threadKey': {'otherUserFbId': '100018997750378'}}, 'class': 'NewMessage', 'body': '😆'}, 'type': 'delta', 'iseq': 66093}
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fbchat/client.py", line 1366, in _parseMessage
    thread_id=thread_id, thread_type=thread_type, ts=ts, metadata=metadata, msg=m)

Please take a look how to fix this issue? Thank you.

**Comment by madsmtm** [comment]
Please provide a full traceback and the code you're using. The parts you've provided are good (!), but it's not enough to fully identify the problem ;)

**Comment by sdnian** [comment]
Sorry, it's my fault. I have found the wrong code and it's mime. Thank you.
