### ISSUE TITLE
Share a post?

### ISSUE THREAD

**Issue by cun** [carpedm20/fbchat#224]
Is there any way to share a post into another chat or group?

**Comment by madsmtm** [comment]
Maybe you could elaborate a bit on what you mean by "sharing a post"? What exactly is a "post" in this context? A screenshot might help me understand your intention

**Comment by ekohilas** [comment]
On messenger, you can sometimes select a message to be "shared" or "forwarded" to another group chat.
This used to happen on messenger.com, but it seems it only happens on mobile clients as of late.

**Comment by madsmtm** [comment]
If we're talking about forwarding a message, then wouldn't it be easiest just to take the message you want to forward, and then

**Comment by madsmtm** [comment]
This has been supported for a while with [`Client.forwardAttachment`](https://fbchat.readthedocs.io/en/stable/api.html#fbchat.Client.forwardAttachment), closing.
