### ISSUE TITLE
Logging level is ignored.

### ISSUE THREAD

**Issue by truenicoco** [carpedm20/fbchat#229]
When subclassing `fbchat.Client`, no matter which  `logging_level` is passed, the standard output displays messages at the `DEBUG` level.

**Comment by madsmtm** [comment]
`fbchat`'s logging setup is kind of wierd, and I must admit, I don't fully understand it, but maybe you could try to provide some code that should be working, and isn't?

**Comment by truenicoco** [comment]
Unfortunately right now I've stopped using fbchat and moved to a XMPP prosody/spectrum/libpurple-facebook solution for my needs.

Here's what my code looked like anyway: https://bitbucket.org/nicocool84/fb_bot/raw/447c246b2b991cf99477a06797365a1252c15414/fb_bot.py

**Comment by madsmtm** [comment]
I'm sorry was so late at answering, and that I couldn't help you. This is definitely one of the things getting reworked next in the next major release. Good luck with your project anyways ;)

**Comment by lobstr** [comment]
If you pass it as a numeric value it behaves correctly.  See:
 [https://docs.python.org/3/library/logging.html#logging-levels](Logging Levels)

**Comment by madsmtm** [comment]
I will address this further in an upcoming update, seems like the logging system is directly in-advised: https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library

**Comment by madsmtm** [comment]
Fixed in d3a0ffc47802f6593ff8871795f53cf21bda714e, not yet released
