### ISSUE TITLE
onFriendRequest() not working

### ISSUE THREAD

**Issue by Noxturnix** [carpedm20/fbchat#232]
# -*- coding: UTF-8 -*-
    
    from fbchat import log, Client
    
    class user1script(Client):
        def onFriendRequest(self, from_id, **kwargs):
            print "FReq"
    
    cl = user1script("myEmail@domain.extention","myPassword")
    cl.listen()

But nothing print when someone send me a request. Please help

**Comment by madsmtm** [comment]
Thanks for opening this issue! I looked into it, and i found that it has been disabled for quite a while, apparently by @Dainius14, though this isn't mentioned anywhere.

I will investigate this, and if it's actually broken, attempt to fix the issue

**Comment by DeltaF1** [comment]
I un-commented the code and it seems to work just fine. I can make a PR if you'd like
