### ISSUE TITLE
onTyping

### ISSUE THREAD

**Issue by lobstr** [carpedm20/fbchat#237]
Was there a reason that the onTyping event was commented out at some point?  I thought that it was working correctly before.

**Comment by madsmtm** [comment]
I don't know why it was commented out, the GIT blame tells me that it was @Dainius14, maybe he can give you the answer? But I'll close this, as it's fixed (by you ;) ) in #238

**Comment by Dainius14** [comment]
If I remember correctly it caused some strange python error for me which I could not explain nor fix. Maybe it was just me, I don't know, but if it's working now - great!
