### ISSUE TITLE
markAsRead is not marking thread as read

### ISSUE THREAD

**Issue by actionless** [carpedm20/fbchat#24]
i tried to compare payload with facebook messenger running in a browser and payload seems to be the same except of the missing `__dyn` argument. can it be related?

**Comment by Schmavery** [comment]
In my experience, including `__dyn` makes no difference.

**Comment by bsansouci** [comment]
@actionless if you love reading minified code, feel free to log into FB, download the whole page and all JS and all, grep `__dyn` and figure out how it's generated. From my two past attempts, that baby's hard to figure out (though @Schmavery and I have figured out all of the other "encryption schemes" happening). As @Schmavery said, it doesn't seem to make a difference so far (let's not jinx it)

**Comment by actionless** [comment]
is `markAsRead` works for anyone here?
or it's something in my setup

**Comment by actionless** [comment]
@Schmavery does it works in your js implementation btw?

**Comment by PidgeyL** [comment]
@actionless Did you also run "MarkAsSeen"? I'm not 100% sure on what the difference is, but there is one...

**Comment by actionless** [comment]
just for better understand, the test code:

```python
client = fbchat.Client(FACEBOOK_ID, FACEBOOK_PASSWORD)
unread = client.getUnread()
user_ids = unread['unseen_threads'][0]['other_user_fbids']
if not user_ids:
    print("== No new messages")
    import sys
    sys.exit()

for user_id in user_ids:
    print("{}:".format(user_id))
    messages = client.getThreadInfo(user_id, 0)
    for message in messages:
        if message.is_unread:
            print((message.subject, message.body))
            client.markAsDelivered(user_id, message.message_id)
    client.markAsRead(user_id)
client.markAsSeen()
```

test case to reproduce the issue:
1) send a message to facebook account
2) execute that code snippet, it should print the new message
3) send one more message
4) execute code snippet once again

expected result:
only the latest message was printed to the console

actual result:
both message from pt.1 and 3 are displayed (`message.is_unread` remains `True`)

but after opening in the browser and running code snippet once again those messages are marked as read so not displayed

**Comment by actionless** [comment]
so can anyone confirm the issue?

**Comment by bsansouci** [comment]
@actionless hey, looking at our implementation (from which this is based on), [this](https://github.com/Schmavery/facebook-chat-api/blob/da29b2227a84c8f584bfbd0e049c91bfa8185074/src/markAsRead.js#L13) is what we do. I difference is the form sent to `change_read_status.php` contains a list of `threadID`s instead of `userID`s. Try calling it with a `threadID` and see what happens.

**Comment by actionless** [comment]
unfortunately it's still behave the same

**Comment by horik** [comment]
in order to work markAsRead, please fix 
" data["ids[%s]"%userID] = True " => " data["ids[%s]"%userID] = 'true' "
this value mast be in lowercase.

**Comment by horik** [comment]
@override
class Client(fbchat.Client):
    def markAsRead(self, userID):
        data = {["ids[%s]" % userID]: 'true'}
        r = self._post(fbchat.client.ReadStatusURL, data)
        return r.ok

**Comment by actionless** [comment]
@thnkloud9 if you are still working on the project, see above

**Comment by madsmtm** [comment]
Assuming this has been fixed
