### ISSUE TITLE
fetchThreadList() is not working.

### ISSUE THREAD

**Issue by SangDdung** [carpedm20/fbchat#241]
```
#-*- coding: utf-8 -*-
import fbchat

client = fbchat.Client("****", "****")
MsgThreaList = client.fetchThreadList()

print MsgThreadList
```

in this, returned text is
>[]

7 days ago, I used this code very well.
but now, this function seem to be broken.

I attempted to use other account. but, same issue.

isn't need to fix some code or function is really broken?

**Comment by madsmtm** [comment]
I can confirm this, Facebook seems to have changed something. I'll investigate this further, and perhaps come up with a solution.

**Comment by blueset** [comment]
Facebook migrated thread list to GraphQL.

I've found the the fetchThreadList equivalent for GraphQL, just note it down here if you may find it useful.

```
"batch_name": "MessengerGraphQLThreadlistFetcherRe"
```

```
"queries": {
    "o0":{
        "doc_id":"1349387578499440",
        "query_params":{
            "limit":12, // Length 
            "before": <millisecond_UNIX_timestamp_int>, // show threads that was active before this time
            "tags":["INBOX"], // source ['INBOX', 'PENDING', 'OTHER' /* filtered pending */, 'unread', 'ARCHIVED']
            "includeDeliveryReceipts":true,
            "includeSeqID":false
        }
    }
}
```

**Comment by dstelzer** [comment]
Just ran into this same issue. Has anyone documented the format that Facebook now returns the data in?

**Comment by madsmtm** [comment]
Not yet, I've planned doing it at some point, but if anyone else is willing to do it, please be my guest!

**Comment by liamrathke** [comment]
https://github.com/Schmavery/facebook-chat-api/pull/572

This is the same discussion in the Node equivalent, hopefully they'll find a fix soon.
