### ISSUE TITLE
how to store/write the text messages using client.listen()

### ISSUE THREAD

**Issue by sumit6192** [carpedm20/fbchat#244]
i find this python package awesome but have some doubts:

from fbchat import Client
from fbchat.models import *
client = Client('email', 'passw')
client.listen() gives me all the incoming messages but how do i store or write them in a file so that i can respond them later using 
client.send(Message(text='message'), thread_id=id, thread_type=ThreadType.USER/GROUP)

**Comment by madsmtm** [comment]
[RTFD](http://fbchat.readthedocs.io/en/master/examples.html#echobot)

Subclass the `Client`, and use `onMessage` to save the information you need to a file.

**Comment by sumit6192** [comment]
sorry to bother you again i am a newbee in python could you just give an example how to
i tried:
with open("C:/Users/sumit.k.das/Desktop/output.txt", "wb") as text_file:
    text_file.write(client.listen())

but nothing happened

**Comment by madsmtm** [comment]
You could do something like this, then:
```
with open(file) as text_file:
    class CustomClient(Client):
        def onMessage(self, message_object=None, **kwargs):
            text_file.write(message_object.text)

    client = CustomClient(email, password)
    client.listen()
```
Though there are many other approaches to this, and the described method isn't the best.

**Comment by sumit6192** [comment]
Tried this one but no able to write the incoming messages.are you sure we can write the incoming messages using client.listen() to a file..

**Comment by sumit6192** [comment]
i get output -
Logging in sumit280@gmail.com...
Login of sumit280@gmail.com successful.
Listening...
Inbox event: 1, 3, 3

but nothing gets written on my text file.. tried different options also but not able to write incoming messages using client.listen()

**Comment by madsmtm** [comment]
`Client.listen` won't have a return value, so you can't do something like `print(client.listen())`. This function calls different methods when the client e.g. when it recieves a message, or when someone kicks a person from a group chat. So if you overwrite it like I showed you, you should be able to do what you want with the `message_object` parameter, and write the `.text` part of the message to a file. Though you should probably open the file with `append`, so that you can actually write to the file, like this:
```
with open(file, 'a') as text_file:
    pass # Do stuff here
```

**Comment by madsmtm** [comment]
But it's beyond me to properly explain how subclassing and method overwriting works, try find a tutorial on this first.

**Comment by sumit6192** [comment]
i triend to write in append mode too but not able to write the incoming messages-

with open('file path','a') as text_file:
    class CustomClient(Client):
        def onMessage(self, message_object=None, **kwargs):
            text_file.write(message_object.text)

    client = CustomClient(email, password)
    client.listen()

it is just returning
 Listening...
Inbox event: 1, 3, 3

i just need to write the incoming messages to a file using the client.listen(). if you could just guide me through that it ould be awesum

**Comment by sumit6192** [comment]
or if you could just tell me how can i get the incoming Thread_id (user_id) of the incoming messages.

**Comment by sumit6192** [comment]
or if you could just tell me how can i get the incoming Thread_id (user_id) of the incoming messages of any user in my contact.. in a generic way

**Comment by sumit6192** [comment]
Got it now its working ..Thanks a lot Bro you are a saviour
