### ISSUE TITLE
Get Users' ID in a group chat

### ISSUE THREAD

**Issue by acquykhud** [carpedm20/fbchat#247]
Hi.
Is there a possible way to get all the participants' ID to a list ? Thank you

**Comment by madsmtm** [comment]
You can use [`fetchGroupInfo`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.fetchGroupInfo), and retrieve a [`Group`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.models.Group) instance from that, from which you grab the `participants`, which contains a list of [`User`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.models.User) instances.
In code:
```
def getParticipants(client, group_id):
    return list(client.fetchGroupInfo(group_id)[group_id].participants)
```
If this doesn't work, or you have any other questions, feel free to reopen this issue ;)
