### ISSUE TITLE
onMessage is obsolute.

### ISSUE THREAD

**Issue by SMdeepak** [carpedm20/fbchat#248]
your example program https://github.com/carpedm20/fbchat/blob/master/examples/echobot.py was working fine a few days ago, and now it tells "listing..." and doesn't listen to the incoming messages.

**Comment by madsmtm** [comment]
Hmm, I can't seem to reproduce this, perhaps you could provide som debug output? To do this, initialise the client with "logging_level=0", try sending yourself a message, and let me see the terminal output?

Of course, be weary that this might disclose some variables that can be used to impersonate you on Facebook, so make sure you filter those out or use a test account.

**Comment by madsmtm** [comment]
Closing, after no response from submitter
