### ISSUE TITLE
Login with access_token?

### ISSUE THREAD

**Issue by fcaza** [carpedm20/fbchat#249]
So far, it looks like we have to login with login/pwd

Do you plan to integrate access_token mechanism for login ?

**Comment by lobstr** [comment]
If you're just looking to avoid doing a full login with email/password, you can use `getSession()` to get your session cookies and save them to use later.  [See here](https://github.com/carpedm20/fbchat/blob/master/docs/intro.rst#sessions).

**Comment by fcaza** [comment]
Thanks for the answer.
Another question, do you know if some people tried to fork your project for java?

**Comment by madsmtm** [comment]
Don't think this has been done in java, I only know about [this](https://github.com/Schmavery/facebook-chat-api) (which is for javascript)

**Comment by tdelam** [comment]
I wonder the same, why user/pass? Why not token?
