### ISSUE TITLE
[Feature request] Last active (User model)

### ISSUE THREAD

**Issue by Dante383** [carpedm20/fbchat#251]
An ability to fetch when the user was last active.

**Comment by lobstr** [comment]
Check out `onChatTimestamp()` (you have to have your chat turned on for it to show up I believe).  It gives an updated list every few minutes of all your friends by FBID and a timestamp of their last activity.

**Comment by Dante383** [comment]
@lobstr How could I not notice it! Thanks

**Comment by pielco11** [comment]
I don't understand how to use this feature.
Can you give a short example, please?
Thanks!

**Comment by madsmtm** [comment]
Something like:
```
import fbchat

class CustomClient(fbchat.Client):
    def onChatTimestamp(self, buddylist, **kwargs):
        print(buddylist) # Contains ids of Facebook users, along with a timestamp

client = CustomClient("<email>", "<password>")
client.listen()
```
See the [docs](https://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.onChatTimestamp) for more info. If you have a specific problem, don't hesitate making a new issue ;)
