### ISSUE TITLE
AttributeError: 'Client' object has no attribute 'getUsers'

### ISSUE THREAD

**Issue by shashwat1002** [carpedm20/fbchat#252]
I'm just beginning with fbchat, I keet facing this error. 

```python
import fbchat
from getpass import getpass

username=str(raw_input("Username: "))
client = fbchat.Client(username, getpass())

no_of_friends = int(raw_input("Number of friends: "))

for i in xrange(no_of_friends):
    name=str(raw_input("Name: "))
    print client.getUsers(name)
```
This is my code.

**Comment by madsmtm** [comment]
There is no `getUsers` method, you should use something like [`searchForUsers`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.searchForUsers). Also, you forgot to actually include the error you were getting ;)

**Comment by madsmtm** [comment]
Assuming this fixed it for you. This confusion must have been caused by a breaking change somewhere, but it's too long ago for me to remember, sorry about the trouble ;)
