### ISSUE TITLE
how to get unread threads and mark messages as read

### ISSUE THREAD

**Issue by noobd3veveloper** [carpedm20/fbchat#261]
hi, i just want to know how to mark messages as read. i tried the markAsRead and markAsSeen but when i check on the facebook messenger it is still flagged and unread/unseen. thanks.

and how to get unread threads.

thanks

**Comment by madsmtm** [comment]
Related to #171. Just like `markAsSeen` is broken, so is `markAsRead`, sadly. I'm not sure how exactly to fix this yet, but if someone can come up with a fix, please do make a PR!

**Comment by madsmtm** [comment]
Oh, and about the unread threads, I don't think `fbchat` has that functionality yet, though it's probably possible somehow.

**Comment by MS-Jahan** [comment]
Any function to check unread messages from recent threads? Or just any method?

**Comment by madsmtm** [comment]
Not directly, no. You'd have to combine `Client.fetchUnread` and `Client.fetchThreadMessages`
