### ISSUE TITLE
Cannot Log In

### ISSUE THREAD

**Issue by tzima** [carpedm20/fbchat#268]
Hi.
I don't seem to be able to log in. I tried it repeatedly with two different accounts without any difference.
I used the following code:

```python
#!/usr/bin/env python3
import fbchat
import logging

client = fbchat.Client("<omitted>", "<omitted>", logging_level = logging.DEBUG)
help(client)
```
It yielded the following output:

```
Logging in <omitted>...
Attempt #1 failed, retrying
Attempt #2 failed, retrying
Attempt #3 failed, retrying
Attempt #4 failed, retrying
Attempt #5 failed
Traceback (most recent call last):
  File "./test.py", line 5, in <module>
    client = fbchat.Client("<omitted>", "<omitted>", logging_level = logging.DEBUG)
  File "/usr/local/lib/python3.6/dist-packages/fbchat/client.py", line 73, in __init__
    self.login(email, password, max_tries)
  File "/usr/local/lib/python3.6/dist-packages/fbchat/client.py", line 391, in login
    raise FBchatUserError('Login failed. Check email/password. (Failed on url: {})'.format(login_url))
fbchat.models.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login.php?login_attempt=1)
```
Any ideas?

Thanks.

**Comment by tzima** [comment]
Nah, that's just Murphy's law. I tried several times within a period of time (and with pauses in between, to prevent a ban due to suspicious activity) and it always failed. A short moment after posting this issue, I tried again and it finally worked.

It was probably some problem at Facebook. Issue maybe closed now. Sorry for this.

**Comment by madsmtm** [comment]
I'll close it, since there's already a bunch of issues on logging in already ;)
