### ISSUE TITLE
Getting all user IDs from all threads and groups

### ISSUE THREAD

**Issue by Sharpz7** [carpedm20/fbchat#274]
Hi, I am currently building a bot on top of Fbchat, and need a list of all the User Id's i am talking to. (http://www.hatebin.com/kcfwntgliy).

My problem is that i can't figure out how to get the ID's of users from inside a messenger group with multiple people, as you can only get the thread ID of the whole group.

Does anyone know a way to get ALL the user ID's of ALL the groups in Fbchat?

**Comment by madsmtm** [comment]
Unless you're talking about Facebook "rooms", then no, a group on https://www.facebook.com/messages/t/XXX or https://www.messenger.com/t/XXX is what `Group` is supposed to represent

Sample code, where we fetch the Group every time someone asks for the participants
```py
import fbchat
from fbchat.models import *

class Bot(fbchat.Client):
    def onMessage(self, message_object=None, thread_id=None, thread_type=None, **kwargs):
        if message_object.text == '/get_participants' and thread_type == ThreadType.GROUP:
            # group is a `Group` instance, containing a bunch of useful information about the group
            group = self.fetchGroupInfo(thread_id)[thread_id]
            self.send(Message(text=repr(group.participants)), thread_id=thread_id, thread_type=thread_type)

bot = Bot(...)
bot.listen()
```

**Comment by Sharpz7** [comment]
```    self.message(str(repr(group.participants)))
AttributeError: 'dict' object has no attribute 'participants'
Inbox event: 2, 2, 2
```

This is the error i was getting.. i don't know why

**Comment by Sharpz7** [comment]
Is the output of this a set? How do i append to it? Can i convert it to a list?
