### ISSUE TITLE
Getting a threadid from a username

### ISSUE THREAD

**Issue by Sharpz7** [carpedm20/fbchat#275]
This doesn't sound impossible.... but probably is.

Can i call a users thread from their username?

**Comment by madsmtm** [comment]
Well, your best bet would be the `searchForX` methods, in particular [`searchForUsers`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.searchForUsers), though I can't guarantee it'll always work, you never know with Facebook ;)
