### ISSUE TITLE
Using def_onmessage() in different place in script

### ISSUE THREAD

**Issue by Sharpz7** [carpedm20/fbchat#276]
http://www.hatebin.com/ztnqckygsq

I am creating a New class, Blackjack, and want to make it so multiple people can use it at once.
Therefore, i need to tell when the next command after !t and !s is, and only when !bjack is on.

So how can i wait for onMessage from somewhere else is the script?

(B.t.w if you guys know if making it work for different people is going to be possible or not, let me know)

**Comment by DeltaF1** [comment]
I recommend checking out the excellent documentation at https://fbchat.readthedocs.io/en/master/api.html. The function you're looking for is probably [Client.doOneListen](https://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.doOneListen).

(P.S. I noticed you've been opening a lot of issues asking about how to use the API, I strongly recommend you take a look at the rest of the documentation at that link, it's laid out very nicely, and there are example scripts that show you how to use some of the Client functionality.)

**Comment by Sharpz7** [comment]
I have read through the whole thing multiple times.... Doesn't make much
sense to me xd
