### ISSUE TITLE
Message timestamps seem to be invalid.

### ISSUE THREAD

**Issue by tcmal** [carpedm20/fbchat#277]
Getting the last time stamp of a group (or of a message) gives a string of an abnormally high integer value:

```
>> thread = client.fetchThreadList()[0]
>> ts = int(thread.last_message_timestamp)
>> ts
1522504826129
>> datetime.fromtimestamp(ts)
ValueError: year 50216 is out of range
```

**Comment by madsmtm** [comment]
Yeah, thats because it's in milliseconds ;)

We should probably have converted it to seconds before eksposing it to the API... ;)

**Comment by tcmal** [comment]
Ok, Should I make a PR to convert it to a datetime object?

**Comment by 2FWAH** [comment]
Take care that changing the unit breaks API compatibility.
Having the date in ms could be useful to use as a (reasonably) primary key.
One easy thing could be to specify the unit in the doc (https://fbchat.readthedocs.io/en/master/api.html#fbchat.models.Thread) to remove ambiguity.

**Comment by tcmal** [comment]
I don't think there's much use in using the timestamp as a primary key as each message already has its own ID anyway.
