### ISSUE TITLE
thread_id

### ISSUE THREAD

**Issue by azziplekkus** [carpedm20/fbchat#28]
Is there any possibility to get the thread_id out of the JSON?
Would be useful for writing a bot that can interact with multiple users in a single group conversation.

**Comment by PidgeyL** [comment]
Could you describe that a bit better? Out of what JSON? If you have a thread object, you can get the ID from there. Which function are you talking about?

**Comment by azziplekkus** [comment]
In _parseMessage(self, content) it's extracting data out of JSON (sender id, message data, ...). I wasn't able to extract the thread_id however, to reply in group conversations.

**Comment by PidgeyL** [comment]
You are not supposed to call _parseMessage() yourself... That's why it has _ in front. All _functions() are functions of the class, not functions for the user.

**Comment by azziplekkus** [comment]
Then how do I use this library? I see no other way than makeing a child class and overriding the parent function in order to achieve something other than printing the message and the JSON.

**Comment by PidgeyL** [comment]
I'm really not sure what you want to do though.
getThreadList(offset, amount) returns a list of threads (thread id included)
getThreadInfo(userID, offset, amount) returns a list of messages from a user (thread id included)
send(thread_id, message) requires the thread id, so you got it
getUnread() also gives a list of threads (thread id included)

Group conversations are not supported yet.

**Comment by azziplekkus** [comment]
What I'm doing now in my code works: I receive a message from someone, and I answer to it straight away by rewriting _parseMessage(). Didn't see any other way to do it.

Group conversations are not supported yet, I know that. I read it here a few times, but that's what I'm trying to implement. Is there anyway to retrieve the group-conversation's thread_id from the JSON? 
I tried several of the JSON field marked with "thread_id" but they didn't work. I must be doing something wrong...

**Comment by PidgeyL** [comment]
I would recommend to have a look at [this project ](https://github.com/Schmavery/facebook-chat-api)to see how they implemented group support (in JavaScript)

**Comment by azziplekkus** [comment]
Thank you! I will have a look at that! :)

But purely out of interest: You said I was not supposed to call _parseMessage(myself), but then how am I supposed to use this lib?

**Comment by PidgeyL** [comment]
if you want to listen for incoming messages, make a class extending fbchat, and overwrite the on_ functions. You can use send() to send messages, and the others to acquire information from users and messages. Threads have a lot of values, so you can extract information from them that way.

If you want more information, tell me what you'd like to do. It's a bit strange telling you how to use the lib, if I don't know how you want to use it :)

**Comment by azziplekkus** [comment]
I overwrote the on_message() function, but also the _parseMessage() function, because it doesn't pass all the arguments (I think) I need.
I'm trying to make a Trivia-bot (like the ones that existed on IRC back in the days). In order to achieve that I need to be able to send and receive messages in a group-conversation.

**Comment by PidgeyL** [comment]
I see. It's possible you'll need to re-write some parts of _parseMessage(). There are other projects you can have a look at. I listed them [here](https://github.com/PidgeyL/fbchat/issues/1)

**Comment by azziplekkus** [comment]
Thanks a lot! I'll check those out as well ;)

**Comment by madsmtm** [comment]
#102 might have made this possible

**Comment by madsmtm** [comment]
Facebook has changed a lot of things, and `fbchat` has been updated, so I'm assuming this is outdated ;)
