### ISSUE TITLE
how can i get the mention information

### ISSUE THREAD

**Issue by Zero2627** [carpedm20/fbchat#280]
I know it sounds clumsy......
But I really don't know how to get the id who was mentioned

**Comment by madsmtm** [comment]
Use `thread_id` ;)

```py
# Get a `Message` object, however you want to
m = client.getThreadMessages(thread_id)[0]

# List of `Mention` objects
print(m.mentions)

# First `Mention` object
print(m.mentions[0])

# Thread ID of person in first `Mention` object
print(m.mentions[0].thread_id)
```

See [`Mention`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.models.Mention) and perhaps [`Message`](http://fbchat.readthedocs.io/en/master/api.html#fbchat.models.Message)

**Comment by madsmtm** [comment]
Assuming this fixed it for you, feel free to reopen 😊
