### ISSUE TITLE
No method for fetching videos

### ISSUE THREAD

**Issue by speedstyle** [carpedm20/fbchat#281]
There doesn't currently seem to be a method for fetching full-quality videos by URL, only preview images and a compressed preview URL.

Additionally, this isn't strictly related, but perhaps more attachment details - such as the URL and filesize - could be integrated into the `Attachment` class rather than implemented individually by subclasses (the `ShareAttachment` class could - when completed - have a `size` of `None`). Of course I understand if it has been done this way to better reflect the underlying API, but I believe it would make more sense this way.

**Comment by madsmtm** [comment]
Thanks for the suggestion, I'll make sure to take it into consideration ;)

**Comment by madsmtm** [comment]
[`Client.fetchImageUrl`](https://fbchat.readthedocs.io/en/stable/api.html#fbchat.Client.fetchImageUrl) apparently works with videos as well, so that is the suggested fix.
