### ISSUE TITLE
No good documentation

### ISSUE THREAD

**Issue by pingpong1109** [carpedm20/fbchat#29]
I am unable to use this as there is no documentation and the issue talking about it being in the code is just as unhelpful.

**Comment by nicolas-martin** [comment]
The code itself is pretty self explanatory. Just have a look at [send](https://github.com/carpedm20/fbchat/blob/master/fbchat/client.py#L197), [getThreadInfo](https://github.com/carpedm20/fbchat/blob/master/fbchat/client.py#L243), getUnread and listen.

Don't be lazy.

**Comment by pingpong1109** [comment]
When I run listen() it just stays there, it prints the data to the screen but doesn't actually advance my code to do anything with said data.

**Comment by PidgeyL** [comment]
It doesn't seem to me you have any experience in coding (python, at least). Study up a bit on classes and overriding them

**Comment by pingpong1109** [comment]
Yes I do. I have several years, you just have no documentation.
