### ISSUE TITLE
How can I setup session cookies?

### ISSUE THREAD

**Issue by ThatAlexanderA** [carpedm20/fbchat#292]
I don't really know where to put the "session_cookies = client.getSession()" command. 
I put it under the client = HDD("emailadress", "password") but it didn't saved any file. 
Can someone help me?

**Comment by madsmtm** [comment]
It won't save & load the session cookies to a file, you'll have to do that yourself. A sample implementation could be:
```py
import json
import fbchat

cookies = {}
try:
    # Load the session cookies
    with open('session.json', 'r') as f:
        cookies = json.load(f)
except:
    # If it fails, never mind, we'll just login again
    pass

# Attempt a login with the session, and if it fails, just use the email & password
client = fbchat.Client('email', 'password', session_cookies=cookies)

# ... Do stuff with the client here

# Save the session again
with open('session.json', 'w') as f:
    json.dump(client.getSession(), f)
```

**Comment by ThatAlexanderA** [comment]
Thank You so much! It works very well! 😃

**Comment by anh-dz** [comment]
Hey, can anyone tell me how to get fb cookie, please?
Thank you very much!

**Comment by alexdupat** [comment]
Hey, the same question ! What is the fb cookie we need, and where find it

**Comment by ravitaak** [comment]
> Hey, can anyone tell me how to get fb cookie, please? Thank you very much!
Need to download a Extension of Chrome
