### ISSUE TITLE
Method to remove friends?

### ISSUE THREAD

**Issue by DeltaF1** [carpedm20/fbchat#294]
I can't find anything in the documentation about removing friends. Does anyone know what the ajax url is, or is this something that is yet to be investigated?

**Comment by madsmtm** [comment]
Removing and adding friends, and receiving frend requests is not yet part of the API, feel free to investigate ;)

**Comment by ThatAlexanderA** [comment]
I searched a little bit and I found that https://m.facebook.com/removefriend.php?friend_id=user_id this url is to remove friend. But you need to click the confirm button to remove the friend. The button name is submit. I don't know how to send a requests that simulates the button press.

**Comment by ThatAlexanderA** [comment]
I added the new url to the utils.py
a264fac
Then added your code to the client.py
c842be3
And run the code, it run successfully with no errors. But the friend isn't removed. 

With Firefox dev tools and track down what Post request need to send. And If I'm right we need to send
headers too with the following information:
Content-Type: application/x-www-form-urlencoded
Cookie: c_user=c_user; xs=xs
With the self._session.cookies.get_dict().get('') command we can get them.
`                {
                "name": "Content-Type",
                "value": "application/x-www-form-urlencoded"
                },
                {
                "name": "Cookie",
                "value": ""
                },
                {
                "name": "c_user",
                "value": self._session.cookies.get_dict().get('c_user')
                },
                {
                "name": "xs",
                "value": self._session.cookies.get_dict().get('xs')
                }`
Should I add this code to the request too? And If so where?

**Comment by madsmtm** [comment]
I think `fb_dtsg` is already available from login via. the `Client.fb_dtsg` value, and when using `Client._post`, the cookies are automatically applied to the request, along with a proper `Content-Type`. Maybe there's something else at play?

**Comment by DeltaF1** [comment]
Is it possible that both the initial GET request you found _and_ the
confirmation request I found need to be sent? Alternatively, maybe the
request I found is wrong.

**Comment by ThatAlexanderA** [comment]
I think your url is good. This is the request that is sent: (there are more lines, but if I remove them it still works)
(https://imgur.com/PThXsNZ)
I try without my url and use `Client.fb_dtsg` as the fb_dtsg value, maybe that will work.

**Comment by madsmtm** [comment]
Actually, looking at it even more closely and slowly remembering how the internals work, the `fb_dtsg` is automatically included in the `_post` request via. `_generatePayload`. Maybe try using an intercepting proxy, and analyse the requests that `fbchat` sends compared to the browser from there? Or maybe try going around `Client._post`, and send a few requests with the `requests` library directly, to narrow down what the problem might be

**Comment by madsmtm** [comment]
Also, I think that using `{'name': x, 'value': y}` is wrong, with `requests` it should just be `x: y`. So the payload could just be:
```
payload = {
    "friend_id": friend_id,
    "unref": "none",
    "confirm": "Confirm",
}
```

**Comment by ThatAlexanderA** [comment]
Thank You so much! 
Now it is working!!
I update the code soon.

**Comment by ThatAlexanderA** [comment]
#298 
I added it to the pull requests.

**Comment by madsmtm** [comment]
Added `Client.removeFriend` in `v1.3.9` via. #298
