### ISSUE TITLE
cannot import name Client

### ISSUE THREAD

**Issue by IvanHrytskiv** [carpedm20/fbchat#297]
from fbchat import Client
ImportError: cannot import name Client

**Comment by madsmtm** [comment]
This looks like an installation error, could you provide some information on how you've installed `fbchat`? Are you using the same pip version as your python version?

**Comment by IvanHrytskiv** [comment]
using the same pip version as your python version? = YES

same pip version and not same = The result is one and the same always

I tried to install it in different ways:

1. clone repo
2. pip install fbchat (for python ver. 2.7 and 3.6)
3. pipenv install fbchat (for python ver. 2.7 and 3.6)
4. using different virtual env. and not using
5. Ubuntu 17.10, Ubuntu 18.04
6. Windows 7, Windows 10 (all ver python)

The result is one and the same always.

Thanks.

**Comment by madsmtm** [comment]
Hmm, that sounds very odd, do you know if this just started happening in this version, or has it been happening in previous versions?

And can you try running `python -c 'import fbchat; print(fbchat); print(fbchat.Client)'` in your terminal, just to confirm the problem?

The wierd part is that if the installation has failed, `from fbchat import Client` should throw an `ImportError: No module named 'fbchat'`, not `ImportError: cannot import name Client`

**Comment by IvanHrytskiv** [comment]
I do not know if it was in previous versions.

python -c 'import fbchat; print(fbchat); print(fbchat.Client)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fbchat

**Comment by madsmtm** [comment]
Okay, that makes a little bit more sense, python can't find the module, try making sure it's installed with `python -m pip install --upgrade fbchat`. Or maybe something in your `PATH` or `sys.path` is broken?

**Comment by IvanHrytskiv** [comment]
launchpadlib 1.10.5 requires testresources, which is not installed.

**Comment by IvanHrytskiv** [comment]
pip check
launchpadlib 1.10.5 requires testresources, which is not installed.
sudo apt install python3-testresources
pip check
No broken requirements found.
pip list | grep launchpadlib
launchpadlib                  1.10.5 

>>> import fbchat
>>> print(fbchat)
<module 'fbchat' from '/usr/local/lib/python3.6/dist-packages/fbchat/__init__.py'>
>>> 

python -c 'import fbchat; print(fbchat); print(fbchat.Client)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named fbchat
))))))

python3.6 -c 'import fbchat; print(fbchat); print(fbchat.Client)'
<module 'fbchat' from '/usr/local/lib/python3.6/dist-packages/fbchat/__init__.py'>
<class 'fbchat.client.Client'>

**Comment by IvanHrytskiv** [comment]
Thanks ! )))

**Comment by madsmtm** [comment]
Glad you got it to work ;)
