### ISSUE TITLE
Listen for a message

### ISSUE THREAD

**Issue by pingpong1109** [carpedm20/fbchat#30]
How would I listen for a message?

**Comment by PidgeyL** [comment]
client.listen() ...

**Comment by pingpong1109** [comment]
That prints out the message and a ton of data but even if I do message = fb.listen() it just prints out the data to the screen and never goes past that line.

**Comment by PidgeyL** [comment]
Either you overwrite on_message, or you use getThreadList... It's all pretty clear from the code
