### ISSUE TITLE
AudioAttachment

### ISSUE THREAD

**Issue by rkuo2000** [carpedm20/fbchat#308]
How to send an audio attachment ?

client.send(Message(text='send an audio', attachments=AudioAttachment('bonjour.mp3'), thread_id=thread_id, thread_type=thread_type)

**Comment by madsmtm** [comment]
Related to, if not a duplicate of, #194. To answer your question, then this is not yet implemeted ;)

**Comment by kapi2289** [comment]
Added in #318!

**Comment by madsmtm** [comment]
Fixed in release `v1.4.0`. The relevant method is called `sendLocalFiles`
