### ISSUE TITLE
Java wrapper

### ISSUE THREAD

**Issue by 7osCraft** [carpedm20/fbchat#309]
Hello,
 I'm not so familiar with python, so I was wondering if there's any java wrapper for this library or any way to integrate this with java.

**Comment by madsmtm** [comment]
There's no wrapper that I know of, but there might be other similar APIs, just like this project is inspired by the node.js API

**Comment by madsmtm** [comment]
Closing, the above comment answered the question as best as possible. Feel free to reopen, or comment if anyone has any further info.
