### ISSUE TITLE
sending .avi on chat ?

### ISSUE THREAD

**Issue by toumtoum52** [carpedm20/fbchat#321]
Hello! I use fbchat for a bot on FB for a video surveillance. When an action on the camera was detect, today, i can send .jpg on facebook. Is it possible in the future that we can send little video in format .avi ?

**Comment by kapi2289** [comment]
I made it in #318 ;)

**Comment by kapi2289** [comment]
Because my changes are not merged yet, you can copy code from my pull request to your library and it'll work :grinning:

**Comment by toumtoum52** [comment]
It works for me ! Very good job man!
thanks a lot !

**Comment by madsmtm** [comment]
Fixed by #318, in release `v1.4.0`. The method is now called `sendLocalFiles`
