### ISSUE TITLE
`onMessge` being called repeatedly after a single message

### ISSUE THREAD

**Issue by grenmester** [carpedm20/fbchat#322]
## Description of the problem
The `onMessage` function seems to be getting called repeatedly instead of just once when a message is sent in Messenger. I'm not sure if this is a bug or if I'm misunderstanding how `onMessage` works since the EchoBot example works as expected for me.

## Code to reproduce
```py
import login
from fbchat import log, Client
from fbchat.models import *

class CBot(Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        debug = Message(text="valid input")
        self.send(debug, thread_id=thread_id, thread_type=thread_type)

client = CBot(login.email, login.password)
client.listen()
```

Note: the login module just contains my email and password.

## Environment information
- Python version 2.7.15
- `fbchat` version 1.3.9

**Comment by Schmavery** [comment]
Any change it's related to https://github.com/carpedm20/fbchat/issues/319?

**Comment by grenmester** [comment]
Yes, that is probably it. Thank you!
