### ISSUE TITLE
Unable to import Client.

### ISSUE THREAD

**Issue by vighneshck** [carpedm20/fbchat#329]
Hi,

This is my first time working with the fbchat library, and I keep getting the following error, although I have installed the library using pip3 install -U fbchat. 

Following are the details of the error:

## Description of the problem
Running 'from fbchat import Client' gives the following error:
ImportError: cannot import name 'Client'

## Code to reproduce
```py
# Example code
from fbchat import Client
from fbchat.models import *
```

## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fbchat.py", line 1, in <module>
    from fbchat import Client
ImportError: cannot import name Client
```

## Environment information
- Python version: 3.6.4
- `fbchat` version: 1.4.0

**Comment by madsmtm** [comment]
It seems like you've named your file `fbchat.py`, which means that the code tries to import `Client` from itself. Try renaming it 😁

**Comment by vighneshck** [comment]
Oh my... that was indeed my fault. 

Thanks a lot!
