### ISSUE TITLE
send message  to group chat

### ISSUE THREAD

**Issue by blcc** [carpedm20/fbchat#33]
Hi,
I found when sending message to a group chat, the following line should not be exist:
            'message_batch[0][specific_to_list][0]' : 'fbid:' + str(thread_id),
            'message_batch[0][specific_to_list][1]' : 'fbid:' + str(self.uid),
Those lines are client.py line 211 and 212.

However, I do not know how to determine group or personal chat via thread_id only.
Maybe additional argument is required in send().

**Comment by Schmavery** [comment]
In our nodejs api, we make a call to the '/chat/user_info/' endpoint with the thread_id to determine whether the chat is a group or a personal one.  Not sure if that helps you.

**Comment by blcc** [comment]
FB keeps changing chat protocol. Old post may not help.
Maybe we need a tool to get the form we need to send.
