### ISSUE TITLE
Can't stop or cancel a listen() loop externally. client.listening=False seems to not work

### ISSUE THREAD

**Issue by juju4Life** [carpedm20/fbchat#331]
I need to have a continuous listen() loop running at all times. I have a sub class of the Client named `ListenBot` which uses the `onMessage` function call. I use the bot to query a database, based on read messages. The database I'm using times out after 90 seconds (which cannot be changed). After those 90 seconds, it drops connection with the `onMessage()` event. Before this happen, maybe 80 seconds after the  `listen()` loop has been running, I want to stop / restart, or stop/start a new connection immediately but there doesn't seem to be a way to do this. I have the following code:
```
@shared_task()
def awake():
    client = ListenBot(Secrets.facebook_email, Secrets.facebook_password)
    if not client.isLoggedIn():
        client = ListenBot(Secrets.facebook_email, Secrets.facebook_password)
    client.stopListening()  
    client.listen()
```

I would expect this code to stop the listening event of the current logged in client, and then start it again. This way I could start it every 80 seconds before the connection is dropped `stopListening()` id nothing, and the same listening event continued to run. I also tried to create a while loop using `doOneLoop()`. I expected the following block of code to run as if I call `listen()`:
```
while True:
    client.doOneListen()
```

But again, this had no effect. It appears not to see the messages at all. Also, If I call `listen()` every bit of code afterwards is never reached, so I can't seem to use any conditional code to restart/stop. I must clearly be using `client.stopListeing` and `client.doOneListen` incorrectly. What is the best way to stop and restart the `listen()` loop?

**Comment by madsmtm** [comment]
`Client.startListening` and `Client.stopListening` are used to set up variables used while listening, not to start and stop the client listening from a seperate thread, or at specific times. Have a look at the `listen` implementation:
```py
def listen(self, markAlive=True):
    self.startListening()
    self.onListening()
    while self.listening and self.doOneListen(markAlive):
        pass
    self.stopListening()
```

I'm not really sure how your setup is, it's quite difficult to follow your explanation, but it should be possible for you set `Client.listening = False` when you need to stop the client? Then maybe something like this could work (assuming it would be okay to restart the connection once it actually drops) (and I don't know what `shared_task` is):
```py
from fbchat import Client
class ListenBot(Client):
    def onMessage(self, message=None, **kwargs):
        if message == "Connection dropped":  # Or however the connection is dropped
            self.listening = False
            return
        # Do other stuff here

@shared_task()
def awake():
    client = ListenBot(Secrets.facebook_email, Secrets.facebook_password)
    client.listen()
```

**Comment by juju4Life** [comment]
Sorry to be unclear. I'm trying using `celery` to start and stop the `listen()` events every minute or so on a remote server, because the remote database that I'm using has a forced timeout of 90 seconds. Inside of the `onMessage()` function, I make calls to this database based on the contents of a received message. Because messages will happen infrequently, when it comes time to make a new request, I'll have a dropped connection for that listen instance. I can then manually call `listen()` and it will work for the next 90 seconds.  If i just call `listen()` without canceling the previous listening event, I'll end up with redundant listening events, doing each action on a cumulative basis, so therefore I need to first cancel the first event, and then start a new one. I could place `try/except` blocks and restart the login process when I lose connection, but this would make it very inefficient for my use-case. So if I can successfully stop each listen loop, and start a new instance of one every 80 seconds externally, I think that will solve my problem. I tried using `client.listening=False` but that seems to have no effect. I may be using it incorrectly.
```
class ListenBot(Client):
    def onMessage(self, message_object, thread_id, **kwargs):
        text = message_object.text
        # Do stuff with text and query the database here
         msg = #Results of Doing stuff
        def send_msg(msg):
            self.send(Message(text=msg), thread_id=id, thread_type=ThreadType.USER)
```
Below I attempt to run this code every 80 seconds, expecting it to externally stop the running `listen()` process, and immediately start a new one.
```
def awake():
    client = ListenBot(Secrets.facebook_email, Secrets.facebook_password)
    if not client.isLoggedIn():
        client = ListenBot(Secrets.facebook_email, Secrets.facebook_password)
    client.listening = False
    client.listen()
```
What seems to happen, is that  `client.listening=False` has no affect. This block of code runs, and then it runs 80 seconds later second time, and so forth, and then I have two or more concurrences of the the listen event happening, which results in the same message being sent multiple times etc.
Is there a way to start and stop the listening event to stop this from happening? Thanks

**Comment by madsmtm** [comment]
Okay, I think I understand you now (please correct me if I'm wrong). You have a database, and which you want to do something with, every time your bot recieves a message. This database times out every 90 seconds, which is the main issue.
I would think it'd be easier trying to solve that issue. Maybe you could make a function, that checks if the database is timed out (/ is about to timeout), and if so, refreshes it? That way you wouldn't have to write your own listening loop and such. If this isn't possible, maybe you can provide some more insight to exactly how your setup is.

I don't know `celery`, it's above my level of expertise, the only real thing I can do is tell you about how the listening methods work, and maybe that'll help you figure it out.
- `Client.startListening()` tells Facebook that we're about to listen, and get some variables that we need while doing that
- `Client.stopListening()` cleans up those variables
- `Client.listening` is mostly just a way to determine if the client is listening
- `Client.doOneListen()` makes a request with a timeout of 30 seconds to Facebook, that asks for the latest updates
- First example:
    - `doOneListen` is called, and waits for any input from Facebook
    - 10 seconds pass
    - Somebody sends a message / does an action on Facebook
    - Facebook sends data about this to the client
    - The data is processed, and `onMessage` is called
    - `doOneListen` returns
- Second example
    - `doOneListen` is called, and waits for any input from Facebook
    - 30 seconds pass while nothing happens
    - `doOneListen` times out, and returns

**Comment by juju4Life** [comment]
Yes, that is pretty much correct. What I'm doing right now, is just timing it so that right at 90 seconds `client.listening=False` and then just completely starting a new process, and then when that loop ends, immediately start a new process. Doing this, I have noticed that if I just start a new process and keep listening=True, then the previous connection stays if it's within that 90 second time frame. I recommend adding an optional argument to ping any connecting database, or user-input database as to offer additional utility. Or even an option argument to restart another instance of the loop after n seconds. Would do a pull request, but I'm fairly new to all of this lol.

**Comment by madsmtm** [comment]
Closing, assuming you've either moved on, or figured out how to do it. Feel free to reopen if there's anything else I can help with!
