### ISSUE TITLE
"no module named fbchat"

### ISSUE THREAD

**Issue by rousbound** [carpedm20/fbchat#334]
## Description of the problem
I can't run any of the examples. I keep getting the "no module named fbchat", and indeed, there is no file named like that in the folders of the master-fbchat folder.

## Code to reproduce
from fbchat import Client
from fbchat.models import *

client = Client('<email>', '<password>')

print('Own id: {}'.format(client.uid))

client.send(Message(text='Hi me!'), thread_id=client.uid, thread_type=ThreadType.USER)

client.logout()

## Traceback
Traceback (most recent call last):
  File "C:\Users\geral\OneDrive\Program\fcbchat\teste1.py", line 1, in <module>
    from fbchat import Client
ModuleNotFoundError: No module named 'fbchat'

## Environment information
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 16:07:46) [MSC v.1900 32 bit (Intel)] on win32

**Comment by kapi2289** [comment]
Did you installed `fbchat` with `pip3 install fbchat`?

**Comment by rousbound** [comment]
So, I installed by running setup on the extracted .zip file. Im running on windows, how can install by using `pip3 install fbchat` ?

**Comment by kapi2289** [comment]
Try to open `cmd` and type `pip3 install fbchat`, if it doesn't work look at [this](https://stackoverflow.com/questions/41501636/how-to-install-pip3-on-windows).

**Comment by rousbound** [comment]
Thanks so, much it worked! Also, I had to open the cmd and write `cd C:\Users\geral\AppData\Local\Programs\Python\Python36-32\Scripts` that was my path, before running `pip3.6 install fbchat`
