### ISSUE TITLE
markAsRead() has no effect

### ISSUE THREAD

**Issue by 2FWAH** [carpedm20/fbchat#336]
## Description of the problem
Using markAsRead() on an unread thread does not mark messages as read.

## Code to reproduce
Let thread_id be the ID of a thread with unread messages.
```py
client.markAsRead(thread_id)
```
Check on Facebook website: thread is not marked as read.
User(s) in thread does not see recent messages as read by me.

## Traceback
No exception or error

## Environment information
- Python 3.5.3
- `fbchat` version 1.4.0

**Comment by madsmtm** [comment]
You're right, this was caused by sending `True` and `False` instead of `true` and `false` to Facebook

**Comment by eduardorh1312** [comment]
how can i fix this? i have this problem

**Comment by madsmtm** [comment]
Hi there @eduardorh1312, this issue should've been fixed a while ago. I know I'm a bit late answering, but if you're still having problems, could you open a new issue, with more details about your specific problem?
