### ISSUE TITLE
Search for group or user by URL

### ISSUE THREAD

**Issue by JaminShanti** [carpedm20/fbchat#344]
## Description
Example: I'd like to be able to search for a user or group by the URL.

## Research (if applicable)
I reviewed the fetch functions in https://fbchat.readthedocs.io/en/master/api.html and did not see this supported.  I want to store the user's and group's URL as the key value to query for their attributes.

**Comment by madsmtm** [comment]
This is not directly possible, though maybe you could extract the username or the user ID / group ID from the URL, and then use `Client.searchForThreads` or `Client.fetchThreadInfo` respectively

**Comment by JaminShanti** [comment]
Happy New Year! 😄
