### ISSUE TITLE
Separating My Messages vs User Messages

### ISSUE THREAD

**Issue by DarrenRainey** [carpedm20/fbchat#347]
I'm currently using the following code and was wondering if there is a function to mark which messages are mine and which messages are from the other user(s)

```from fbchat import Client
from fbchat.models import *
import sys
import codecs
sys.stdout = codecs.getwriter('utf8')(sys.stdout)
sys.stderr = codecs.getwriter('utf8')(sys.stderr)

client = Client('###################', '#########################')

# Gets the last 10 messages sent to the thread
messages = client.fetchThreadMessages(thread_id='###############################',limit=300)
# Since the message come in reversed order, reverse them
messages.reverse()
# Prints the content of all the messages
for message in messages:
    print (message.text)

**Comment by Charliiee** [comment]
`Message` class has an attribute '`author`' that stores the user who owns it. So you could check the `message.author` against your friend's userid, supposing you've stored it beforehand, and check whether the message is his or not (in this case it's yours).

**Comment by DarrenRainey** [comment]
Ok thanks I'll have to look into that later.

**Comment by madsmtm** [comment]
Closing, assuming the submitter figured out the problem. Feel free to reopen 😉
