### ISSUE TITLE
How can I download an attachment that was sent to me. 

### ISSUE THREAD

**Issue by AshrafAkon** [carpedm20/fbchat#348]
I am building a script and I would like to know that how can I use this to download an attachment that was sent to me via a group chat or personal message. If I can just get the url of attachment , that will also work. Then I can download that. I searched the documentation and found a class called "FileAttachment", that has a method called url. But I was not able to use that. Can anyone help me with this issue on how can I download an attachment. I also want to fetch all unseen messages of a group. How can I do that?

**Comment by kapi2289** [comment]
`url` is an attribute, no method.
This is an example
```py
import requests
attachment = message.attachments[0] # Get the first attachment from the message
if isinstance(attachment, FileAttachment): # Check if it's a file
    url = attachment.url # Get url to download
    filename = attachment.name # Get file name (you can use custom file name, but remember to use a proper file format)
    content = requests.get(url).content # Downloading the file
    with open(filename, "wb") as file:
        file.write(content) # Saving it
```

**Comment by AshrafAkon** [comment]
But i still have some problems. The solution you provided has a line .(attachment = message.attachments[0])
Now on that line what does "message" refers to? and I cant find anything on ".attachments[x]". Can you please tell me more about that. I just found out about this module yesterday. That's why I am having this problems. If you can provide me a working example. That would be very nice.

**Comment by kapi2289** [comment]
Please [read the docs](https://fbchat.readthedocs.io/en/master/intro.html), so you will know how to fetch message.

**Comment by kapi2289** [comment]
Yes, but `fetchThreadMessages` returns an array so make sure to use `[0]` at the end of it.

**Comment by kapi2289** [comment]
```py
message = client.fetchThreadMessages(thread_id='id', limit=1)[0]
attachments = message.attachments
first_attachment = attachments[0]
```

**Comment by AshrafAkon** [comment]
Thanks. I have solved the issue.
