### ISSUE TITLE
Fetch all messages in a thread

### ISSUE THREAD

**Issue by Akpofure** [carpedm20/fbchat#358]
I would like to retrieve all the messages from a conversation if possible can you give me the code for python 3. Thank you and have a good day.

**Comment by madsmtm** [comment]
As you guessed yourself, you have to use [Client.fetchThreadMessages](https://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.fetchThreadMessages). You would run it in a loop, and wait until no more messages were returned, something like this:
```py
import time
client = Client("<email>", "<password>")
thread_id = <thread ID>
messages = []
before = time.now()
while True:
    extra = client.fetchThreadMessages(thread_id=thread_id, before=before)
    if not extra:
        break  # 
    print("Got the following messages:", messages)
    messages.extend(extra)
    before = messages[-1].timestamp
```
Though it's an untested sketch, you might have to make a few adjustments to make it work 😉 . You could also (which would probably be cleaner) set it up as a generator

**Comment by wetmore** [comment]
This approach only goes back so far; it stops returning new messages after about 12 days in my case, and starts returning the same messages over and over.

**Comment by madsmtm** [comment]
@wetmore, are you still having this problem? If so, please create a new issue, I'm closing this one (I'm on an issue cleanup spree 😁)
