### ISSUE TITLE
Workspace possible?

### ISSUE THREAD

**Issue by knowledge1st** [carpedm20/fbchat#360]
It's not a problem but a question, so change the tag if possible.

Hello everyone, my questions are this ones:
1.- Do my user+pw get saved into some file? or it's only temporally while the client is open?
2.- Can this module be used in Workspace by Facebook? I would love to apply this to my workarea... But i'm doubting if it can connect to other url that isn't fb directly...

Thank you all!

**Comment by knowledge1st** [comment]
So de user and pw are only passed to fb client? good.
Yeah, that thing... Workplace, mb.
I'm going to do the request... 
Thank u

**Comment by madsmtm** [comment]
Sorry, I haven't seen your question before now, since you edited your question after I saw it the first time :grin:

But what I meant with a feature request was simply just to create a seperate issue dedicated for that. Though if it's easier, we can just reuse this issue

**Comment by madsmtm** [comment]
I'll close this, and track Workplace related stuff in https://github.com/carpedm20/fbchat/issues/402 (since it's more focused, while this issue is also a question 😊)
