### ISSUE TITLE
Failed loading session

### ISSUE THREAD

**Issue by hoangvu304** [carpedm20/fbchat#364]
It's failed when use session cookies. I tried to run command one by one in client.py, it's ok.
## Code to reproduce
```python
import json
import fbchat
cookies = {}
try:
    with open('session.json', 'r') as f:
        cookies = json.load(f)
except:
    pass

client = fbchat.Client('email', 'password', session_cookies=cookies)
with open('session.json', 'w') as f:
    json.dump(client.getSession(), f)
```

## Traceback
```
Failed loading session
Traceback (most recent call last):
  File "/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py", line 372, in setSession
    self._postLogin()
  File "/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py", line 225, in _postLogin
    self.fb_dtsg = re.search(r'name="fb_dtsg" value="(.*?)"', r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

## Environment information
- Python: 3.6.6
- `fbchat`: 1.4.1

**Comment by hoangvu304** [comment]
Thank for you reply @madsmtm . Yes, it happen every time i run. This is traceback when i tried with my facebook:
# traceback
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com:443
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET /?__req=1&seq=0 HTTP/1.1" 200 None
Failed loading session
Traceback (most recent call last):
  File "/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py", line 372, in setSession
    self._postLogin()
  File "/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py", line 225, in _postLogin
    self.fb_dtsg = re.search(r'name="fb_dtsg" value="(.*?)"', r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR:client:Failed loading session
Traceback (most recent call last):
  File "/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py", line 372, in setSession
    self._postLogin()
  File "/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py", line 225, in _postLogin
    self.fb_dtsg = re.search(r'name="fb_dtsg" value="(.*?)"', r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Logging in anmayxalo@gmail.com...
INFO:client:Logging in anmayxalo@gmail.com...
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com:443
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /?__req=1&seq=0 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /login/save-device/?login_source=login&refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /login/save-device/cancel/ HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com:443
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET /?__req=3&seq=0 HTTP/1.1" 200 None
Login of anmayxalo@gmail.com successful.
INFO:client:Login of anmayxalo@gmail.com successful.

**Comment by madsmtm** [comment]
Okay, that's interesting, it seems like your session is invalid for some reason, but I can't tell for sure.

Is it possible for you to try modifying the source locally? If so, modify line 219 in `fbchat/client.py` (that would be `/home/vuht/p3venv/lib/python3.6/site-packages/fbchat/client.py` on your machine) like this:
```diff
@@ -216,7 +216,7 @@ class Client(object):
         self.user_channel = "p_" + self.uid
         self.ttstamp = ''
 
-        r = self._get(self.req_url.BASE)
+        r = self._get(self.req_url.BASE + "/home.php")
         soup = bs(r.text, "html.parser")
 
         fb_dtsg_element = soup.find("input", {'name': 'fb_dtsg'})
```
And then run the script and give me the debug output as before

**Comment by madsmtm** [comment]
Well, I didn't expect it to work, but it helped me narrow down the cause, thanks for trying!

From what I've found, if you access the URL `/home.php`, one of three things will happen:
1. If you have a clean session (aka. without having been logged in before), then you're redirected to `/login.php`
2. If you have a logged in session, then you're shown the home page
3. If you have a session that's been logged out, then you're redirected to the index, where a "Recent logins" screen is displayed, like this one:
   ![Facebook Main Screen](https://user-images.githubusercontent.com/10577181/49698513-33251f00-fbc5-11e8-9f00-3dd993ccbbb0.png)

In your case, the third happens, so it's not because the session cookies are loaded incorrectly, or because our parsing of `fb_dtsg` is wrong, it's because Facebook doesn't like your session.

Now as to why it doesn't like your session, I can't say yet. My best bet would be that you should fixate your `user_agent` between logins, which can be done like this:
```py
# You can use any other well-formatted user agent string here
user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
client = fbchat.Client('email', 'password', user_agent=user_agent, session_cookies=cookies)
```

You could try narrowing down the problem even further by fully removing the file access, so in total like this:
```py
import fbchat
import logging
logging.basicConfig(level=logging.DEBUG)

user_agent = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36"
client = fbchat.Client('email', 'password', user_agent=user_agent)
cookies = client.getSession()
client2 = fbchat.Client('email', 'password', user_agent=user_agent, session_cookies=cookies)
```

**Comment by hoangvu304** [comment]
Thank you @madsmtm  so much, it's work !

**Comment by hoangvu304** [comment]
Yes, I use user_agent as you suggest and save cookies into model, then load it when login. I think my problem was read/write cookies from json file before.

**Comment by rach-sharp** [comment]
I was getting this issue when I started from some example code and totally missed the call to `client.logout()` at the end, which was why my session cookies were invalid between runs of the script, just something to check for anyone who sees this

**Comment by SDS-2704** [comment]
> I can't directly reproduce, does this happen every time you run it? Can you try giving some `urllib3` debugging output? (by preceeding your file with the following):
> 
> ```python
> import logging
> logging.basicConfig(level=logging.DEBUG)
> ```

I am facing an error too 

Logging in shivam.d.sharma...
Attempt #1 failed, retrying
Traceback (most recent call last):
  File "C:\Users\my\Anaconda3\lib\site-packages\fbchat\_client.py", line 209, in login
    user_agent=user_agent,
  File "C:\Users\my\Anaconda3\lib\site-packages\fbchat\_state.py", line 149, in login
    return cls.from_session(session=session)
  File "C:\Users\my\Anaconda3\lib\site-packages\fbchat\_state.py", line 186, in from_session
    fb_dtsg = FB_DTSG_REGEX.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
