### ISSUE TITLE
searchForUsers('<name>') not working as Expected

### ISSUE THREAD

**Issue by kaushalvivek** [carpedm20/fbchat#365]
## Description of the problem
```searchForUsers()``` should return a list of objects that match the name entered as the query, but it's returning only one response *(presumably, the first response.)*

## Code to reproduce
```py
users = client.searchForUsers('Jane')
for user in users:
    print("User's ID: {}".format(user.uid))
```
This should print the user ID of all chats with 'Jane' in their name, but it would return just one option.

## Environment information
- Python 3.7.0
- `fbchat` 1.4.1

**Comment by kapi2289** [comment]
Maybe you have only one Jane on your Facebook friends list?

**Comment by kaushalvivek** [comment]
Oh, no, I checked with multiple search terms. Terms that should definitely have returned multiple results.

**Comment by kaushalvivek** [comment]
https://github.com/carpedm20/fbchat/blob/89a277c3541e5b5a5a1b4c1dd6aaf9025ce43707/fbchat/client.py#L505

Found the issue, the limit is set as 1 here. I suppose that was done for a reason?
5 or 10 would be a better limit logically, I'd say.

**Comment by madsmtm** [comment]
I looked at the history, but I couldn't find an explicit reason for setting the limit so low, maybe it was just to be pragmatic, and encourage people to set their own limits?

**Comment by kaushalvivek** [comment]
It does compromise on usability in its present implementation though, maybe a limit of 3 or 5 would be a better balance between usability and a pragmatic approach?

**Comment by madsmtm** [comment]
Well, you've set it at 10 in #366, which is definitively a better choice for `searchForThreads`, and I don't think the limits should differ between the `searchForX` methods.

I'd still think that the overly pragmatic choice is better. I'd rather add explicit documentation about this fact, than set an arbitary limit. You can see an example of this in the [`asks` documentation](https://asks.readthedocs.io/en/latest/a-look-at-sessions.html#important-connection-un-limiting)

But then again, `searchForMessageIDs`, `searchForMessages` and `search` limits of `5`, and `fetchThreadMessages` and `fetchThreadList` have limits of `20`, so maybe it's not a big deal.

I guess I'll approve this change, and merge the PR when it's updated 👍

**Comment by kaushalvivek** [comment]
Hi @madsmtm , I've updated ```searchForX``` methods for ```Users, Pages, Groups and Threads``` and set the limit to 10. Checkout #366.
