### ISSUE TITLE
ValueError: '🎄' is not a valid MessageReaction

### ISSUE THREAD

**Issue by Demindiro** [carpedm20/fbchat#368]
## Description of the problem
My friends somehow (probably with the android client which for some reason has more features / is less limited) managed to react with a 🎄. The result is that I can't fetch messages up to a certain point (or well, not directly at least).
Other emojis work as well, of course.
<img width="271" alt="schermafbeelding 2018-12-12 om 12 54 51" src="https://user-images.githubusercontent.com/17316999/49868286-4296a900-fe0d-11e8-80e0-fa4735eddb26.png">
<img width="207" alt="schermafbeelding 2018-12-12 om 12 54 56" src="https://user-images.githubusercontent.com/17316999/49868293-45919980-fe0d-11e8-9c34-1ad64ddd755d.png">
<img width="372" alt="schermafbeelding 2018-12-12 om 12 55 01" src="https://user-images.githubusercontent.com/17316999/49868297-47f3f380-fe0d-11e8-958e-2fe0497142c4.png">

## Code to reproduce
```py
from fbchat import Client
client = Client("<email>", "<password>")
client.fetchThreadMessages('1234567890', limit=400)
```

## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/fbchat/client.py", line 847, in fetchThreadMessages
    messages = list(reversed([graphql_to_message(message) for message in j['message_thread']['messages']['nodes']]))
  File "/usr/local/lib/python3.7/site-packages/fbchat/client.py", line 847, in <listcomp>
    messages = list(reversed([graphql_to_message(message) for message in j['message_thread']['messages']['nodes']]))
  File "/usr/local/lib/python3.7/site-packages/fbchat/graphql.py", line 212, in graphql_to_message
    rtn.reactions = {str(r['user']['id']):MessageReaction(r['reaction']) for r in message.get('message_reactions')}
  File "/usr/local/lib/python3.7/site-packages/fbchat/graphql.py", line 212, in <dictcomp>
    rtn.reactions = {str(r['user']['id']):MessageReaction(r['reaction']) for r in message.get('message_reactions')}
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 543, in __new__
    return cls._missing_(value)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/enum.py", line 556, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: '🎄' is not a valid MessageReaction
```

## Environment information
- Python version: 3.7.1
- `fbchat` version: 1.4.2

**Comment by madsmtm** [comment]
This is related to #220. Maybe we can find a solution that fixes both, without breaking backwards compatibility?

**Comment by Demindiro** [comment]
An idea I have is replacing the enums with something that acts like an enum but allows any value instead of throwing a `ValueError` This allows passing on 'invalid' values without breaking backwards compatibility. It isn't a very clean solution though.

**Comment by madsmtm** [comment]
For that, we might investigate the `aenum` library, as @ekohilas mentioned.

But although I'd like to keep backwards compatibility, if we can't make something that solves these issues, I'm not directly opposed to making `Message.reactions` contain a dict with `None` for some values.
