### ISSUE TITLE
client.getUsers("FRIEND'S NAME") doesn't work

### ISSUE THREAD

**Issue by hman190** [carpedm20/fbchat#37]
Hi,
I used the example from README, but it doesn't work at all. Can you give me some advices? My code is as follows:

```
import fbchat
client = fbchat.Client("MY_ID", "MY_PASSWORD")
friends = client.getUsers("Ning")  # I tried a friend's name
friend = friends[0]
```

After executing the code, it shows the following error messages:

```
friends = client.getUsers('Ning')
File "build/bdist.linux-x86_64/egg/fbchat/client.py", line 189, in getUsers
File "build/bdist.linux-x86_64/egg/fbchat/utils.py", line 18, in get_json
File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
return _default_decoder.decode(s)
File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 63 (char 62)
```

Thanks!

**Comment by PidgeyL** [comment]
Judging from the name, I guess your response data might contain non-ascii chars, am I correct?

**Comment by Charliiee** [comment]
Download the repo on your computer, then edit utils.py file. Try to change get_json(text) function from this: `return json.loads(re.sub(r"for.*(.*;.*;.*).*;", '', text.encode('utf-8').decode("unicode-escape"), 1))` to this: `return json.loads(re.sub(r"^[^{]*", '', text, 1))`. Save the file and install fbchat again via setup.py from the folder you've downloaded. 

> code by @HashirZahir on pull request #32

**Comment by neilyueh** [comment]
still have error. would you please help me to take a look on it ? thank you.

>>> import fbchat
>>>
>>> client = fbchat.Client("neil.yueh@gmail.com", "*******")
Logging in...
>>> friends = client.getUsers("李魯民")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-armv7l/egg/fbchat/client.py", line 189, in getUsers
  File "build/bdist.linux-armv7l/egg/fbchat/utils.py", line 18, in get_json
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting ',' delimiter: line 1 column 64 (char 63)

**Comment by neilyueh** [comment]
hi !

with fbchat help. I can successfully login into facebook and get friend on it. but I am not able to sent message to my friend. would you please kindly help to see anything wrong here ? thank you.

# encoding: utf-8
import fbchat

client = fbchat.Client("neil.yueh@gmail.com", "********")

friends = client.getUsers("李魯民")  # return a list of names
friend = friends[0]
sent = client.send(friend.uid, "測試訊息") # <-- always get false return. please help. thank you.
if sent:
    print("Message sent successfully!")

**Comment by neilyueh** [comment]
thanks. return json.loads(re.sub(r"^[^{]*", '', text, 1)) 
fix the issue for me.
