### ISSUE TITLE
Method to get current thread color?

### ISSUE THREAD

**Issue by sammyjp** [carpedm20/fbchat#374]
## Description
It would be good to be able to know the current thread color of a given thread. At the moment it seems the only way to determine the thread color is to change it to a new one so you know what it is.
Also is there a way of changing the colors of specific messages or can it only be applied to the whole thread?

**Comment by kapi2289** [comment]
```python
thread = client.fetchThreadInfo(thread_id)[thread_id]
print(thread.color)
```

**Comment by madsmtm** [comment]
Closing, assuming @kapi2289's suggestion solves the issue
