### ISSUE TITLE
ReadTheDocs configuration file

### ISSUE THREAD

**Issue by madsmtm** [carpedm20/fbchat#391]
The documentation is currently failing because the build relied on `setuptools` (and we've switched to `flit`).

This is a good chance to switch to a [configuration file](https://docs.readthedocs.io/en/latest/config-file/index.html) instead of the UI configuration. If anyone has any experience with good configuration options, then I'm all ears! Otherwise I'll just tinker with it myself 😊

**Comment by kapi2289** [comment]
First of all, I would suggest changing the theme to for example [sphinx_rtd_theme](https://github.com/rtfd/sphinx_rtd_theme), because actual is really ugly. To fix the build we need to set the requirements file, you can do this even now in UI settings.

**Comment by KANG-NEWBIE** [comment]
question, is this tool safe?
and there is no logger in it?

**Comment by kapi2289** [comment]
Yes, it is safe, the code is open source, so you can check it yourself :wink:
