### ISSUE TITLE
fbchat and fan page 

### ISSUE THREAD

**Issue by JesperSoerensen** [carpedm20/fbchat#397]
## Description
Hi, is it possible to use fbchat and send messages via fan page?

I have a fan (business) page on my private FB and would like to send messages from my fan page and not from my private page. A fan page still use the login and password from my private FB.

possible and how to?

**Comment by kapi2289** [comment]
No, it's not possible with this library. For that you can use the official Facebook API

**Comment by JesperSoerensen** [comment]
Hi kapi2289,
OK, thank you for reply.

br Jesper
