### ISSUE TITLE
client.send() return true but message is not sent

### ISSUE THREAD

**Issue by Erickira** [carpedm20/fbchat#40]
After the fix proposed by @Charliiee I wrote this code, his purpose is to use a list of person to send them a message (today's agenda):

```
Tabl=[List of people name]
for index, item in enumerate(Tabl, start=0):
    friends=client.getUsers(item)
    friend=friends[0]
    az = open(os.path.join(File location),'a')   #Keeping people userid for reference and futur use.
    message=friend.uid
    az.write(str(message)+'\n')
az.close()

with open(os.path.join(location of userid file), 'r') as f:
    for line in f:
        with open(os.path.join(file location of the message), 'r') as e:
            for lined in e:
                line=re.sub(r"\W", "", line)
                sent = client.send(line, lined)
                if sent==False:
                    print line
                    sent=False
```

I've noticed 2 things with this code:
- People that never sent a message to the account won't receive the message.
- Even like that not everyone will receive the message (while sent is always True).

Is there a limit of message that can be sent? Do I need people to often message the bot?

**Comment by PidgeyL** [comment]
Messages sometimes get blocked, when they suspect bots. Check if you need to authenticate, by logging in, and sending the exact same message

**Comment by Erickira** [comment]
You mean being connect to the facebook account at the same time the program send the message?
Seem like it works better but the message is not sent to everyone. I'll try dividing my list in smaller part and sending message to each part with a 2 minute interval.
True, after logging it seem like if I send the message myself facebook tell me that I'm not using it the way it should be used and I could be temporally blocked.
I'll try that and if it works I'll close the issue. Thanks for your help.

**Comment by madsmtm** [comment]
Facebook has changed a lot of things, and `fbchat` has been updated, so I'm assuming this is outdated ;)
