### ISSUE TITLE
Facebook Account getting disabled

### ISSUE THREAD

**Issue by MigDinny** [carpedm20/fbchat#404]
I am currently developing a bot using this project. This is really useful and it's helping me a lot.

After some days of testing (I've created an account for this purpose) it got suspended. It is due to multiple "suspicious logins" (because of the script accessing the account).

What can I do to prevent this?

**Comment by madsmtm** [comment]
See https://github.com/carpedm20/fbchat/issues/361 for suggestions. The primary suggestion is to reuse session cookies! I'll close this for now, but this is definitely a bug, that I'd like to improve the documentation to clarify.
