### ISSUE TITLE
Simple question: client own User information. 

### ISSUE THREAD

**Issue by miguelwon** [carpedm20/fbchat#407]
The User object allows you to get basic information such as name and first_name. How can I get the User own object for the client session? After login a client I want to get his/her name, etc.

**Comment by madsmtm** [comment]
You can get the user ID with [`Client.uid`](https://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.uid), and use that in [`Client.fetchUserInfo`](https://fbchat.readthedocs.io/en/master/api.html#fbchat.Client.fetchUserInfo):
```py
client = Client(...)
user = client.fetchUserInfo(client.uid)[client.uid]
```

**Comment by madsmtm** [comment]
Closing, assuming the above suggestion answers the question.
