### ISSUE TITLE
Client.send() always fails?

### ISSUE THREAD

**Issue by dstelzer** [carpedm20/fbchat#41]
Most features work fine, but Client.send() always returns False with no message being sent. Comparing the POST requests that fbchat makes with those from messenger.com, Messenger's message_batch[0][message_id] parameter is always a single nine-digit number, while fbchat's is not. But I don't know how it's generated or how to make a valid one. Have others noticed this?

**Comment by modulebaan** [comment]
I'm also having this problem...

**Comment by blcc** [comment]
Hi dstelzer,

I tried to find the POST data about send message with firefox inspector.
But see nothing in post form but query string.
I think I missed something to get the post form. How did you get the form data?

BTW, maybe the facebook mobile page will be a simpler approach for sending message.
https://m.facebook.com/messages/send/

**Comment by modulebaan** [comment]
I can confirm that the pull request #42 fixes it
