### ISSUE TITLE
New Reply messages

### ISSUE THREAD

**Issue by JackCloudman** [carpedm20/fbchat#410]
Now you can reply messages and bot not detect it as message in method onMessage
see: 
![image](https://user-images.githubusercontent.com/17970185/54957297-f54fca80-4f17-11e9-8e6d-51bb85076277.png)

**Comment by kapi2289** [comment]
Yes, this is a bug, because I don't know why, Facebook sends these reply messages in a completely different JSON. I'm trying to fix this in #409

**Comment by madsmtm** [comment]
I'll reopen this for now, until we've closed #409 😉
