### ISSUE TITLE
sendremotefile (image) at the same time

### ISSUE THREAD

**Issue by stanly0726** [carpedm20/fbchat#428]
as you know 
when sending multiple images at once can place them into small grids
can sendremotefile do that?
it sends image one by one and takes LOT OF SPACE now

**Comment by madsmtm** [comment]
Sorry for the later response, but yes, this is possible, you can use `Client.sendRemoteFiles`/`Client.sendLocalFiles`, which takes a list as it's first argument, for exactly this purpose 😉

So something like this:
```python
images = ["https://example.com/image.png", "https://example.com/image.jpg"]
client.sendRemoteFiles(images)
```
