### ISSUE TITLE
Possible to choose a specific person to chat

### ISSUE THREAD

**Issue by BenjaminHoegh** [carpedm20/fbchat#429]
Is it possible to choose a specific person to chat with? So the bot only response when this person is sending a message?

**Comment by szymonszl** [comment]
I'm not sure if I understand your question, but the person that you are sending to is passed to `send` through the `thread_type` and `thread_id` parameters.
For example: 
```python
client.send(
    Message(text='Hello World'),
    thread_id='1234567',
    thread_type=ThreadType.USER
)
```
will send a message "Hello World" to the user with UID 123456.

If you want your program to react to messages sent to it, you can override the `onMessage` method so it responds to your liking, for example
```
class BotClient(Client):
    def onMessage(self, message_object, thread_id, thread_type, ...):
        message_text = message_object.text
        self.send(
             Message(text=message_text.lower()),
             thread_type=thread_type,
             thread_id=thread_id
        )

client = BotClient(email=..., password=...)
client.listen()
```
while running will respond to any received message (`onMessage`) with the message's content (`message_object.text`) but all letters turned lowercase (`.lower()`). The received message's content, thread type and id are passed as parameters to onMessage. Thread type and id represent the message's author, so sending something to these will respond to the author.

-------

Please note that I've written this response was written on mobile, so I might have done some typos in the code, or skipped some stuff. For example the function definition for onMessage is not nearly full, copy it from the function's definition in code or documentation.

**Comment by nestorghh** [comment]
It does not seem to be working when the user has a custom username in his url. I'm getting an error: FBchatFacebookError: Error when sending request: Got 500 response. Have you tried using the program to send messages to users with a custom url?

**Comment by madsmtm** [comment]
Regarding only sending messages to specific people, you can make it respond to only a specific thread as follows:
```python
class CustomClient(Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        if thread_id != "123":  # Input user ID here
            return  # Ignore all messages that are not in this specific thread
        pass  # Your bot code here
```

The [`KeepBot` example](/carpedm20/fbchat/blob/master/examples/keepbot.py) uses a similar tactic.

Regarding sending messages to users with custom URLs, then that sounds like a separate issue, perhaps you could open a separate one, and provide a bit more detail, @nestorghh?

**Comment by madsmtm** [comment]
I'll assume that @szymonszl and I answered your question, @BenjaminHoegh, if not, feel free to reopen!
