### ISSUE TITLE
Q: how to send attachments or pictures

### ISSUE THREAD

**Issue by modulebaan** [carpedm20/fbchat#43]
Hi devs,

Is it possible to send attachments or pictures with fbchat?
If it's possible, how can I do that?

**Comment by bsansouci** [comment]
The original facebook-chat-api that this is based on can (https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#sendMessage). I'm not sure if this python wrapper supports it but feel free to submit a PR and make it happen ;)

**Comment by modulebaan** [comment]
That's an incredible API :+1: I looked at the Python code but I don't think if it's supported.

**Comment by JohnathonNow** [comment]
Does PR #53 do what you want?
