### ISSUE TITLE
onChatTimestamp not called anymore

### ISSUE THREAD

**Issue by 2FWAH** [carpedm20/fbchat#430]
Hello,

## Description of the problem
`onChatTimestamp` is not called anymore for few days. It was working nice before (called every few minutes) but not anymore. I didn't change anything on my side, Facebook probably changed something?
Anyone else impacted?

## Environment information
- Python 3.7
- `fbchat` 1.6.5

**Comment by madsmtm** [comment]
Hmm, this is the case for me as well 😕. I've recently discovered that they're slowly moving their clients to using websockets, so I'm guessing this is one of the things that got moved.

Maybe we'll be able to find a workaround, or maybe we'll have to bite the bullet and implement websocket support (I'm still not quite sure how we should do it, considering that we'll need to make the `/pull` request simultaneously 🤔).

**Comment by madsmtm** [comment]
Should be fixed in #494, release `v1.9.0`
