### ISSUE TITLE
max char limit?

### ISSUE THREAD

**Issue by Riuchando** [carpedm20/fbchat#44]
for this there seems to be a problem when sending messages of more than 20000 characters? I was doing a binary search to find the limit and the send function returns true even though the message didn't show up in the messenger

**Comment by modulebaan** [comment]
I saw in the code there's no limit for characters... Maybe this should be added?

**Comment by madsmtm** [comment]
Facebook has changed a lot of things, and `fbchat` has been updated, so I'm assuming this is outdated ;)
