### ISSUE TITLE
2FA login error

### ISSUE THREAD

**Issue by IAmNotImportant** [carpedm20/fbchat#442]
## Description of the problem
When 2FA is enabled, instead of prompting to enter input, an error appears and another attempt is done - the script is stuck at loop.

## Code to reproduce
```py
from fbchat import Client
client = Client('<email>', '<password>')
```

## Traceback
```
Logging in <email>...
Attempt #1 failed, retrying
Traceback (most recent call last):
  File "/home/u/.local/lib/python3.7/site-packages/fbchat/_client.py", line 254, in login
    state = State.login(email, password, user_agent=user_agent)
  File "/home/u/.local/lib/python3.7/site-packages/fbchat/_state.py", line 127, in login
    code = on_2fa_callback()
NameError: name 'on_2fa_callback' is not defined
```

## Environment information
- python 3.7.3
- fbchat 1.7.2 (installed via pip)

**Comment by nomore1007** [comment]
Wow, I just had this issue too right now.

**Comment by madsmtm** [comment]
Sorry about this, I actually discovered that I made this mistake, and committed a fix, but I must have accidentally rebased it away 🙄
