### ISSUE TITLE
Get 'for (;;); {"t":"refresh","reason":110,"seq":0}' when pull message

### ISSUE THREAD

**Issue by blcc** [carpedm20/fbchat#45]
Hi,

After smoothly use for few days, I found fbchat stop pull new message.
When the _pullMessage in listen function return content, it actually return following string:

'for (;;); {"t":"refresh","reason":110,"seq":0}'

It may be mean reload page is required in browser, but have no idea how to do in requests session.

Thanks.

**Comment by bsansouci** [comment]
Hey @blcc, I work on the nodejs version of this API and we've potentially had a similar problem. The simplest solution would be to simply make a request to `www.facebook.com` and make sure to save all the new cookies it sends back, and then go back to listening. If you try, tell us if it works :)

**Comment by lobstr** [comment]
Have this same error.  Just started playing around with _pullMessage and added "clientid" to the data that gets sent to the sticky URL and it started working okay.  I don't really know what clientid is, just copied it and it's value from my browser, but hopefully that sheds some light for someone more inclined.

**Comment by blcc** [comment]
@lobstr is right. "clientid" may be used as client identification for different browser/apps. It may be generated by javascript randomly when reload the FB home page, so @bsansouci's method also work.
In fact, there is a client_id variable in fbchat/client.py. So just insert following to line 405 of client.py:
"clientid" : self.client_id,
(data in _pullMessage(). Remember the indent)
Will fix the problem.

Thanks guys.

**Comment by blcc** [comment]
@lobstr is right. The "clientid" may be used as identification of browser/apps. Which maybe generated by javascript in FB home randomly. So that @bsansouci's method also does the magic.
In fact there is client_id variable in client.py. Hence all we need to do is insert following to line 405 of fbchat/client.py:
`            "clientid": self.client_id,`


Thanks guys.
