### ISSUE TITLE
Link preview in sent messages

### ISSUE THREAD

**Issue by andrejeronimo** [carpedm20/fbchat#451]
## Description
Would be nice if we could send messages with link previews.

## Example
![image](https://user-images.githubusercontent.com/7091189/61623362-686f1080-ac6e-11e9-9aed-469f963c4bd7.png)

**Comment by kapi2289** [comment]
Duplicate of #424

**Comment by madsmtm** [comment]
Agree with @kapi2289, closing as duplicate
