### ISSUE TITLE
Some fields contain `None` when data is fetched

### ISSUE THREAD

**Issue by IAmNotImportant** [carpedm20/fbchat#458]
## Description of the problem
When I download information about users, a lot of fields are `None` (eg. last name, message count) for everyone

## Code to reproduce
```py
from fbchat import Client
import pprint

client = Client("[REDACTED]", "[REDACTED]")
users = client.fetchAllUsers()
pprint(users)
```

## Output
```
User(
  uid='[VALID UID]',
  type=ThreadType.USER,
  photo='[VALID URL]',
  name='[VALID NAME]',
  last_message_timestamp=None,
  message_count=None,
  plan=None,
  url='[VALID URL]',
  first_name='[VALID NAME]',
  last_name=None,
  is_friend=True,
  gender='[VALID GENDER]',
  affinity=None,
  nickname=None,
  own_nickname=None,
  color=None,
  emoji=None
)
```

for every fetched user.

## Environment information
- `python 3.5.3`
- `fbchat 1.7.3` intalled via pip

**Comment by IAmNotImportant** [comment]
I probably should point out that this problem is not specific to said function; `client.getUserActiveStatus(uid)` also returns `None `when called.

Am I doing something wrong?

**Comment by kapi2289** [comment]
`fetchAllUsers` doesn't provide some fields, if you want to get more info, use `client.fetchUserInfo(uid)[uid]`. About `getUserActiveStatus` it might return `None` when you hide your active status or when the user you want to get active status hide his. But if you're doing everything fine, it might be related to #430

**Comment by IAmNotImportant** [comment]
Yes, I had my status hidden. But when I turned it on, the results didn't change.

**Comment by madsmtm** [comment]
As @kapi2289 mentioned, the reason that the fields are `None` is because Facebook, at that specific endpoint, simply doesn't provide us with all the information that the `User` class can contain.

So I'll close this issue for now, the issues pertaining to `getUserActiveStatus` are as said, tracked in #430.
