### ISSUE TITLE
Send the first message

### ISSUE THREAD

**Issue by Atles** [carpedm20/fbchat#46]
Hi,

I have one problem with the fbchat.
Well ... when I send a message to a friend of mine that I have already spoken, the message arrives perfectly. The problem is when I try to send a message to a friend of mine that I never talked on facebook. The method returns True, but the message does not arrive.

Can anybody help me?

**Comment by lobstr** [comment]
How are you sending the message?  I just tried messaging someone I've never talked to before by their ID and it worked fine for me.

**Comment by Atles** [comment]
```
import csv
import fbchat
import time

client = fbchat.Client("******", "******")
f = csv.reader(open('file.csv'), delimiter=';')

for id_face in f:
    
    id_friend = int(id_face[0])
    sent = client.send(id_friend, "Hello")
```

**Comment by Atles** [comment]
I get the id of a csv file and send messages to my friends. Messages arrive perfectly for the people I talked already. As for the ones I never talked to, the message does not get to them.

**Comment by Atles** [comment]
Now it's working. Maybe it was a temporary lock.

**Comment by Schmavery** [comment]
Maybe make sure you double check this person's message requests if this happens again, sometimes facebook handles it differently...
