### ISSUE TITLE
get User name by specific id

### ISSUE THREAD

**Issue by agusmakmun** [carpedm20/fbchat#47]
```python
def unreadMessages(self):
    thread = self.client.getThreadInfo(self.userid, 0)
    for message in reversed(thread):
        print dir(message)
        #if message.is_unread:
        #    print message.body.encode('cp860', errors='ignore')
```

As following script above, we have this:
```
['__doc__', '__init__', '__module__', u'action_type', u'attachments', 
u'author', u'author_email', u'body', u'commerce_message_type', u'customizations',
u'ephemeral_ttl_mode', u'folder', u'forward_count', u'forward_message_ids', 
u'has_attachment', u'is_filtered_content', u'is_filtered_content_account', 
u'is_filtered_content_bh', u'is_filtered_content_invalid_app', u'is_filtered_content_quasar', 
u'is_forward', u'is_sponsored', u'is_spoof_warning', u'is_unread', u'message_id', 
u'meta_ranges', u'offline_threading_id', u'other_user_fbid', u'platform_xmd', 
u'ranges', u'raw_attachments', u'source', u'source_tags', u'subject', u'tags', 
u'thread_fbid', u'thread_id', u'threading_id', u'timestamp', u'timestamp_absolute', 
u'timestamp_datetime', u'timestamp_relative', u'timestamp_time_passed']
```

Can i get the name/username from `message.author`? coz, we only got `fbid:100007030058882`.

**Comment by modulebaan** [comment]
With the Facebook Graph API you can request the name and profile picture of this person if you make a call with your Facebook App ID

**Comment by agusmakmun** [comment]
@modulebaan thank for your suggest. is there any other alternative without Facebook API?

**Comment by modulebaan** [comment]
Not that I know, I tried to read URL and the HTML of Facebook but for some reasons Facebook uses different implementations in their HTML of pictures and names.

The Facebook Graph API is the easiest and most stable way to get this info, why doing different?

**Comment by Schmavery** [comment]
I believe that this is possible (see https://github.com/Schmavery/facebook-chat-api/blob/master/src/getUserInfo.js for an example), but I agree completely with @modulebaan.

**Comment by duongnguyen-leez-uq** [comment]
you can use Client.fetchUserInfo(author_id)
![image](https://user-images.githubusercontent.com/61045608/78546489-b2614c00-7827-11ea-8a58-b52f6236e4c3.png)
