### ISSUE TITLE
.send() does not work

### ISSUE THREAD

**Issue by ItSeldomRains** [carpedm20/fbchat#470]
## Description of the problem
Trying to use .send() but shows the following error instead. Everything works until the part `self.send(reply, thread_id=thread_id, thread_type=thread_type)`
 on line 16 of the given code.
Is this another issue on Python3.x and Python2.x compatibility? If so, what do I need to replace on the fbchat files?

# Example code
```py
import wikipedia
from fbchat import log, Client


class Raven(Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        self.markAsDelivered(thread_id, message_object.uid)
        self.markAsRead(thread_id)
        demand = message_object.text
        reply = wikipedia.summary(demand, sentences = 1)
        log.info("{} from {} in {}".format(message_object, thread_id, thread_type.name))
        

        if author_id != self.uid:
           self.send(reply, thread_id=thread_id, thread_type=thread_type)
           


client = Raven("email", "password")
client.listen()
```

## Traceback
```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 2775, in _parseMe
ssage
    self._parseDelta(m)
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 2745, in _parseDe
lta
    msg=m,
  File "C:\Users\User\Documents\Coding\Python27\wikipy.py", line 16, in onMessage
    self.send(reply, thread_id=thread_id, thread_type=thread_type)
  File "C:\Python27\lib\site-packages\fbchat\_client.py", line 1059, in send
    data.update(message._to_send_data())
AttributeError: 'unicode' object has no attribute '_to_send_data'
```

## Environment information
- Python version: Python 2.7
- `fbchat` 1.8.1

**Comment by szymonszl** [comment]
The argument to `send` has to be a fbchat.models.Message object, as in [this example](https://github.com/carpedm20/fbchat/blob/8052b818de5de9682f6d64405579ad640cd657ee/examples/basic_usage.py#L8), not a str/unicode (as in your example). You just have to change `reply` to `Message(text=reply)`

Also, you should switch to py3 anyways, since the deprecation date is only getting closer!

**Comment by ItSeldomRains** [comment]
Then it just says NameError: global name 'Message' is not defined

**Comment by ItSeldomRains** [comment]
> The argument to `send` has to be a fbchat.models.Message object, as in [this example](https://github.com/carpedm20/fbchat/blob/8052b818de5de9682f6d64405579ad640cd657ee/examples/basic_usage.py#L8), not a str/unicode (as in your example). You just have to change `reply` to `Message(text=reply)`
> 
> Also, you should switch to py3 anyways, since the deprecation date is only getting closer!

Then it just says NameError: global name 'Message' is not defined

**Comment by madsmtm** [comment]
Yeah, sorry, should have clarified that you need to import `Message`:
```py
import wikipedia
from fbchat import log, Client, Message
# ... snip ...
        if author_id != self.uid:
           self.send(Message(text=reply), thread_id=thread_id, thread_type=thread_type)
# ... snip ...
```
