### ISSUE TITLE
[HELP] Download a picture from url

### ISSUE THREAD

**Issue by EdouardGILLARD** [carpedm20/fbchat#475]
Hi ! 
First thank you for fbchat it's really nice ! 

I have a question, I use fetchImageUrl(image_id) and i have the URL of my image but how can i download it ? 

I test : 
with open('picture.jpg', 'w') :
        response = requests.get(<URL>, stream=True)
But i have a empty file ...

Thanks,

**Comment by madsmtm** [comment]
You'll have to do this outside `fbchat` - There are numerous options here, but something like the `requests` package would probably suffice:
```python
import requests
...  # Create client and get image ID
url = client.fetchImageUrl(image_id)
r = requests.get(url)
with open('picture.jpg', 'wb') as fp:
    fp.write(r.content)
```

**Comment by madsmtm** [comment]
Assuming the above suggestion answers the question. If not, please consult other resources (such as StackOverflow), it's not a question that I'm the most qualified to answer 😉
