### ISSUE TITLE
Regular expression is slow in get_json

### ISSUE THREAD

**Issue by dstelzer** [carpedm20/fbchat#48]
There's a noticeable delay in each call to get_json. Since the cruft at the beginning is always the same, why not use a slice operation instead of a regex?

**Comment by madsmtm** [comment]
To make `get_json` work for as long as possible. Maybe one day Facebook decides to remove the `for (;;);`. And then everybody who's not using the latest version of fbchat, will get screwed over ;)

**Comment by Schmavery** [comment]
Would it be faster to do something like
```
i = text.index("{")
if i > -1: return text[i:]
else: return ""
```

**Comment by madsmtm** [comment]
Try testing it's speed, and if it is indeed faster, then make a pull request

**Comment by madsmtm** [comment]
I did the speed test, and included your code in a commit somewhere ;)
