### ISSUE TITLE
Mentions not linking to User profiles

### ISSUE THREAD

**Issue by GraysonLee08** [carpedm20/fbchat#482]
## Description of the problem
I created a thread message with multiple mentions. The message posts however the mentions don't link to the User's profile like a typical mention on Facebook does. May not be a true issue but was expecting the mention to have the same experience at a standard mention. 

## Code to reproduce
```py
# Logging In
from fbchat import Client
from fbchat.models import *

client = Client('email', 'password')

# Check to see if logged in
if not client.isLoggedIn():
    client.login('email', 'password')

# Thread ID = 0123456789

thread_id = '0123456789'
thread_type = ThreadType.GROUP

# Will send a message with a mention
client.send(Message(text='Testing the @User1 @User2', 
    mentions=[Mention(thread_id, offset=12, length=6), 
    Mention(thread_id, offset=19, length=6)]),
    thread_id=thread_id, 
    thread_type=thread_type)

# Securely log out
client.logout()

```
## Environment information
- Python 3.7.3
- fbchat 1.8.3

**Comment by kapi2289** [comment]
When you're making mentions `Mention(user_id, offset=19, length=6)` - the `user_id` must be the mentioned user ID.

Or you can use `formatMentions`
```python
client.send(Message.formatMentions("Testing the {} {}",
	('<first user id>', '@User1'), ('<second user id>', '@User2')),
	thread_id=thread_id, thread_type=thread_type)
```

**Comment by madsmtm** [comment]
I'll assume this is solved by @kapi2289's suggestion
