### ISSUE TITLE
Instantiates Client with access token, instead of email and password

### ISSUE THREAD

**Issue by zsolt-vincze** [carpedm20/fbchat#487]
## Description
Long story short; My program authenticates users through native SDKs (web, android, ios). This way, the program doesn't know the user's credentials just their userId and accessToken (standard, long-lived, page-access-token, etc). Is it possible to use this framework with those data instead of the plain email/pwd ?

## Research (if applicable)
I know, that you are using cookies as the website does, and I know that the FB's Graph Api doesn't support many things. But I don't know what those variables does in a Cookies and I have no idea, how I can get the same data from the Cookies by the access token or even is it possible to use your features with access token.

**Comment by madsmtm** [comment]
Short answer: No 😕.

You can use the userId/accessToken through Facebook's Graph API, but as you said, it's quite limited in what it can do. And hence also the reason `fbchat` exist (to "fill in the gap").
But sadly, this requires a set of cookies (because we emulate a browser), and as far as I know, you can't extract cookies from that.

**Comment by zsolt-vincze** [comment]
Thank you your response. I understand the limits and... this framework is still useful either way. So I'm thankful

**Comment by zsolt-vincze** [comment]
@madsmtm : Can I open the same urls in the browser? I mean, if the user is logged in and opens a link (e.x. /chat/user_info_all ) will it download the same data? What is the full url ? ( Is it possible the load that link in a browser, under a different domain? )

**Comment by madsmtm** [comment]
Not sure I understand your question, but calling `Client.fetchAllUsers` will make a POST request to `https://www.facebook.com/chat/user_info_all`, where it will download the same data.
