### ISSUE TITLE
markAlive not working

### ISSUE THREAD

**Issue by k4r3l01** [carpedm20/fbchat#490]
Hello please i have problem when i set markAlive to false so my account is still permanently active

**Comment by madsmtm** [comment]
Probably related to https://github.com/carpedm20/fbchat/issues/483

**Comment by SalahdinAyoubi** [comment]
from fbchat import Client
from fbchat.models import *

# enter your username and password
userId = ""
pss = ""


# login and save session_cookies
client = Client(userId , pss )

def handel_session():
    session = client.getSession()
    k = session.keys()
    v = session.values()
    for i , a in zip(k , v):
        print(i,a)

print("#############")

def get_information():
    person = str(input(" Enter person to search : "))
    users = client.searchForUsers(person)
    user = users[0]
    print("User's ID: {}".format(user.uid))
    print("User's name: {}".format(user.name))
    print("User's profile picture url: {}".format(user.photo))
    print("User's main url: {}".format(user.url))
    sms = input(" Ener Message : ")
    if sms:
        client.send(Message(text=sms), thread_id=user.uid, thread_type=ThreadType.USER)
        print(" Sent Mzssage")
    else:
        print(" Eroor sent Message ")




# get messages reverse
def get_messages():
    messages = client.fetchThreadMessages(user.uid)
    messages.reverse()
    for msg in messages:
        print(msg)

#msg = client.send(Message(text='Hi me!'), thread_id=client.uid, thread_type=ThreadType.USER)
def log_out():
    ressult = client.logout()
    if ressult:
        print(" Logged Out Successfully ")
    else:
        print(" Error in Login Out ")
get_information()
log_out()

**Comment by SalahdinAyoubi** [comment]
from fbchat import Client
from fbchat.models import *

# enter your username and password
userId = ""
pss = ""


# login and save session_cookies
client = Client(userId , pss )

def handel_session():
    session = client.getSession()
    k = session.keys()
    v = session.values()
    for i , a in zip(k , v):
        print(i,a)

print("#############")

def get_information():
    person = str(input(" Enter person to search : "))
    users = client.searchForUsers(person)
    user = users[0]
    print("User's ID: {}".format(user.uid))
    print("User's name: {}".format(user.name))
    print("User's profile picture url: {}".format(user.photo))
    print("User's main url: {}".format(user.url))
    sms = input(" Ener Message : ")
    if sms:
        client.send(Message(text=sms), thread_id=user.uid, thread_type=ThreadType.USER)
        print(" Sent Mzssage")
    else:
        print(" Eroor sent Message ")




# get messages reverse
def get_messages():
    messages = client.fetchThreadMessages(user.uid)
    messages.reverse()
    for msg in messages:
        print(msg)

#msg = client.send(Message(text='Hi me!'), thread_id=client.uid, thread_type=ThreadType.USER)
def log_out():
    ressult = client.logout()
    if ressult:
        print(" Logged Out Successfully ")
    else:
        print(" Error in Login Out ")
get_information()
log_out()

**Comment by madsmtm** [comment]
Should be fixed in #494, release `v1.9.0`
