### ISSUE TITLE
provide getFriendsList capability

### ISSUE THREAD

**Issue by dreamflasher** [carpedm20/fbchat#491]
Facebook-chat-api has: https://github.com/Schmavery/facebook-chat-api/blob/master/DOCS.md#getFriendsList

Would be great if you'd include that too, thank you!

**Comment by madsmtm** [comment]
This is already supported, it's just called `Client.fetchAllUsers` instead 😉

**Comment by dreamflasher** [comment]
I guess then the documentation is wrong ;) " fetchAllUsers() – Fetch all users the client is currently chatting with."

Does this give all friends or all people I have chatted with?

**Comment by madsmtm** [comment]
Hmm, well, it's not quite "all friends" as you'd see it under `https://www.facebook.com/XXX/friends`.

A few differences are as follows (but there's probably more):
- Only in friend list: Deactivated or memorialized accounts.
- Only in `fetchAllUsers`: Accounts that you're not friends with (but have chatted with before), or accounts that are "Messenger Only"

So really, it gives all the people you can chat with.

**Comment by madsmtm** [comment]
Linking #282, since it might be relevant
