### ISSUE TITLE
what about scraping

### ISSUE THREAD

**Issue by dr1214** [carpedm20/fbchat#493]
what about scraping
we need scarp uids from groups ,posts coments nd likes

**Comment by madsmtm** [comment]
Hi @dr1214, I'm not 100% sure what you mean, so I'm assuming you're asking whether you can fetch posts, comments and likes. To that, the answer is no, that's out of the scope for this project (it's called `fbCHAT` after all 😉).

Feel free to reopen and elaborate on your question if I didn't understand correctly!
