### ISSUE TITLE
Can't echo a message (with echobot)

### ISSUE THREAD

**Issue by HunterAzar** [carpedm20/fbchat#496]
Hello
I started the echobot (from examples) and Bot reads messages but does not reply to them

![IMG_20200108_170223](https://user-images.githubusercontent.com/26726236/71994244-b259ac00-3238-11ea-9d69-1cf80bea96f6.png)

**Comment by madsmtm** [comment]
Hi @HunterAzar, beware that the code on the `master` branch is not yet released, and as such, if you've taken your code from the examples in that branch, your code won't work.

Please use the code from [the examples on ReadTheDocs](https://fbchat.readthedocs.io/en/stable/examples.html#echobot).

**Comment by HunterAzar** [comment]
Ok 
Thanks
