### ISSUE TITLE
Can't login on old account

### ISSUE THREAD

**Issue by Callen93** [carpedm20/fbchat#500]
## I can't connect on one of my two account
I have two Facebook account, one which is fairly recent and one that's older. I can login with no problem on the recent one but get an error when login to old one 

## Code to reproduce
```py
from fbchat import Client
client = Client("old_account", "password")
```

## Traceback
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "fbchat/_client.py", line 77, in __init__
    self.login(email, password)
  File "fbchat/_client.py", line 174, in login
    email, password, on_2fa_callback=self.on_2fa_code
  File "fbchat/_state.py", line 152, in login
    "(Failed on url: {})".format(r.url)
FBchatException: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login/?cuid=[B64-URL string]&email=[EMAIL]&li=[CHARS]&e=1348060&refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr)

```

## Comparison to what happen on recent account
I noticed that when I enter the wrong password on my other account, I get the same kind of error
 ```
FBchatException: Login failed. Check email/password. (Failed on url: https://m.facebook.com/login/?email=[EMAIL]&li=[CHARS]&e=1348092&refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr)
```
The error code however is not the same AND the field Cuid is not present.

## Environment information
- Python3
- `fbchat` v2 master
## Question
Do you know so I can troubleshoot : 

- What's is CUID ?
- Can I find somewhere the correspondence between error code and error ?

**Comment by dundalkian** [comment]
Can you login to your old account via the normal facebook website? I've found that accounts that are clearly bots will get flagged by facebook and require additional info before they are reactivated.

**Comment by madsmtm** [comment]
Thanks for the report @Callen93!

To view the error message, simply visit the URL in your browser (in a private window). E.g. visit https://m.facebook.com/login/?e=1348092.

By doing this, I got:
```
1348060 -> You used an old password. If you have forgotten your current password, you can request a new one.
1348092 -> The password you entered is incorrect. Did you forget your password?
```

So perhaps you're simply just not entering your passwords correctly?

**Comment by Callen93** [comment]
Thanks !

Sorry for the inconvenience I indeed used an old password... This method to get info about error will probably be useful however.

Thanks, problem solved.

**Comment by madsmtm** [comment]
Yeah, it's something I just figured out, and it actually made me incorporate the error into the error message, see 6b39e58eb87567f6b950da690aee1c787126d6e6.

So when I release the next major version, you should be able to get the error message directly 😉
