### ISSUE TITLE
facebook account getting banned

### ISSUE THREAD

**Issue by ablaszkiewicz** [carpedm20/fbchat#504]
Description:
I have noticed that after a few days my accounts using fbchat are getting permanently banned on facebook. Is there some way to prevent this?

**Comment by MS-Jahan** [comment]
> Description:
> I have noticed that after a few days my accounts using fbchat are getting permanently banned on facebook. Is there some way to prevent this?

Use Two Step Authentication to prevent this. And don't do things like sending same message to a lot of people (if you're doing).

**Comment by madsmtm** [comment]
See #427, #187 and #477 for a lot of discussion regarding this (and other things).

The best advice I can give is to store and reuse session cookies, but if you're already doing that, then I don't know 😕

**Comment by ablaszkiewicz** [comment]
Thanks for answers and sorry for the question - later I realised that similar questions have been answered. I think cookies will help
