### ISSUE TITLE
Add "which message was seen" feature in onMessageSeen()

### ISSUE THREAD

**Issue by MS-Jahan** [carpedm20/fbchat#505]
I can't find any way to check which message was seen. It would be greater to add a "mid" like object or property (not too familiar with OPP ;-p ) so that actually which message was read can be found.

If there is already a way, please tell me.

**Comment by madsmtm** [comment]
It's been a while since I tinkered with this, but I think the method is wrongly named, perhaps it should have been called `onThreadSeen`, or something 😕.

Arguably, the documentation is very lacking on this point, but perhaps `onMessageDelivered` is what you're searching for?

**Comment by madsmtm** [comment]
Just checked, we don't receive data about which message is marked as seen, so I'll close this, since we can't fix this
