### ISSUE TITLE
[FIXED]listen not working anymore

### ISSUE THREAD

**Issue by thekindlyone** [carpedm20/fbchat#51]
The login works, I can send messages and retrieve friends, but receiving messages while listening is not firing the `on_message` method. Am I doing something wrong?

```
client = Client(username, password)
client.listen()
```

in `parseMessage` the `content` coming in is always `{u'reason': 110, u't': u'refresh', u'seq': 0}` and therefore `on_message` is never fired.

I googled a bit and I found https://github.com/defaultnamehere/zzzzz/issues/25  
Someone here thinks getting new cookies will help. 

**SOLUTION:** 

add `"clientid": self.client_id,` in the dict `data` in `Client._pullMessage` method in `client.py`

**Comment by lobstr** [comment]
Check issue #45, have you added that "clientid" line?

**Comment by thekindlyone** [comment]
oh. sweet. Added it.. it worked. Dunno how I missed that.
