### ISSUE TITLE
Make option to keep using cookies at all cost - even if logging in failed at first.

### ISSUE THREAD

**Issue by TheLastGimbus** [carpedm20/fbchat#514]
## Description
If your bot receives and sends a lot of messages, it is good to set up 2FA for it, so there's a lower chance that Facebook will take it down.
If you are running your bot automated, on Raspberry Pi or some other server, you need to use cookies at all cost, so you won't be required to manually type in 2FA code if internet/power goes down.
But fbchat invalidates cookies if logging in failed at first. So, if there was a temporary lack of internet, and it (automatically, through some cron job or something) tried to log in (even with `max_tries=10000000`), it will ignore cookies at next try and wait for 2FA code.

So, it would be nice to have some flag, like `force_cookies` to keep using cookies and re-try logging in with them.

**Comment by madsmtm** [comment]
I've changed the login flow quite a bit in `v2`, so it should be fixed there.

I probably won't add this feature for `v1`, I'd like to keep changes minimal, but if it's really needed, I can be persuaded otherwise 😉
