### ISSUE TITLE
MQTT error 

### ISSUE THREAD

**Issue by h4o** [carpedm20/fbchat#516]
## Description of the problem
When there is a connection error (not sure if disonnected or a login issue) I get a connection in the logs from which the client cannot recover.
## Code to reproduce
The base client should do the trick
```py
from fbchat import Client
client = Client("[REDACTED_USERNAME]", "a_password_with_%")
```

## Traceback
```
Connection error, retrying
MQTT error code ERROR_QUEUE_NOT_FOUND received
Connection error, retrying
MQTT error code ERROR_QUEUE_NOT_FOUND received

```

## Environment information
- Python version 3.4
- `fbchat` version 

## Additional comments
The client seems to work for ~48h then fail, it might be linked to a duration of a token or the stability of my connection.
Is there a way to catch this error and force a new login?

**Comment by madsmtm** [comment]
Haha, just found this issue as well, and released a fix, see b4618739f30d9f227070c140297406fa746f78da, version `v1.9.6`.

Thanks for the report though 😁
