### ISSUE TITLE
[Question] Is there a way to make all the logs go to one file that I designate?

### ISSUE THREAD

**Issue by syspic** [carpedm20/fbchat#523]
Question in title. I essentially want to log all the `on_....` commands, mostly the `on_message` , to a file. However I see the way to do this has changed. It is no longer making a subclass of Client so I will have to re learn this :'(

**Comment by madsmtm** [comment]
Hmm, the new version shouldn't be released yet, so it shouldn't be a problem; just use the version on PyPI / the `v1` branch; however, I'll make an issue soon asking for feedback on how the API should work in the future, so when that comes, I'll link to this issue, thanks!

**Comment by madsmtm** [comment]
Oh, and regarding your specific question, see the examples for how I've currently designed the listening system; under that design (which _will_ change), you would do:
```python
import fbchat
session = fbchat.Session.login(...)
listener = fbchat.Listener.connect(session, True, True)
for event in listener.listen():
    if isinstance(event, fbchat.MessageEvent):
        with open('file.log', 'a') as f:
            f.write(event.message.text)
```

**Comment by syspic** [comment]
Thank you so much for the response! I've notices you get back the people super quickly and I appreciate that 

Oh ok, I see. I was looking at master by accident

As for the listener in v2, is that where all the `on..` methods will go now?

**Comment by madsmtm** [comment]
Yup, that's where I'll move it. Ideally, I'd like the following to work:
```python
import fbchat
session = fbchat.Session.login(...)
listener = fbchat.Listener(session, True, True)

@listener.register
def on_message(message: fbchat.Message):
    with open('file.log', 'a') as f:
        f.write(message.text)

listener.run()
```

But I'm not quite there yet.

I'll close this issue for now though, if you don't mind 😉

**Comment by madsmtm** [comment]
I've made the issue asking for feedback, #526, kindly submit your thoughts! 😃
