### ISSUE TITLE
example not working

### ISSUE THREAD

**Issue by danhimalplanet** [carpedm20/fbchat#525]
I'm trying basic usage example
https://github.com/carpedm20/fbchat/blob/master/examples/basic_usage.py#L4

    $ pip install fbchat
    ...
    Successfully uninstalled fbchat-1.9.6
    $ python3
    Python 3.6.9 (default, Nov  7 2019, 10:44:02)
    [GCC 8.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import fbchat
    >>> session = fbchat.Session.login("<email>", "<password>")
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    AttributeError: module 'fbchat' has no attribute 'Session'

**Comment by madsmtm** [comment]
Please see the examples on the [`v1` branch](https://github.com/carpedm20/fbchat/tree/v1/examples), or on [ReadTheDocs](https://fbchat.readthedocs.io/en/stable/examples.html).

The examples on the `master` branch is for the new, still unreleased version 😉
