### ISSUE TITLE
how to listen to group messaging?

### ISSUE THREAD

**Issue by danielcovaci** [carpedm20/fbchat#529]
hello guys, 
im new to python and fbchat
can someone show an example with client.listen() to group messaging and make a loop if the messsage = "end of the world" do something ....
im trying to make a facebook group bot that act like old trivia bot

**Comment by madsmtm** [comment]
Have a look at the [`EchoBot` example](https://fbchat.readthedocs.io/en/stable/examples.html#echobot).

I've rewritten it a bit below to match your requirements:
```python
import fbchat
from fbchat.models import *

# Subclass fbchat.Client and override required methods
class EchoBot(fbchat.Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        # Works with both groups and user chats, if you want only groups, check `thread_type is ThreadType.GROUP`
        print("{} from {}".format(message_object, thread_id))
        # If the message matches
        if message_object.text == "end of the world":
            # Do something, e.g. send a message back
            self.send(Message(text="Oh no!"), thread_id=thread_id, thread_type=thread_type)

bot = EchoBot("<email>", "<password>")
bot.listen()
```

Hope this could be of any help. If you have further questions, feel free to ask!

**Comment by danielcovaci** [comment]
sory for late reply, 
10q madsmtm for this code, it works :)) vscode looks like christmass tree (36 problems found) but the code works 
now you have to teach me how to loop trough a list of questions and pull a random question :)

**Comment by danielcovaci** [comment]
@madsmtm please help
im trying to pass this string > 100000481613163 9 100001018323774 1 bobonete 1 edi 1 jon 1 wich represents the score [(100000481613163, 9), (100001018323774, 1), (bobonete, 1) (edi, 1), (jon, 1)] 
`into self.send(Message(text=topten), thread_id=thread_id, thread_type=thread_type)`
i get this error:
`Exception in parsing of {
'deltas': [{'attachments': [], 
'body': 'clasament', 
'irisSeqId': '517', 
'irisTags': ['DeltaNewMessage', 'is_from_iris_fanout'], 'messageMetadata': {'actorFbId': '100000481613163', 'folderId': {'systemFolderId': 'INBOX'}, 'messageId': 'mid.$gAAvS3zJNCbd3NRdQU1xA9IH5FkHw', 'offlineThreadingId': '6647581889065796080', 'skipBumpThread': False, 'tags': ['source:chat:light_speed', 'app_id:437626316973788'], 'threadKey': {'threadFbId': '3328080807266743'}, 'threadReadStateEffect': 'MARK_UNREAD', 'timestamp': '1584907028563'}, 'participants': ['100000481613163', '100015080057521', '100001018323774'], 'requestContext': {'apiArgs': {}}, 'tqSeqId': '373', 'class': 'NewMessage'}], 'firstDeltaSeqId': 517, 'lastIssuedSeqId': 517, 'queueEntityId': 100015080057521}
Traceback (most recent call last):
  File "C:\Users\benga\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fbchat\_client.py", line 2820, in _parse_message       
    self._parse_payload(topic, data)
  File "C:\Users\benga\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fbchat\_client.py", line 2758, in _parse_payload       
    self._parseDelta(delta)
  File "C:\Users\benga\AppData\Local\Programs\Python\Python38-32\lib\site-packages\fbchat\_client.py", line 2722, in _parseDelta
    self.onMessage(
  File "c:/Users/benga/Dropbox/python/echoandchatu.py", line 101, in onMessage
    cursor = cnx.cursor()
  File "C:\Users\benga\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mysql\connector\connection.py", line 916, in cursor    
    raise errors.OperationalError("MySQL Connection not available.")
mysql.connector.errors.OperationalError: MySQL Connection not available.
Messages seen by 100000481613163 in 3328080807266743 (GROUP) at 1584907028.622s`

**Comment by HunterAzar** [comment]
You have problem with mysql.connector on line 101
Can you send some lines of code?

**Comment by danielcovaci** [comment]
here is the code:
`import fbchat
from fbchat.models import *
from mysql.connector import connect  


# Subclass fbchat.Client and override required methods
class EchoBot(fbchat.Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        # Works with both groups and user chats, if you want only groups, check `thread_type is ThreadType.GROUP`
        print("{} from {}".format(message_object, thread_id))
        
        cnx = connect(user='root', password='', host='localhost', database='chat')

        print('Attempting to connect to the database...')

        if cnx.is_connected():
            print("Connection to the database established successfully")

        
        #verifica daca este intrebare fara raspuns
        cursor = cnx.cursor()
        checkIntrebare = ("select asked.id, intrebari.intrebare, intrebari.raspuns from asked inner join intrebari on asked.id_intrebare=intrebari.id where asked.nickname is null limit 1")
        cursor.execute(checkIntrebare)
        result = cursor.fetchall()

        if cursor.rowcount:

        #daca este afiseaza intrebarea
            for row in result:
                idIntrebare = int(row[0])
                intrebare = row[1]
                raspuns = row[2]
                
                cursor.close()
            
        else:
        #daca nu este ... add random  
            #    print ("No results found")
            #add random intrebare
            cursor = cnx.cursor()

            addIntrebare = ("select * from intrebari order by rand() limit 1") 

            cursor.execute(addIntrebare)
            result = cursor.fetchall()
            for row in result:
                idIntrebare = int(row[0])
                intrebare = row[1]
                raspuns = row[2]

            cursor.close()

            #insert intrebare
            cursor = cnx.cursor()

            askIntrebare = ("insert into asked (id_intrebare) values (%s)")
            cursor.execute(askIntrebare, (idIntrebare,))
            # Make sure data is committed to the database
            cnx.commit()
            idIntrebare = cursor.lastrowid
            cursor.close()

        cnx.close()
        print("MySQL connection is closed")   
        print("id intrebare: ", idIntrebare, " / intrebare: " ,intrebare, " / raspuns: ", raspuns)
        
        # If the message matches

        if message_object.text == "intrebare":
            # Do something, e.g. send a message back

            self.send(Message(text=intrebare), thread_id=thread_id, thread_type=thread_type)

        if message_object.text == raspuns:
            # Do something, e.g. send a message back
            self.send(Message(text="raspuns corect!"), thread_id=thread_id, thread_type=thread_type) 

            print ("id>>>", author_id, "id intrebare>>>", idIntrebare)

            cnx = connect(user='root', password='', host='localhost', database='chat')

            print('2. Attempting to connect to the database...')

            if cnx.is_connected():
                print("2. Connection to the database established successfully")
          
            #update intrebare
            cursor = cnx.cursor()

            updateIntrebare = ("update asked set nickname=(%s) where id=(%s)")
            
            cursor.execute(updateIntrebare, (author_id, idIntrebare,))
            # Make sure data is committed to the database
            cnx.commit()
            cursor.close()

            cnx.close()
 
        if message_object.text == "clasament":
            #show clasament
            cursor = cnx.cursor()

            clasament = ("select nickname, count(nickname) as corect from asked where nickname is not null group by nickname limit 10") 

            cursor.execute(clasament)
            result = cursor.fetchall()
            list = []
            for row in result:
                nickname = row[0]
                scor = row[1]
                jucator = nickname, str(scor)
                list.append(jucator)
            
            cursor.close()
            cnx.close()
            
            topten = list 

            self.send(Message(text=topten), thread_id=thread_id, thread_type=thread_type)

        if message_object.text == "wake up":
            
            self.send(Message(text="m-am trezit!"), thread_id=thread_id, thread_type=thread_type)     
               

bot = EchoBot(xxxx@yahoo.com", "nxxx020")
bot.listen()`

**Comment by danielcovaci** [comment]
here is the code:
              `import fbchat
from fbchat.models import *
from mysql.connector import connect  


# Subclass fbchat.Client and override required methods
class EchoBot(fbchat.Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        # Works with both groups and user chats, if you want only groups, check `thread_type is ThreadType.GROUP`
        print("{} from {}".format(message_object, thread_id))
        
        cnx = connect(user='root', password='', host='localhost', database='chat')

        print('Attempting to connect to the database...')

        if cnx.is_connected():
            print("Connection to the database established successfully")

        
        #verifica daca este intrebare fara raspuns
        cursor = cnx.cursor()
        checkIntrebare = ("select asked.id, intrebari.intrebare, intrebari.raspuns from asked inner join intrebari on asked.id_intrebare=intrebari.id where asked.nickname is null limit 1")
        cursor.execute(checkIntrebare)
        result = cursor.fetchall()

        if cursor.rowcount:

        #daca este afiseaza intrebarea
            for row in result:
                idIntrebare = int(row[0])
                intrebare = row[1]
                raspuns = row[2]
                
                cursor.close()
            
        else:
        #daca nu este ... add random  
            #    print ("No results found")
            #add random intrebare
            cursor = cnx.cursor()

            addIntrebare = ("select * from intrebari order by rand() limit 1") 

            cursor.execute(addIntrebare)
            result = cursor.fetchall()
            for row in result:
                idIntrebare = int(row[0])
                intrebare = row[1]
                raspuns = row[2]

            cursor.close()

            #insert intrebare
            cursor = cnx.cursor()

            askIntrebare = ("insert into asked (id_intrebare) values (%s)")
            cursor.execute(askIntrebare, (idIntrebare,))
            # Make sure data is committed to the database
            cnx.commit()
            idIntrebare = cursor.lastrowid
            cursor.close()

        cnx.close()
        print("MySQL connection is closed")   
        print("id intrebare: ", idIntrebare, " / intrebare: " ,intrebare, " / raspuns: ", raspuns)
        
        # If the message matches

        if message_object.text == "intrebare":
            # Do something, e.g. send a message back

            self.send(Message(text=intrebare), thread_id=thread_id, thread_type=thread_type)

        if message_object.text == raspuns:
            # Do something, e.g. send a message back
            self.send(Message(text="raspuns corect!"), thread_id=thread_id, thread_type=thread_type) 

            print ("id>>>", author_id, "id intrebare>>>", idIntrebare)

            cnx = connect(user='root', password='', host='localhost', database='chat')

            print('2. Attempting to connect to the database...')

            if cnx.is_connected():
                print("2. Connection to the database established successfully")
          
            #update intrebare
            cursor = cnx.cursor()

            updateIntrebare = ("update asked set nickname=(%s) where id=(%s)")
            
            cursor.execute(updateIntrebare, (author_id, idIntrebare,))
            # Make sure data is committed to the database
            cnx.commit()
            cursor.close()

            cnx.close()
 
        if message_object.text == "clasament":
            #show clasament
            cursor = cnx.cursor()

            clasament = ("select nickname, count(nickname) as corect from asked where nickname is not null group by nickname limit 10") 

            cursor.execute(clasament)
            result = cursor.fetchall()
            list = []
            for row in result:
                nickname = row[0]
                scor = row[1]
                jucator = nickname, str(scor)
                list.append(jucator)
            
            cursor.close()
            cnx.close()
            
            topten = list 

            self.send(Message(text=topten), thread_id=thread_id, thread_type=thread_type)

        if message_object.text == "wake up":
            
            self.send(Message(text="m-am trezit!"), thread_id=thread_id, thread_type=thread_type)     
               

bot = EchoBot("mxxxxy@yahoo.com", "naxxxx2020")
bot.listen()`

**Comment by HunterAzar** [comment]
Use this
```
cnx = mysql.connector.connect(args)
```

**Comment by HunterAzar** [comment]
Close if code is working 🙂

**Comment by danielcovaci** [comment]
now i get
`undefined variable 'mysql'`

**Comment by HunterAzar** [comment]
Change 
```
From mysql.connector import connect
```
To
```
Import mysql.connector
```

**Comment by danielcovaci** [comment]
i have forgoten `cnx = connect()`
