### ISSUE TITLE
Session files not uploading

### ISSUE THREAD

**Issue by barci2** [carpedm20/fbchat#530]
When using session._upload method, HTTPError: Connection error is thrown. This happens because of bug in method _post called from _payload_post called from said method, where "https://www.facebook.com" is added at the end of https://upload.facebook.com/ajax/mercury/upload.php . A quick fix is to change the line in method _post from:
r = self._session.post(prefix_url(url), data=data, files=files)
to:
r = self._session.post(prefix_url(url) if not url.startswith("https://upload.") else url, data=data, files=files)

**Comment by madsmtm** [comment]
Thanks for the report, I'll fix it at some point, for now, you should probably just use the supported version on the `v1` branch 😉

**Comment by madsmtm** [comment]
Fix in 6660fd099d9df665ab58e3ee9cb33ca3a252d298, I've also moved `Session._upload` to `Client.upload`
