### ISSUE TITLE
How to print/ log while listening?

### ISSUE THREAD

**Issue by rocketLeagueTraderJoe** [carpedm20/fbchat#531]
I feel like the answer is going to be super simple and straightforward, but I'm stumped and can't figure how to do this. Let me explain:

If I run my bot from a terminal, I get all my print messages, and if I set the proper logging level I can see the logs as they occur.

I want the bot to start on reboot, so I added it as a service to systemd. So now it starts automatically, but I can also start and stop it. And I also have the standard output and error write to a file.

Issue is that I'm not seeing any of the printed messages being written to the file while listening like this. For example, if I have this where client is commented out: 
`print("Starting Client...")`
`client = fbBot(email=email, password=password, session_cookies=cookie)`
`#client.listen()`

That print message will output to the file, as expected. But if I use `client.listen()`, then I don't get anything in my file at all (even though it supposedly prints before `client.listen`). There are also several print messages during some of the "on" methods too but none of them show while listening. What's could the reasoning behind this be? Am I misunderstanding how outputting to a file works or something?

**Comment by madsmtm** [comment]
Hmm, perhaps it's got something to do with output buffering, can you try following the steps in [here](https://stackoverflow.com/a/230774), or similar? That is, changing the print statement to `print("Starting Client...", flush=True)`

**Comment by rocketLeagueTraderJoe** [comment]
Awesome, it works! I had no idea about flush; Now I can change all my log.warnings back to prints instead, and only listen for errors. Thanks!
