### ISSUE TITLE
Add donations for this project

### ISSUE THREAD

**Issue by TheLastGimbus** [carpedm20/fbchat#533]
## Description
I've been playing with this library for some time, and it gave me so many awesome opportunities that I've never even thought of before. You guys (aspecially - but not only - @madsmtm <3 ) did so much of such a great work.
Please add some donation options, github sponsors for example. I would love to buy you a coffe <3

**Comment by madsmtm** [comment]
Thanks a lot for your kind words, @TheLastGimbus!

However, I probably won't follow your proposal. I don't really want to accept money for working on this project, it'll make it feel more like a job, and with that comes obligations, burnout and other bad stuff.
I like having this as a hobby project, something I can work on when I feel like it, but also something I could abandon forever the next second, should I feel the need (I probably won't 😉).

I hope you understand these concerns, and that I don't mean them as a dismissal of your gratitude. Again, I really appreciate the kind words and intentions, thanks! 🙏

**Comment by TheLastGimbus** [comment]
You're totally right. That's very reasonable...
