### ISSUE TITLE
Trigger event on reconnect

### ISSUE THREAD

**Issue by Alexis211** [carpedm20/fbchat#536]
I'm building a Messenger bridge for Matrix using the fbchat library, and I don't want to miss any messages from my friends. However sometimes when my internet connection breaks, the bridge does not receive events during some time. I already have a room sync procedure that retreives all of the new messages in a room since last time, which is run when the bridge starts. However, I'd also like to run this sync when the fbchat listener reconnects, so that any events that happenned when the connection was broken can be recuperated automatically. Is there currently a way of doing this, or is such a feature planned?

Thanks

**Comment by madsmtm** [comment]
I have added this event in alpha release `v2.0.0a2`, as `fbchat.Connect` and `fbchat.Disconnect`, so when `v2` is released, you'll be able to do this. Thanks for the request! 👍
