### ISSUE TITLE
Threaded Listening within Client Class

### ISSUE THREAD

**Issue by papagm** [carpedm20/fbchat#538]
I'm writing up a program that allows clients to send messages and interact with fb chat via input. I want to be able to listen() and run onMessage() in the background (in a different thread), while also interacting in my 'interactiveMode' loop, but i can't seem to get the threads to work how i thought they would.
My code at the moment inside my Bot(Client) class:

    def onMessage(self, author_id=None, message_object=None, thread_id=None,
                  thread_type=ThreadType.USER, **kwargs):

        print("new message received!")

    def interactiveMode(self):
            listenerThread = threading.Thread(target=self.listen())
            listenerThread.start()

            while 1: 
              # ... <code here>...
at the moment after I initialise the client and run client.interactiveMode(), the rest of interactiveMode code after the threading for self.listen() never runs and i'm stuck in self.listen(). my interactiveMode function works as expected by itself, however i would like the additional feature of printing to terminal when a new message comes in. Thanks!

**Comment by madsmtm** [comment]
Your error is probably in `threading.Thread(target=self.listen())` - it should be `threading.Thread(target=self.listen)` (without parentheses).

But I must warn you that `fbchat` is _not_ thread safe!!! All sorts of wierd stuff can happen if you try this, so beware: You're on your own if you do this, the functionality you're trying to implement is not supported!

**Comment by papagm** [comment]
Ah lol, stupid mistake on my part! All good, thanks for the help

**Comment by madsmtm** [comment]
No problem 👍
