### ISSUE TITLE
fbchat._exception.FBchatFacebookError: Error when sending request: Got 404 response. This is either because you specified an invalid URL, or because you provided an invalid id (Facebook usually requires integer ids).

### ISSUE THREAD

**Issue by kattstof** [carpedm20/fbchat#539]
login successful but when it starts to listeb it throws this error (using the removebot example)
fbchat._exception.FBchatFacebookError: Error when sending request: Got 404 response. This is either because you specified an invalid URL, or because you provided an invalid id (Facebook usually requires integer ids).

**Comment by madsmtm** [comment]
Hmm, I can't reproduce. Are you using the example on the `master` branch or on the `v1` branch?

And could you try enabling debug logging by putting the following at the top of your file and try again?
```python
import logging
logging.basicConfig(level=logging.DEBUG)
```

Sorry for the late response 🙄

**Comment by kattstof** [comment]
Ended up being my environment for some odd reason , a fresh reinstall made it work, no idea why my enviroment caused it to screw u.
