### ISSUE TITLE
getUsers() by Facebook link

### ISSUE THREAD

**Issue by MarioCroSite** [carpedm20/fbchat#54]
Now this work with Friend name but it is possible to work with facebook link and how.

```
friends = client.getUsers("FRIEND'S NAME")  # return a list of names
friend = friends[0]
sent = client.send(friend.uid, "Your Message")
```

for example like this.

```
friends = client.getUsers("https://www.facebook.com/MyProfile")  # return a User_Id
friend = friends[0]
sent = client.send(friend.uid, "Your Message")
```

**Comment by thekindlyone** [comment]
@MarioCroSite if you get the MyProfile bit out of "https://www.facebook.com/<MyProfile>" and run clinet.getUsers('<MyProfile>'), it is working for 100% of all cases I tested. Does it not work for you?

**Comment by madsmtm** [comment]
Assuming ^ fixed this
