### ISSUE TITLE
Error in Fetching information example (doc)

### ISSUE THREAD

**Issue by Benjamin-Loison** [carpedm20/fbchat#540]
Instead of:

images = client.fetchThreadImages("<thread id>")
for image in islice(image, 20):
    print(image.large_preview_url)

It should be "images" instead of "image" in https://fbchat.readthedocs.io/en/stable/intro.html#fetching-information

for image in islice(images, 20):

**Comment by madsmtm** [comment]
Nicely spotted! Do you want to make a PR to the `v1` branch, fixing it in the file [`examples/fetch.py`](https://github.com/carpedm20/fbchat/blob/v1/examples/fetch.py)?

**Comment by Benjamin-Loison** [comment]
Thanks, in fact it is my first one ^^.

Have I done it well ? https://github.com/carpedm20/fbchat/pull/547

**Comment by madsmtm** [comment]
You've done great 😉. I'll close this 👍
