### ISSUE TITLE
How to send messages while listening

### ISSUE THREAD

**Issue by Morpny-kun** [carpedm20/fbchat#543]
First of all sorry for such a noob question, I am not very familiar to fbchat library or python in general. I am trying to make a chat bot so I started experimenting with the Echobot example but when I want to send certain responses to specific messages instead of just echoing the message back, it gives me as Message not defined error. Is their a different way of sending messages while listening?

`class EchoBot(Client):
    def onMessage(self, author_id, message_object, thread_id, thread_type, **kwargs):
        self.markAsDelivered(thread_id, message_object.uid)
        self.markAsRead(thread_id)

        log.info("{} from {} in {}".format(message_object, thread_id, thread_type.name))

        # If you're not the author, echo
        if author_id != self.uid:
            if message_object.text == "sleepnow":
                self.send(Message(text="Going to sleep"), thread_id=thread_id, thread_type=thread_type)    
                sleep(2)
                self.stopListening()
                # self.logout

            else:
                self.send(message_object, thread_id=thread_id, thread_type=thread_type)
                print("I will print message_object now")
                print(message_object)
                print(type(message_object))`

![Screenshot from 2020-04-04 08-10-40](https://user-images.githubusercontent.com/44739457/78417546-95bcec80-764c-11ea-9ca7-fd2a1070ec31.png)

When I run this and message the bot "sleepnow" is give me this error:
`Traceback (most recent call last):
  File "/home/morphi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2820, in _parse_message
    self._parse_payload(topic, data)
  File "/home/morphi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2758, in _parse_payload
    self._parseDelta(delta)
  File "/home/morphi/.local/lib/python3.6/site-packages/fbchat/_client.py", line 2737, in _parseDelta
    msg=delta,
  File "/home/morphi/Projects/PyProjects/Messenger bot/echobot.py", line 32, in onMessage
    self.send(Message(text="Going to sleep"), thread_id=thread_id, thread_type=thread_type)
NameError: name 'Message' is not defined
Marked messages as seen in threads [('100026733585515', 'USER')] at 1585970386.489s`

**Comment by kapi2289** [comment]
You need to import the `Message` model first.
```python
from fbchat.models import Message
```

**Comment by Morpny-kun** [comment]
Thanks a lot, it worked. I feel really stupid now after I checked the other examples saw that the echobot example code didn't have this line:
 `from fbchat.models import *`

Thanks a bunch, ( > w< )/
