### ISSUE TITLE
new facebook api - FIXED !!!

### ISSUE THREAD

**Issue by Kobito123** [carpedm20/fbchat#55]
Hey guys, I use fbchat for a couple of weeks now and everything worked fine.

 But since 23h I can't send any msg :/

import fbchat
client = fbchat.Client("....", ".....")
sent = client.send(100001986531748, "test123")
if sent:
    print("Message sent successfully!")
print("nope! test")

In cmd:

D:\Spiele\TEST>python test.py
Logging in...
nope! test

When loggin in the fbacc, I can msg everyone without a problem. Furthermore I can get the last messages sent without a problem

Any ideas ? Sorry I am new to python

thx in advance <3

**Comment by chrisjohneder** [comment]
getting the same problem..log in is ok but when sending message im just getting False response

**Comment by Schmavery** [comment]
Hey guys, our api just died too because facebook changed their endpoint for sending messages.  Feel free to check out [this](https://github.com/Schmavery/facebook-chat-api/issues/311#issuecomment-240293830) for a fix.

**Comment by Kobito123** [comment]
thx alot =)

**Comment by gbip** [comment]
Can youd be more precise @Schmavery please ?
I have the same issue. Tried what you said, didn't work.
Thanks !

**Comment by Schmavery** [comment]
Sorry guys, I don't actually work on the python version of this api, I was just trying to give some relevant tips.  A good rule of thumb is to try the operation in a browser and compare the request that gets sent there to the one that the api is sending :smile: good luck!

**Comment by Kobito123** [comment]
thx alot for the help @Schmavery  <3

**Comment by gbip** [comment]
@Kobito123 did you solved it ? I tried fixing it by following what has been done on the javascript version of the API, but i can't make it work...

**Comment by Kobito123** [comment]
@gbip  not yet :/

**Comment by chrisjohneder** [comment]
how about these? it seems it's working but could not implement on client.py

https://m.facebook.com/messages/compose?ids=
https://m.facebook.com/messages/send/?icm=1

**Comment by Kobito123** [comment]
Did anyone fix it ? :)

**Comment by stefanhdao** [comment]
Any updates on this? I've been trying to edit the CLient myself but not a whole lot of luck to get it working.

**Comment by thekindlyone** [comment]
I tried to replicate the js version commits that made it work again. 404. :(

How do you get error logs on this.. like the js project has?

**Comment by stefanhdao** [comment]
I'm not sure but I was just printing out the response and it just says we're hitting an invalid page. Maybe there is a setting that we are not sending that the js version does.

**Comment by thekindlyone** [comment]
```
 { client: 'mercury',
  action_type: 'ma-type:user-generated-message',
  author: 'fbid:100010359372619',
  timestamp: 1471400345995,
  timestamp_absolute: 'Today',
  timestamp_relative: '4:19',
  timestamp_time_passed: '0',
  is_unread: false,
  is_cleared: false,
  is_forward: false,
  is_filtered_content: false,
  is_filtered_content_bh: false,
  is_filtered_content_account: false,
  is_filtered_content_quasar: false,
  is_filtered_content_invalid_app: false,
  is_spoof_warning: false,
  source: 'source:chat:web',
  'source_tags[0]': 'source:chat',
  body: 'TEST BOT: aaf',
  html_body: false,
  ui_push_phase: 'V3',
  status: '0',
  offline_threading_id: '6171500356804827443',
  message_id: '6171500356804827443',
  threading_id: '<1471400345996:3042699249-3e565cdb@mail.projektitan.com>',
  'ephemeral_ttl_mode:': '0',
  manual_retry_cnt: '0',
  has_attachment: false,
  signatureID: '7ed6ba49',
  'specific_to_list[0]': 'fbid:100000121491279',
  'specific_to_list[1]': 'fbid:100010359372619',
  'other_user_fbid': '100000121491279' }
```

This is a sample working payload(from a comment in the js project)
@stefanhdao  Do you know why there are quotes in some keys and not in others?

**Comment by stefanhdao** [comment]
I didn't notice that, this is what their code looks like. Let me do a little more digging.

`    var form = {
      'client' : 'mercury',
      'action_type' : 'ma-type:user-generated-message',
      'author' : 'fbid:' + ctx.userID,
      'timestamp' : Date.now(),
      'timestamp_absolute' : 'Today',
      'timestamp_relative' : utils.generateTimestampRelative(),
      'timestamp_time_passed' : '0',
      'is_unread' : false,
      'is_cleared' : false,
      'is_forward' : false,
      'is_filtered_content' : false,
      'is_filtered_content_bh':false,
      'is_filtered_content_account':false,
      'is_filtered_content_quasar':false,
      'is_filtered_content_invalid_app':false,
      'is_spoof_warning' : false,
      'source' : 'source:chat:web',
      'source_tags[0]' : 'source:chat',
      'body' : msg.body ? msg.body.toString() : "",
      'html_body' : false,
      'ui_push_phase' : 'V3',
      'status' : '0',
      'offline_threading_id' : messageAndOTID,
      'message_id' : messageAndOTID,
      'threading_id': utils.generateThreadingID(ctx.clientID),
      'ephemeral_ttl_mode:': '0',
      'manual_retry_cnt' : '0',
      'has_attachment' : !!(msg.attachment || msg.url || msg.sticker),
      'signatureID' : utils.getSignatureID(),
    };
`

**Comment by thekindlyone** [comment]
I fixed it! Wait. lemme send a pull request.

**Comment by thekindlyone** [comment]
@stefanhdao check PR

**Comment by Kobito123** [comment]
thx =) but I sadly get : 


D:\Spiele\TEST>python t.py
Traceback (most recent call last):
  File "t.py", line 1, in <module>
    import fbchat
  File "C:\Users\kobito\AppData\Local\Programs\Python\Python35\lib\site-packages\fbchat\__init__.py", line 14, in <module>
    from .client import *
  File "C:\Users\kobito\AppData\Local\Programs\Python\Python35\lib\site-packages\fbchat\client.py", line 304
    print r
          ^
SyntaxError: Missing parentheses in call to 'print'




Client.py :(line 297+)           
 

 except KeyError:
                # if user doesn't enter l or m or s, then use the large one
                sticker = LIKES['l']
            data["message_batch[0][sticker_id]"] = sticker

        r = self._post(SendURL, data)
        if self.debug:
             print r
             for k,v in data.iteritems():
                  print k,':',v
        return r.ok

how can I highlight the code like u guys all did ? sry I am really new to all of this :C thx in advance

**Comment by chrisjohneder** [comment]
working again thanks

**Comment by Bravo111** [comment]
And how to send images and files now?

**Comment by thekindlyone** [comment]
@Bravo111 check #56 .. fixed image sending problem. Forgot to do the api change fixes for images. Also added example in readme.
Basically 
```
    client.sendLocalImage(friend.uid,message='<message text>',image='<path/to/image/file>') # send local image
    imgurl = "http://i.imgur.com/LDQ2ITV.jpg"
    client.sendRemoteImage(friend.uid,message='<message text>', image=imgurl) # send image from image url
```

**Comment by Bravo111** [comment]
Thank you, @thekindlyone. Could you also answer, how can I recieve images and stickers with api?

**Comment by thekindlyone** [comment]
@Bravo111 , I don't think it is working at the moment. Open a new issue will you?

**Comment by thekindlyone** [comment]
@Bravo111 check #61. It should solve your issue.
