### ISSUE TITLE
Error while echo message that have image

### ISSUE THREAD

**Issue by HazzazBinFaiz** [carpedm20/fbchat#560]
I have followed code that given at the documentation for Echobot. (v1.9.6)

But it throws this exception when i send an image : 

`fbchat._exception.FBchatFacebookError: Error when sending request: Got 500 response.`

**Comment by madsmtm** [comment]
Yeah, this is kinda a known issue.
The way to fix it is to either not attempt to echo images/files, or to download the images/files locally, upload it to Facebook again, and then send the message again.

In `v2`, I simply changed the example so it only echoes the message text, and echoing images is "left as an exercise for the reader".

**Comment by madsmtm** [comment]
If it's okay, I'll close this issue, since it's really an error with the example, and that part is "fixed" in `v2`
