### ISSUE TITLE
AttributeError: module 'fbchat' has no attribute 'Session'

### ISSUE THREAD

**Issue by Tantol** [carpedm20/fbchat#566]
## Description of the problem
AttributeError: module 'fbchat' has no attribute 'Session'

## Code to reproduce
```py
import fbchat

# Log the user in
session = fbchat.Session.login("..., "...")

print("Own id: {}".format(session.user.id))

# Send a message to yourself
session.user.send_text("Hi me!")

# Log the user out
session.logout()

```

## Traceback
```
Traceback (most recent call last):
  File "send.py", line 4, in <module>
    session = fbchat.Session.login("..., "...")
AttributeError: module 'fbchat' has no attribute 'Session'

```

## Environment information
- Python 3
- `fbchat` version newest

**Comment by smilexs4** [comment]
Are you sure that the fbchat version is the newest? `pip install fbchat` installs an older version. In this case you should uninstall it, download the .zip and install that.

**Comment by Tantol** [comment]
> Are you sure that the fbchat version is the newest? `pip install fbchat` installs an older version. In this case you should uninstall it, download the .zip and install that.

Yes I probably have old version (installed by pip).

Thanks I will reinstall from source.

**Comment by 403error403** [comment]
Can you say how to uninstall older version and install the newest version??

**Comment by smilexs4** [comment]
`pip uninstall fbchat` or `pip3 uninstall fbchat` should remove the old version. 

Download the latest version with `git clone https://github.com/carpedm20/fbchat`

Go into the directory with `cd fbchat` and install it with `pip3 install fbchat . ` (make sure the dot is at the and).

**Comment by Tantol** [comment]
`pip install git+https://github.com/carpedm20/fbchat.git`

**Comment by TarunGunampalli** [comment]
I have the same issue but reinstalling directly from git didn't solve it. I still have the exact same error. What can I do now?

**Comment by smilexs4** [comment]
Make sure to download using `git clone https://github.com/carpedm20/fbchat` and install it from the directory instead of installing it directly from git with `pip install git+https://github.com/carpedm20/fbchat.git`.

**Comment by TarunGunampalli** [comment]
I used git clone, it does the same thing. Have you tried it very recently? Just asking since your last reply was a few months ago.

**Comment by smilexs4** [comment]
Try `pip3 install git+https://github.com/carpedm20/fbchat.git` it works for me on windows.

**Comment by 403error403** [comment]
Hello Sir. Can you help me to make a fb chat bot? I am facing some minor
problems but I can't solve these. I need a brief resource also. Please help
me. Thanks in advance.😊
