### ISSUE TITLE
Reply specificly 

### ISSUE THREAD

**Issue by 403error403** [carpedm20/fbchat#570]
We can reply any message specificly in messenger by swiping the message. Thus we can indicate - we are replying of which message. How can it be done in fbchat?

**Comment by wetmore** [comment]
Use the `reply_to_id` argument when calling `send_text` on a thread object. See https://github.com/carpedm20/fbchat/blob/master/fbchat/_threads/_abc.py#L102

Example:
```
import fbchat

session = fbchat.Session.login("<email>", "<password>")
listener = fbchat.Listener(session=session, chat_on=False, foreground=False)

for event in listener.listen():
    if isinstance(event, fbchat.MessageEvent):
        if event.author.id != session.user.id:
            event.thread.send_text(event.message.text, reply_to_id=event.message.id)
```

**Comment by madsmtm** [comment]
@wetmore's answer is correct. This can also be seen in the [documentation for `send_text`](https://fbchat.readthedocs.io/en/v2.0.0a3/api/threads.html?highlight=send_text#fbchat.ThreadABC.send_text). I've added an extra example for this in 65b42e65323de2fedeb424792e9511fdb0e7bf66.

If you're using `v1`, you would do this using `Message.reply_to_id`:
```python
client.send(fbchat.Message("text", reply_to_id=message_id), thread_id=thread_id, thread_type=thread_type)
```

**Comment by 403error403** [comment]
Hello Sir. Can you help me to make a fb chat bot? I am facing some minor
problems but I can't solve these. I need a brief resource also. Please help
me. Thanks in advance.😊
