### ISSUE TITLE
Errors when login 

### ISSUE THREAD

**Issue by AgonyCode** [carpedm20/fbchat#597]
It was good, but today, I cannot log in to the Facebook account. Thank you so much. 

Code:
import fbchat
import logging
client = fbchat.Client(username, password, logging_level=logging.DEBUG)

Attempt #1 failed, retrying
Traceback (most recent call last):
  File "/Users/david/PycharmProjects/Messenger/venv/lib/python3.8/site-packages/fbchat/_client.py", line 205, in login
    self._state = State.login(
  File "/Users/david/PycharmProjects/Messenger/venv/lib/python3.8/site-packages/fbchat/_state.py", line 149, in login
    return cls.from_session(session=session)
  File "/Users/david/PycharmProjects/Messenger/venv/lib/python3.8/site-packages/fbchat/_state.py", line 186, in from_session
    fb_dtsg = FB_DTSG_REGEX.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by devkarim** [comment]
What fbchat version are you using? If it is 2.0.0a3 then perhaps you will need to change it to 2.0.0a2 by using `pip install fbchat==2.0.0a2` as I've encountered a similar issue, thanks to #581.

If it is still an issue, try logging into the account via your browser and check whether anything blocks the way.

**Comment by AgonyCode** [comment]
> What fbchat version are you using? If it is 2.0.0a3 then perhaps you will need to change it to 2.0.0a2 by using `pip install fbchat==2.0.0a2` as I've encountered a similar issue, thanks to #581.
> 
> If it is still an issue, try logging into the account via your browser and check whether anything blocks the way.

Thank you so much, I was using 1.9.6, now I upgraded my version and it works, but too many functions need to be modified now.
