### ISSUE TITLE
Can't log in if two-factor authentication is enabled

### ISSUE THREAD

**Issue by kylegoetz** [carpedm20/fbchat#6]
You just get

raise Exception("id or password is wrong") 

in response. Password and ID are definitely correct because I double-checked them by direct copy and paste via browser.

If two-factor and code generator are disabled, it works but gives the "data" error that is listed as another issue in the issue tracker.

**Comment by dmartauz** [comment]
I cannot even login wiith newly registered FB accoung which has Locin Approvals and Code Generator features disabled by default? I get always get "id or password is wrong" Exception. Any ideas?

**Comment by kyjak** [comment]
Using the app password does not work for me either and I cannot login using this library at all.

**Comment by madsmtm** [comment]
Hi @kyjak and @kylegoetz, I'll assume this works now since 2FA support were added, if this is incorrect please reopen this ;)
