### ISSUE TITLE
[FIXED] Bug in reception of images

### ISSUE THREAD

**Issue by thekindlyone** [carpedm20/fbchat#60]
When images without text body is sent, it just called `on_message_error` and not `on_message` making users unable to handle them.

**Comment by Bravo111** [comment]
@thekindlyone always catch "TypeError: the JSON object must be str, not 'bytes'" exception. Even when use your example (and image url)

**Comment by thekindlyone** [comment]
@Bravo111 which example?

**Comment by Bravo111** [comment]
I run this code with python3.5: 
`imgurl = "http://i.imgur.com/LDQ2ITV.jpg" `
`client.sendRemoteImage(friend.uid, image=imgurl)`
and get an [error](https://www.dropbox.com/s/zcwc8nt7gdmunqg/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202016-08-31%2013.58.31.png?dl=0).
I guess there is a problem in this line `return json.loads(r._content[9:])['payload']['metadata'][0]['image_id']`.

**Comment by thekindlyone** [comment]
@Bravo111 this is the reception of images thread. You are talking about sending images.
But this is not happening in 2.7. Let me check.

**Comment by thekindlyone** [comment]
@Bravo111  try this instead of the offending line.. should work.   
 `return json.loads(r._content[9:].decode('utf-8'))['payload']['metadata'][0]`

**Comment by thekindlyone** [comment]
There are too many pulls right now, and a little bit of a mess due to my inexperience with git. I am pausing sending any more PRs unless the ones already sent are merged. Clone the project and try what I said. Lemme know if it works.

**Comment by Bravo111** [comment]
@thekindlyone, yes, it works great. Don't forget `['image_id']` in the end of this line! 
Is it possible to receive images with Echobot now?

**Comment by thekindlyone** [comment]
Yes, image receiving works, but I havent tested it with python3. Please test and tell.

**Comment by Bravo111** [comment]
@thekindlyone, unfortunately it receives empty message with `'has_attachment': False`.

**Comment by thekindlyone** [comment]
@Bravo111 , receiving , right? Check the metadata.. the urls for the images are in there.

**Comment by Bravo111** [comment]
@thekindlyone, is `image_ids[0]` what I need? Because there are nothing else in output but timestamps and ids.

**Comment by thekindlyone** [comment]
@Bravo111 , no , in the on_message method, that you overrode, you get a metadata argument. The url is in there.
![image](https://cloud.githubusercontent.com/assets/2511509/18133417/211a68a6-6fb8-11e6-9ddd-9359041c6287.png)

**Comment by Bravo111** [comment]
Think we have different output
![2016-08-31 17 55 32](https://cloud.githubusercontent.com/assets/16646586/18133678/8fd9f9de-6fac-11e6-9339-c1fc59657d3a.png)

**Comment by thekindlyone** [comment]
@Bravo111 are you sending or receiving? this output looks like you have debug=True and are sending. Show test code.

**Comment by Bravo111** [comment]
Receiving. Here's the code:
![2016-08-31 17 59 47](https://cloud.githubusercontent.com/assets/16646586/18133807/1af0e848-6fad-11e6-9425-ad2a86bfa616.png)

**Comment by thekindlyone** [comment]
@Bravo111  do you see the metadata argument in the on_message method? That is where the url is. Instead of printing message, print metadata. The output you showed me is generated while sending the echo. Turn debug=False if the output is confusing you.

**Comment by Bravo111** [comment]
@thekindlyone, yes, now all works perfect. Thanks for tips.
