### ISSUE TITLE
mark as unread

### ISSUE THREAD

**Issue by thewind11235** [carpedm20/fbchat#600]
How can i mark as unread when auto reply? My friends complained about me reading without rep. Thanks!

**Comment by syspic** [comment]
this [method](https://github.com/carpedm20/fbchat/blob/43aa16c32dfd6428768fd1bd9731b2f44aaf2220/fbchat/_client.py#L579)

But i dont know how that works from the other persons point of view. Does the `read` message go away? i dont know . If you find out id be happy to know!
