### ISSUE TITLE
__init__() takes 1 positional argument but 2 positional arguments  were given

### ISSUE THREAD

**Issue by LightSN** [carpedm20/fbchat#601]
Hello,
I was trying to mention somebody and i got this error: 
"__init__() takes 1 positional argument but 2 positional arguments  were given"
My code:
```
import fbchat
from fbchat import Message

session = fbchat.Session.login("mail", "pass")
listener = fbchat.Listener(session=session, chat_on=False, foreground=False)


for event in listener.listen():
    if isinstance(event, fbchat.MessageEvent):
        print(f"{event.message.text} from {event.author.id} in {event.thread.id}")
        if event.message.text == "!Test":

        	event.thread.send_text(
        		text = "Test",
        		mentions = Message.format_mentions("{p}",("my_fbid", "Test"),p = ("my_fbid", "Test")),
        		)
```
Also I got this error in examples

**Comment by syspic** [comment]
Which class is the error coming from? 


The __init__ function is where the class gets initialized. it takes at minimum one argument `self`. If you want more you can do something like `def __init__(self, positionalArg1, positionalArg2 )`

https://www.geeksforgeeks.org/__init__-in-python/ is a good source
