### ISSUE TITLE
FB Accounts keep getting banned

### ISSUE THREAD

**Issue by szymeklimek** [carpedm20/fbchat#609]
Hello, the accounts I've been using keep getting blocked. Facebook requests multiple things such as phone number authentication, selfie photos and ID. I've been verifying the accounts using my phone number and using session cookies in the script, but now I can't access any of  the accounts. 

Is my IP address blacklisted from fb? Does anyone have any ideas from past experience how to get an account working again? 

Thanks in advance.

**Comment by HunterAzar** [comment]
On what are you running it?
VPS, computer?

**Comment by szymeklimek** [comment]
I'm got banned while testing the app on Windows 10 computer. It's mostly run on google compute engine cm, but I had no issues there

**Comment by HunterAzar** [comment]
Are you tried make session on google compute, and then use them in win10?

**Comment by HunterAzar** [comment]
Working?

**Comment by szymeklimek** [comment]
> Working?

Yeah, it's working. Let's hope it won't get banned this time around. But STILL I can't log into the account from my personal pc, logging in only works on the google vm.
