### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sulavmhrzn** [carpedm20/fbchat#615]
Traceback (most recent call last):
  File "/home/sulav/.local/share/virtualenvs/facbook-autoreply-bot-Rb9hz_6h/lib/python3.8/site-packages/fbchat/_client.py", line 205, in login
    self._state = State.login(
  File "/home/sulav/.local/share/virtualenvs/facbook-autoreply-bot-Rb9hz_6h/lib/python3.8/site-packages/fbchat/_state.py", line 151, in login
    return cls.from_session(session=session)
  File "/home/sulav/.local/share/virtualenvs/facbook-autoreply-bot-Rb9hz_6h/lib/python3.8/site-packages/fbchat/_state.py", line 190, in from_session
    revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])

**Comment by dbieber** [comment]
I am running into this issue too.
It looks like Facebook is redirecting my login attempt:
"You&#039;re using a browser that isn&#039;t supported by Facebook, so we&#039;ve redirected you to a simpler version to give you the best experience"
I see you closed the issue shortly after opening it. How did you resolve it?

Edit: It seems like changing the user agent got me past this issue.
I then also had to update the `FB_DTSG_REGEX` to `re.compile(r'"name":"fb_dtsg","value":"(.*?)"')`.
And now FB isn't sending me 2-factor codes, so I'll have to sort that out. I think I'm close to being able to use fbchat again though...

**Comment by sulavmhrzn** [comment]
Didn't realize i closed the issue. It would be really helpful if you could update the answer after you figured out the answer  to 2fa issue as well.

**Comment by clem-ant** [comment]
Hi @sulavmhrzn, I have the same issue as you, did you figured out how to fix it ?

**Comment by Hasibulkarimratul** [comment]
same issue ! Don't know what to do !  -__- If you guys find any quick fixes please write it down here :( .

**Comment by dbieber** [comment]
When I turned off 2FA and made the two changes mentioned above, the library works again for me.
I haven't been able to turn 2FA back on yet though because the 2FA codes aren't being sent.

Edit:
I've successfully turned on 2FA using the Authenticator app; I wasn't able to get SMS 2FA working unfortunately.

**Comment by sulavmhrzn** [comment]
Tried changing user agent and FB_DTSG_REGEX but no luck.

**Comment by dbieber** [comment]
The way I figured out the issue for myself was to add
print(r.text) before the line with the error (e.g. in `/home/sulav/.local/share/virtualenvs/facbook-autoreply-bot-Rb9hz_6h/lib/python3.8/site-packages/fbchat/_state.py`) in order to get visibility into what was happening.
In my case, I saw that FB was redirecting me to a different version of FB. Changing the user agent prevented the redirecting from happening.

I then hit a second error and used the same print(r.text) trick to see that the format of fb_dtsg (not sure what this is) had changed, and that's what lead me to update the regex.

**Comment by dbieber** [comment]
I got an email requesting more detail about how I resolved the issue. Specifically the two changes I made were:

1. In _util.py, at line 46:
```
USER_AGENTS = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36",
]
```
2. In _state.py, at line 12:
```
FB_DTSG_REGEX = re.compile(r'"name":"fb_dtsg","value":"(.*?)"')
```

**Comment by sulavmhrzn** [comment]
Ayee it worked now. Thank You @dbieber

**Comment by xaadu** [comment]
Change 

revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])

to

revision = 1 

I don't see exact use of this revision and It works just fine for me! You can use any integer you want as the value. 

Thanks @dbieber for your perfect solution! There was a problem before for using the user agent. I think You've solved two problem at once!

**Comment by suvanjanprasai** [comment]
revision = 1   was the right solution thanks xaadu and sulavmhrzn

**Comment by karlicoss** [comment]
@dbieber 's solution worked, also convenient to use even without modifying the `fbchat` source code, e.g.:
https://github.com/karlicoss/fbmessengerexport/blob/ff000ac5edaf25441f5e7763538de4e1d530c1d6/export.py#L13-L18
```python
import fbchat # type: ignore
### see https://github.com/fbchat-dev/fbchat/issues/615#issuecomment-710127001 
import re
fbchat._util.USER_AGENTS    = ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"]
fbchat._state.FB_DTSG_REGEX = re.compile(r'"name":"fb_dtsg","value":"(.*?)"')
```

**Comment by emilstahl97** [comment]
> Change
> 
> revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])
> 
> to
> 
> revision = 1
> 
> I don't see exact use of this revision and It works just fine for me! You can use any integer you want as the value.
> 
> Thanks @dbieber for your perfect solution! There was a problem before for using the user agent. I think You've solved two problem at once!

this solved my problem

**Comment by KaziMahbuburRahman** [comment]
> Change
> 
> revision = int(r.text.split('"client_revision":', 1)[1].split(",", 1)[0])
> 
> to
> 
> revision = 1
> 
> I don't see exact use of this revision and It works just fine for me! You can use any integer you want as the value.
> 
@xaadu vai 🥇

**Comment by dbieber** [comment]
I've had to change line 12 of _state.py again. I now use:

`FB_DTSG_REGEX = re.compile(r'"DTSGInitialData",\[\],{"token":"(.*?)"')`

**Comment by david-dj12** [comment]
I'm nerd, nothing was working it getting worse
