### ISSUE TITLE
Get ThreadID from Listen for on_message

### ISSUE THREAD

**Issue by litobro** [carpedm20/fbchat#62]
I'm slogging through the code here and maybe I'm just missing something obvious, but is there a way to get the ThreadID in the on_message function? The author_id is available (while author_name is generally not) but when trying to reply, it would be useful to reply into the same thread.

**Comment by thekindlyone** [comment]
PR #56 adds getUserInfo to get name from uid. As for thread_id, have you checked the metadata?

**Comment by litobro** [comment]
I'm going through the metadata now trying to access a thread_id, there were some issues for python 3.5 in PR #56 for getUserInfo. I was getting an error on an iteritems() call and hadn't had time to debug the compatibility yet.

**Comment by thekindlyone** [comment]
ugh, 3.x doesn;t have iteritems. items in 3 does what iteritems did in 3.5.

**Comment by litobro** [comment]
Unless I'm mistaken the metadata doesn't contain the thread_id either. It does have a "offlineThreadingId" that if I try to send a message to I receive a 500 error in response.

**Comment by thekindlyone** [comment]
I fixed the iteritems thing, but don't know about thread_id. Can't you just reply to the author_id? Does it not always reply to same thread?

**Comment by litobro** [comment]
Replying to the author_id seems to always reply directly (1to1) with the author of the message, even in a group chat.

**Comment by thekindlyone** [comment]
The group chat in the js wrapper has some extra things going on. But the current PR situation is pretty messed up due to my inexperience with git, so am not doing any extra functionality till my current PR's are merged or rejected.

**Comment by Schmavery** [comment]
In the js wrapper, it looks like we're first checking if the `tid` field on the message exists, and then preferring to use that, then trying to use the `thread_fbid` and failing that, the `other_user_fbid`.  It's possible that this is a little out of date and handles cases that no longer exist, but it seems to be working.

**Comment by litobro** [comment]
Poking around some more now, it seems that the `threadFbId` and `actorFbId` definitely exist in the metadata. Not sure how I missed the tread one. Don't see a `tid` anywhere, but I'm going to have to think a bit about how to implement this if the maintainer wants it part of the main library. Otherwise I can just implement a simple fall through case on my bot.

**Comment by thekindlyone** [comment]
@litobro just follow the js and clone whatever it is doing in python. Worked for me so far. :P

**Comment by litobro** [comment]
I'm going to close this issue and reopen as an issue about replying to groups.
