### ISSUE TITLE
Cannot reply to groups

### ISSUE THREAD

**Issue by litobro** [carpedm20/fbchat#63]
If a group_id is given and the message type of "group" passed in, it fails to send a message to anybody and returns a 200.

**Comment by kasem123** [comment]
In case of a single user message
'other_user_fbid' : recipient_id,

In case of a group message
'thread_fbid' : recipient_id,

that seems to do it, at least for me

**Comment by Dgameman1** [comment]
@kasem123 Know how to fix this for GetThreadInfo?

**Comment by madsmtm** [comment]
Facebook has changed a lot of things, and `fbchat` has been updated, so I'm assuming this is outdated ;)
