### ISSUE TITLE
Alert Bot

### ISSUE THREAD

**Issue by A-STOP** [carpedm20/fbchat#632]
Hi! I want to make a bot that alerts you using fbchat. So basically the bot chats to a specific person and alerts that person. I couldn't find any tutorials anywhere. I'm new to coding and I don't know where to start. Can someone help me?

**Comment by nettoollams** [comment]
nvm guys I figured it out. 

import fbchat
from fbchat import Client, log
from fbchat.models import *
import re

fbchat._util.USER_AGENTS    = ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"]
fbchat._state.FB_DTSG_REGEX = re.compile(r'"name":"fb_dtsg","value":"(.*?)"')

client = Client('<email>', '<password>')
client.send(Message(text='hi dear, send bobs and vegena'), thread_id='<user_id>', thread_type=ThreadType.USER)
client.logout()

**Comment by A-STOP** [comment]
Nvm guys I figured it out. This isn't an alert bot tho. It just sends a message to a specific person.

import fbchat
from fbchat import Client, log
from fbchat.models import *
import re

fbchat._util.USER_AGENTS    = ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"]
fbchat._state.FB_DTSG_REGEX = re.compile(r'"name":"fb_dtsg","value":"(.*?)"')

client = Client('email', 'password')
client.send(Message(text='message'), thread_id='user_id', thread_type=ThreadType.USER)
client.logout()

**Comment by A-STOP** [comment]
This is how I got the user ID.

import fbchat
from fbchat import Client, log
from fbchat.models import *
import re

fbchat._util.USER_AGENTS    = ["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"]
fbchat._state.FB_DTSG_REGEX = re.compile(r'"name":"fb_dtsg","value":"(.*?)"')

client = Client('email', 'password')
# Fetches a list of all users you're currently chatting with, as `User` objects
users = client.fetchAllUsers()
print("users' IDs: {}".format([user.uid for user in users]))
print("users' names: {}".format([user.name for user in users]))
