### ISSUE TITLE
Cant login in my account 

### ISSUE THREAD

**Issue by edikiuspro** [carpedm20/fbchat#639]
Error:
fbchat._exception.FBchatUserError: Login failed. Check email/password. (Failed on url: https://m.facebook.com/cookie/consent-page/?next_uri=https%3A%2F%2Fm.facebook.com%2Fhome.php%3Frefsrc%3Dhttps%253A%252F%252Fwww.facebook.com%252F&_rdr)

**Comment by m-el-azzouzi** [comment]
Hey, look here mate
#638
