### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by edikiuspro** [carpedm20/fbchat#640]
Traceback (most recent call last):
  File "C:\Users\Admin\Project\Voting.py", line 326, in <module>
    client=BotGrupowy("***","***")
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fbchat\_client.py", line 103, in __init__
    self.login(email, password, max_tries, user_agent=user_agent)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fbchat\_client.py", line 205, in login
    self._state = State.login(
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fbchat\_state.py", line 156, in login
    return cls.from_session(session=session)
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\fbchat\_state.py", line 192, in from_session
    fb_dtsg = FB_DTSG_REGEX.search(r.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by edikiuspro** [comment]
Debug info:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): m.facebook.com:443
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET / HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /login.php?login_attempt=1 HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?refsrc=https%3A%2F%2Fwww.facebook.com%2F&_rdr HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /cookie/consent-page/?next_uri=https%3A%2F%2Fm.facebook.com%2Fhome.php%3Frefsrc%3Dhttps%253A%252F%252Fwww.facebook.com%252F&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "POST /cookie/consent/?next_uri=https%3A%2F%2Fm.facebook.com%2Fhome.php%3Frefsrc%3Dhttps%253A%252F%252Fwww.facebook.com%252F&amp;sid=jlm4Zms4rW3SyGJsgSc0&amp;m_basic_source_surface=COOKIE_CONSENT_PAGE HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://m.facebook.com:443 "GET /home.php?refsrc=https%3A%2F%2Fwww.facebook.com%2F&__ccr=FQQREREA.ARYhHxu2jHjH2--J36zxBLPTC9H0d0wQLpzU5g9zCq5yrOxY&_rdr HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.facebook.com:443
DEBUG:urllib3.connectionpool:https://www.facebook.com:443 "GET / HTTP/1.1" 200 None

**Comment by dbieber** [comment]
If you print(r.text) at line 182 of _state.py, you'll see there's the following:
`["DTSGInitData",[],{"token":"<token>","async_get_token":"<async_token>"},<number>]`
Maybe this info is what's needed?

**Comment by edikiuspro** [comment]
> If you print(r.text) at line 182 of _state.py, you'll see there's the following:
> `["DTSGInitData",[],{"token":"<token>","async_get_token":"<async_token>"},<number>]`
> Maybe this info is what's needed?
i used print(r.text) and found new problem
(https://user-images.githubusercontent.com/50236306/111641524-88692580-87fd-11eb-8b59-2e491e2b8356.png)

**Comment by orzechszek** [comment]
in _state.py replace FB_DTSG_REGEX:
`FB_DTSG_REGEX = re.compile(r'"DTSGInitData",\[\],\{"token":"(.*?)"')`

**Comment by dbieber** [comment]
I can confirm that worked for me. Thanks @orzechszek!

**Comment by orzechszek** [comment]
If it works, please also update in v1 project - fbchat 1.9.7 available through pip.

**Comment by edikiuspro** [comment]
Thank you very much @orzechszek
