### ISSUE TITLE
Client.send() always returns False

### ISSUE THREAD

**Issue by lyneca** [carpedm20/fbchat#67]
The call to `self._post(SendURL, data)` in `Client.send()` is returning a 404 error. After comparing it with captured requests from messenger.com and facebook.com, the request URL matches neither; is `https://www.facebook.com/ajax/mercury/send_messages.php` still correct?

All other functionality seems to be fine except for sending messages. This occurs for both group and individual conversations.

**Comment by thekindlyone** [comment]
https://github.com/Schmavery/facebook-chat-api/issues/339

**Comment by lyneca** [comment]
I tested facebook-chat-api and I could send messages using it.

**Comment by Zulex** [comment]
Client.send(id, message) seems to be working fine on my end. Did you use the right id?

**Comment by lyneca** [comment]
Yup, same ID works in the Node version.

**Comment by Dgameman1** [comment]
Client send works for me as well.

**Comment by JarbasAI** [comment]
started having this problem out of nowhere, always 404

**Comment by Bankde** [comment]
Hi @JarbasAI 
Is there any chance you're running your program for a week or so ?
https://github.com/Schmavery/facebook-chat-api/issues/202
https://github.com/Schmavery/facebook-chat-api/issues/156

If so, relogin will help. (I have tried many other methods but couldn't make it)
In my case, I schedule the relogin every 6 hours and everything seems to work fine for months.

**Comment by madsmtm** [comment]
Assuming ^ fixed this ;)
