### ISSUE TITLE
Threading doesn't work with Echobot

### ISSUE THREAD

**Issue by Zulex** [carpedm20/fbchat#69]
Hello all,

I'm using the echobot in a seperate thread of a python file. The threading looks something like this code under. When running the python file it is able to log in to Facebook and echo messages. But script1 isn't running at all, it seems like Echobot is the only thing running. Even if the script is a simple print function it won't run. Am I missing something or is my code just wrong?

if **name**==  '**main**':
     p1 = threading.Thread(target = script1 )
     p1.start()
     p2 = threading.Thread(target =   EchoBot("<email>", "<password>").listen )
     p2.start()

Thanks!

**Comment by WeiTang114** [comment]
I tried a similar script and found only this working:

```

p1 = threading.Thread(target = script1 )
p1.start()

EchoBot("", "").listen()
```

**Comment by madsmtm** [comment]
Assuming ^ fixed this ;)
