### ISSUE TITLE
When sending unicode message,  throw encoding exception

### ISSUE THREAD

**Issue by liqiangsu** [carpedm20/fbchat#78]
Python 3.4 64bit  Winows 10
Although the message was sent successfully, the program throws an exception as following:

Traceback (most recent call last):
    sent = client.send(friend.uid, u"\u4e00")
  File "C:\Python34\lib\site-packages\fbchat\client.py", line 292, in send
    print(data)
  File "C:\Python34\lib\encodings\cp850.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 731-743: character maps to <undefined>

**Comment by dstelzer** [comment]
This is actually a limitation your terminal's output encoding. Python tries to print out the message for debugging purposes, but can't find a way to print \u4e00 to a Windows terminal. Changing your output encoding (or turning debugging off) should fix it.

**Comment by Charliiee** [comment]
That happened to me when I was creating my chat. I used windows 8 at that time, but as @dstelzer said that's a problem with the cmd. All you have to do is changing encoding on print.
I fixed it like so: [fbchat-terminal/chat.py](https://github.com/Charliiee/fbchat-terminal/blob/master/fbchat-terminal/chat.py#L89).
