### ISSUE TITLE
sendLocalImage() error

### ISSUE THREAD

**Issue by kenykau** [carpedm20/fbchat#79]
can initial and send message to friend, but sending local image returns follow error:
```
send = client.sendLocalImage(friend[0].uid, message="<hi>", image="c:/image.jpg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\fbchat\client.py", line 317, in sendLocalImage
    image_id = self.uploadImage({'file': (image, open(image), mimetype)})
  File "c:\Python27\lib\site-packages\fbchat\client.py", line 327, in uploadImage
    return json.loads(r._content[9:])['payload']['metadata'][0]['image_id']
TypeError: 'NoneType' object has no attribute '__getitem__'
```
OS: Windows Server 2012R2
Python: 2.7

Thanks in advance

**Comment by kenykau** [comment]
Update:
I track down the code here are something that I found that:
`return json.loads(r._content[9:])['payload']['metadata'][0]['image_id']
print(r)
#r returns 
#<Response [200]>`

but in r._content I get
`for (;;);{"__ar":1,"__sf":"o","payload":{"uploadID":null,"metadata":[]},"bootloadable":{},"ixData":{},"lid":"6350400494084450070"}`

there is no data in metadata

**Comment by dstelzer** [comment]
Facebook seems to have changed how images are handled in Messenger. Now a second request seems to be necessary to get the URL of a received image or the ID of a sent one, and it requires parameters which I don't understand at all. :/

**Comment by kenykau** [comment]
Thanks alot dstelzer
