### ISSUE TITLE
bug in getThreadList() and getUsers()

### ISSUE THREAD

**Issue by wannaphongcom** [carpedm20/fbchat#8]
bug in getThreadList() and getUsers()
```python
TypeError: __repr__ returned non-string (type bytes)
```

**Comment by carpedm20** [comment]
Hmm.. this wasn't happened before your pull requests. Could you explain what did you fix during #7 ?

**Comment by wannaphongcom** [comment]
I have edited client.py line 18.  it can run no problem, but when I run it, it was found that there is a bug in the getThreadList () and getUsers ().

**Comment by wannaphongcom** [comment]
https://github.com/carpedm20/fbchat/pull/7 I can fix in login and sendMessage().

**Comment by wannaphongcom** [comment]
My English is not good. I am sorry.

**Comment by carpedm20** [comment]
#7 Solved

**Comment by wannaphongcom** [comment]
Good news. Thank you.
