### ISSUE TITLE
getThreadInfo logic no longer follows request pattern by Facebook

### ISSUE THREAD

**Issue by ankmathur96** [carpedm20/fbchat#83]
I've been trying to use getThreadInfo to get messages from a certain thread ID. Right now, there seems to be logic indicating that the start param must be less than the end param. There's a couple of issues with this function as written:

1. start, end, timestamp are not descriptive parameter names because, clearly, the parameters being set in the payload are offset and limit, which is not the same concept.
2. Point 1 is indicative of a bug in this code. If you look at how FB is making these requests on their messages loading page, they are incrementing offset, holding limit to be 80, and the timestamp appears to be changing. It is, in fact, decreasing with each new request. I think it's being set to the timestamp of the last message in the previous batch. The code in getThreadInfo is setting it to be now, which is why, for chats with many messages, this function does not behave properly.

I'm experimenting with a fix right now, but I wanted to see if anyone else was having this issue.

**Comment by Schmavery** [comment]
We've had a complaint or two about this on our api as well (https://github.com/Schmavery/facebook-chat-api/issues/262).  I'd imagine you're right, and facebook has tweaked how they handle these parameters.
Do you understand why the offset is changing as well as the timestamp?  It seems like these would handle the same sort of thing...

**Comment by ankmathur96** [comment]
It's not clear to me why it would be done this way. What I'm trying right now is just incrementing offset, leaving limit to be at 80, and setting timestamp to the earliest retrieved message from the last timestamp. This seems to be working somewhat for paginated requests, but I'm still getting some duplicates, so I haven't submitted a pull request.

**Comment by dstelzer** [comment]
The method I'm using is:
 - Set `limit` to whatever you like (I'm using 1024)
 - Set `timestamp` and `offset` to zero
 - Make a request
 - Set `timestamp` to `int(data['actions'][0]['timestamp']) - 1`
 - Set `offset` to `offset + len(data['actions'])`
 - Go back to step 2
Repeat until you have all the messages you want. This seems to work nicely.

As for why the redundancy, the timestamp seems to win out if they disagree. But I don't know why.

**Comment by ankmathur96** [comment]
This is how I am also doing it (except I'm using a much smaller offset (80)). I made the following changes to getThreadInfo that I think better reflect how the function should be used:

`        # this is pretty arbitrary, since timestamp is winning out anyway.
        if not end: end = start + 20
        # if end <= start: end = start + end

        data = {}
        data['messages[user_ids][%s][offset]'%userID] =    start
        data['messages[user_ids][%s][limit]'%userID] =     end
        data['messages[user_ids][%s][timestamp]'%userID] = timestamp if timestamp is not None else now()`

**Comment by carpedm20** [comment]
Maybe #89 fixed this but not sure.

**Comment by madsmtm** [comment]
Reworked completely in v. `1.0.x`
