### ISSUE TITLE
Getting images from received messages

### ISSUE THREAD

**Issue by dstelzer** [carpedm20/fbchat#84]
Facebook no longer includes the URL for an image in the message data (only for a thumbnail). I've attached the progress I've made on this issue, which isn't enough for a pull request yet but may help others.

Facebook's response does still include a Facebook ID number.

In order to get the actual URL, a POST request is made to `https://www.messenger.com/webgraphql/query/` with URL parameters:
 - `query_id = [15-digit number in decimal]`
 - `dpr = 1.5`
 - `variables = {"id":"[the ID of the user]","photoID":"[the ID of the image]"}` (sent as a string containing JSON)

The `query_id` is generated by the server and sent to the client; I haven't figured out how yet. It doesn't accept arbitrary values:

    for (;;);{"__ar":1,"__sf":"m","error":1675007,"errorSummary":"Persisted Query Not Available","errorDescription":"You sent a query_id, which is no longer available. As a client, one should not reissue this query_id until it has been returned by the server again.","silentError":1,"payload":{"debug_info":"Query ID 98765432123456 is not available"},"bootloadable":{},"ixData":{},"lid":"*redacted number*"}

However, it's not bound to the particular image. The same query_id can be reused to get URLs for as many images as you want. TODO: only within a session? Connected to fb_dtsg?

**Comment by dstelzer** [comment]
Testing with the same parameters 20 hours later (and after ending the session) still gets me the image URL. So as soon as one query_id is found it should be sufficient.

**Comment by dstelzer** [comment]
More evidence suggests that a single query_id might even be usable by different users. If someone could send me either a query_id from their own account, or a Facebook image ID from a Messenger message, it would be much appreciated.

**Comment by madsmtm** [comment]
I've found that the query_id is always set `865890046879452`, independent of user account.

I've included an image, showing that the query_id is set directly in a source code file

I recon it's made such that Facebook can differentiate the type of request to `https://www.messenger.com/webgraphql/query/`

Also, in my case `dpr` is always set to `2.`
Don't think `dpr` changes anything ;)

**Comment by GAMELASTER** [comment]
@madsmtm 
The `doc_id` is something like internal application ID, so it's same for everyone.
Same it's with `query_id`, instead of sending the whole query, you use only ID (probably for security reasons).

**Comment by Schmavery** [comment]
Yeah, seems like a form of [persisted query](https://scaphold.io/community/blog/persisted-queries/)
