### ISSUE TITLE
Group messages broken?

### ISSUE THREAD

**Issue by JohnathonNow** [carpedm20/fbchat#88]
I noticed that the current version does not seem to work for sending messages to groups.
(client.send returns True, but the message does not appear in the chat.)
I was able to get it working again, but was wondering if anyone else had this issue and if it warrants a PR.

Thanks.

**Comment by MadeInPierre** [comment]
Hi, 
I have been trying to get the messages from a thread, and send one to a thread, but fbchat doesn't seem to allow a `thread_id` in `client.send()` or `client.getThreadInfo()`, as these methods require a `user_id` instead.
Currently I can only manipulate threads with a single person.

I am not very experienced, so if you found that this is something missing from fbchat, I would appreciate a fix !

**Comment by JohnathonNow** [comment]
See #89 for getting `client.getThreadInfo` working for groups. `client.send` is supposed to be able to support group threads with the `message_type` parameter.

**Comment by prometrix** [comment]
Im also having trubbel with the group messages, not sure I'm using it in the right way.
One thing is I'm not sure what to use as recipient_id when sending to a group chat.
A simple example for a echobot working with group chat would be great :-)

**Comment by carpedm20** [comment]
Merged #89
