### ISSUE TITLE
Not able to login from my webhost hosted in USA

### ISSUE THREAD

**Issue by shabnambanu1234** [carpedm20/fbchat#90]
Hi,

Using your APIs I am trying to login to my fb account from a python script but I am not able to login . Does this API still works? Here is my code:

import fbchat

client = fbchat.Client("100014895393956", "***********") // password hidden before pasting here

Thanks,
Shabnam

**Comment by carpedm20** [comment]
Maybe now it's work, after e847c551d151e393357a978b98d30e164daa9f94.
