### ISSUE TITLE
getThreadList doesn't seem to work

### ISSUE THREAD

**Issue by Dominykas97** [carpedm20/fbchat#95]
client.getThreadList(0) outputs that:

> [<fbchat.models.Thread instance at 0x7f5d87bb0e18>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0d88>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0e60>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0dd0>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0ea8>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0ef0>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0f38>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0f80>,
>  <fbchat.models.Thread instance at 0x7f5d87bb0fc8>,
>  <fbchat.models.Thread instance at 0x7f5d87b51050>,
>  <fbchat.models.Thread instance at 0x7f5d87b51098>,
>  <fbchat.models.Thread instance at 0x7f5d87b510e0>,
>  <fbchat.models.Thread instance at 0x7f5d87b51128>,
>  <fbchat.models.Thread instance at 0x7f5d87b51170>,
>  <fbchat.models.Thread instance at 0x7f5d87b511b8>,
>  <fbchat.models.Thread instance at 0x7f5d87b51200>,
>  <fbchat.models.Thread instance at 0x7f5d87b51248>,
>  <fbchat.models.Thread instance at 0x7f5d87b51290>,
>  <fbchat.models.Thread instance at 0x7f5d87b512d8>,
>  <fbchat.models.Thread instance at 0x7f5d87b51320>]

Every time getThreadList(0) gives different values.

> [<fbchat.models.Thread instance at 0x7fcc05cfee18>,
>  <fbchat.models.Thread instance at 0x7fcc05cfed88>,
>  <fbchat.models.Thread instance at 0x7fcc05cfee60>,
>  <fbchat.models.Thread instance at 0x7fcc05cfedd0>,
>  <fbchat.models.Thread instance at 0x7fcc05cfeea8>,
>  <fbchat.models.Thread instance at 0x7fcc05cfeef0>,
>  <fbchat.models.Thread instance at 0x7fcc05cfef38>,
>  <fbchat.models.Thread instance at 0x7fcc05cfef80>,
>  <fbchat.models.Thread instance at 0x7fcc05cfefc8>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f050>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f098>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f0e0>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f128>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f170>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f1b8>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f200>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f248>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f290>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f2d8>,
>  <fbchat.models.Thread instance at 0x7fcc05c9f320>]

Those hexadecimal values don't seem to be groups' IDs even if I convert them into decimal values.
Is there any other way to get groups' IDs?

**Comment by carpedm20** [comment]
Try:

    for t in client.getThreadList(0):
        print i.thread_fbid

or 

    for t in client.getThreadList(0):
        print t.thread_id

based on what you want. Hex values is related to memory address of python `fbchat.models.Thread` instance.

**Comment by Dominykas97** [comment]
OK, it works. Thank you.
